// Appendix A.5 — Cube Place Task: Complete Training Metrics
#import "../../../../shared/formatting/macros.typ": *
#import "../../../../shared/formatting/acronyms.typ": *
#import "../../../../shared/formatting/template.typ": faps-figure

= Appendix: Cube Place Task — Complete Training Metrics <appendix:place_metrics>

This appendix provides complete training curves for the cube place task across all three tensegrity variants. All plots are cut at 300k timesteps (#ac("PD") variant training duration). Figures are generated by `project_thesis/scripts/plot_appendix_place.py`; rerun with `make appendix-place` from `project_thesis/scripts/`.

== Reward Overview <appendix:place_reward_overview>

#faps-figure(
  image("../../../assets/figures/appendix/place_reward_overview.png", width: 100%),
  caption: [Cube place reward overview. *(a)*~Total reward — solid lines show the per-variant mean, the shaded envelope spans the per-iteration min/max range. *(b)*~Policy standard deviation ($sigma$).],
  short-caption: [Cube place reward overview],
) <fig:appendix_place_rewards>

== Task Metrics <appendix:place_task_metrics>

#faps-figure(
  image("../../../assets/figures/appendix/place_metrics.png", width: 100%),
  caption: [Cube place task metrics. *(a)*~Grasp success rate. *(b)*~Place success rate. *(c)*~Red-cube safety rate (remaining on conveyor). *(d)*~Mean episode length.],
  short-caption: [Cube place task metrics],
) <fig:appendix_place_metrics>

== Task Reward Components — Manipulation Pipeline <appendix:place_manipulation>

#faps-figure(
  image("../../../assets/figures/appendix/place_manipulation.png", width: 100%),
  caption: [Cube place manipulation pipeline rewards. *(a)*~Distance shaping toward the cube. *(b)*~Grasp reward (closure $times$ proximity). *(c)*~Lifting binary reward. *(d)*~Height bonus (proportional to lift distance).],
  short-caption: [Cube place manipulation rewards],
) <fig:appendix_place_manipulation>

== Task Reward Components — Placement and Target <appendix:place_placement>

#faps-figure(
  image("../../../assets/figures/appendix/place_placement.png", width: 100%),
  caption: [Cube place placement rewards. *(a)*~Goal-tracking shaping ($1 - tanh(d_"xy"/1.0)$, gated on grasp). *(b)*~Fine goal-tracking ($1 - tanh(d_"xy"/0.20)$). *(c)*~Release reward. *(d)*~Green-cube-in-target-drum bonus.],
  short-caption: [Cube place placement rewards],
) <fig:appendix_place_placement>

== Regularization and Training Diagnostics <appendix:place_diagnostics>

#faps-figure(
  image("../../../assets/figures/appendix/place_regularization.png", width: 100%),
  caption: [Cube place regularization terms. *(a)*~Action-rate penalty (ramps at 200k). *(b)*~Joint-velocity penalty (ramps at 200k). *(c)*~Joint-torque penalty. *(d)*~Belt-contact penalty.],
  short-caption: [Cube place regularization terms],
) <fig:appendix_place_regularization>

#faps-figure(
  image("../../../assets/figures/appendix/place_diagnostics.png", width: 100%),
  caption: [Cube place training diagnostics. *(a)*~Policy loss. *(b)*~Value-function loss. *(c)*~Entropy loss. *(d)*~KL-adaptive learning-rate schedule.],
  short-caption: [Cube place training diagnostics],
) <fig:appendix_place_diagnostics>
