// Appendix A.7 — Step-Response Time Traces
#import "../../../../shared/formatting/macros.typ": *
#import "../../../../shared/formatting/acronyms.typ": *
#import "../../../../shared/formatting/template.typ": faps-figure

= Appendix: Step-Response Time Traces <appendix:step_responses>

This appendix collects the full time-trace plots for the step-response validation experiments referenced in @subsec:step_results. Plots are grouped by actuation mode (PD, constant-tension tendon, physical antiparallelogram tendon) and ordered Elbow → Wrist-X → Wrist-Y per mode. Within each panel, dashed lines show the commanded setpoint and solid lines the measured joint angle. Wrist-X traces and the physical-tendon elbow trace are flagged as "Data not recorded" placeholders pending re-running of the corresponding experiments. Figures are generated by `project_thesis/scripts/plot_step_responses.py`; rerun with `make step-traces` from `project_thesis/scripts/`.

#faps-figure(
  image("../../../assets/figures/appendix/step_pd_grouped.png", width: 100%),
  caption: [PD-controlled step responses (`ImplicitActuator`, $K = 400$, $D = 20$). *(a)*~Elbow joint at $20 degree$/$30 degree$/$40 degree$. *(b)*~Wrist X — placeholder; re-run `step_response` on `wrist_x_joint` with the PD `ImplicitActuator` at $10 degree$/$20 degree$/$30 degree$. *(c)*~Wrist Y at $10 degree$/$20 degree$/$30 degree$.],
  short-caption: [PD step responses (Elbow / Wrist-X / Wrist-Y)],
) <fig:appendix_step_pd>

#faps-figure(
  image("../../../assets/figures/appendix/step_tendon_grouped.png", width: 100%),
  caption: [Constant-tension tendon step responses (PI--D cascade on cable tension; elbow $K_p = 50$, $K_i = 4$, $K_d = 2$; wrist $K_p = 10$, $K_i = 1.5$, $K_d = 0.6$). *(a)*~Elbow joint. *(b)*~Wrist X — placeholder; re-run with the constant-tension tendon controller. *(c)*~Wrist Y.],
  short-caption: [Constant-tension tendon step responses],
) <fig:appendix_step_tendon>

#faps-figure(
  image("../../../assets/figures/appendix/step_physical_grouped.png", width: 100%),
  caption: [Physical antiparallelogram tendon step response. *(a)*~Elbow joint placeholder — re-run `step_response` on the physical antiparallelogram elbow ($K_p = 75$, $K_i = 6$, $K_d = 3$) at $20 degree$/$30 degree$/$40 degree$ and export per-step CSVs. Per-amplitude rise/settle/NRMSE values are already aggregated into @fig:step_metrics in @subsec:step_results. *(b)*~Wrist X — placeholder. *(c)*~Wrist Y — placeholder; wrist behaviour is identical to the constant-tension tendon variant in @fig:appendix_step_tendon (the physical variant only redefines the elbow mechanism).],
  short-caption: [Physical tendon step response (Elbow)],
) <fig:appendix_step_physical>
