// Chapter 0.2: Background Citation Verification Log
// Per-section bullet list of every cited source in the Background and
// Prior Work chapters, with the PDF/section/page evidence that supports
// the claim and a clickable link to the local source file.
//
// Origin: extracted from inline `// VERIFIED:` comments that previously
// lived in chapters/background/2_*.typ. Kept here in the guideline so
// the thesis prose stays clean while the verification trail remains
// traceable. See `chapters/background/VERIFICATION_PROMPT_TEMPLATE.md`
// for the prompt that regenerates / refines these bullets per section.
//
// Path convention: links are written relative to this file
// (`guideline/chapters/`); four `..` segments reach `doc/`.

#import "../../../shared/formatting/macros.typ": *
#import "../../../shared/formatting/acronyms.typ": *

#let srcpdf(path, label: "PDF") = link("../../../../Literatur/sources/" + path)[#text(fill: rgb("#1a6f1a"))[#label]]

#heading(numbering: none)[Background — Citation Verification Log] <ch:bg-citation-log>

This appendix records, per Background subsection, which page / section /
quotation in each cited PDF supports the corresponding claim in the
thesis. Each bullet shows the citation key, a brief evidence pointer,
and a #emph[(PDF)] link to the local source file under
`doc/Literatur/sources/`. Line references in square brackets (e.g.
#raw("[2_2:18]")) point at the line in the corresponding
`chapters/background/2_*.typ` file where the claim appears.

== §2.1 Reinforcement Learning for Robotic Manipulation

// Last verified: 2026-04-22 (line-by-line pass, see VERIFICATION_PROMPT_TEMPLATE.md).
// Line numbers refer to chapters/background/2_1_ReinforcementLearning.typ.

- *V1* — *@SuttonBarto2018*, *@Kober2013Survey* `[2_1:9]` — OK: textbook + survey introduced as canonical references for RL formalism and robotics-RL constraints respectively; Sutton & Barto Ch.~3 "Finite Markov Decision Processes" p.~47, Kober2013 §2.1 pp.~4--5 ("Reinforcement Learning in the Context of Classical Robotics"). #srcpdf("reinforcement_learning/Books/SuttonBarto2018.pdf", label: "SuttonBarto2018 PDF") — #srcpdf("reinforcement_learning/Survey_Articles/Kober2013.pdf", label: "Kober2013 PDF")
- *V2* — *@SuttonBarto2018* `[2_1:14]` — OK: MDP tuple $(cal(S), cal(A), P, r, gamma)$ matches Ch.~3 §3.1 p.~47 ("Finite Markov Decision Processes"); discounted return $G_t = sum gamma^k r_(t+k+1)$ p.~76 §3.4; performance measure $J(theta) = EE_(pi_theta)[sum gamma^t r_t]$ matches policy-gradient setup §13.2 p.~324 ("we seek to maximize performance, so its updates approximate gradient ascent in J"). #srcpdf("reinforcement_learning/Books/SuttonBarto2018.pdf")
- *V3* — *@Spaan2012POMDP*, *@SuttonBarto2018*, *@Kober2013Survey* `[2_1:16]` — OK (resolved 2026-05-02): partial-observability sentence now cites a formal POMDP reference (Spaan2012, _Reinforcement Learning: State-of-the-Art_ Springer 2012, Ch.~12 "Partially Observable Markov Decision Processes" — defines the POMDP tuple $(cal(S),cal(A),T,R,Omega,O)$ with observation model $O(o | s, a)$ and history-dependent optimal policy) plus Sutton \& Barto §17.3 "Partially Observable States" p.~465; the practical recurrent-policy / observation-stacking claim is supported by Kober2013 §2.1 pp.~4--5. #srcpdf("reinforcement_learning/Book_Chapters/Spaan2012.pdf", label: "Spaan2012 PDF") — #srcpdf("reinforcement_learning/Books/SuttonBarto2018.pdf", label: "SuttonBarto2018 PDF") — #srcpdf("reinforcement_learning/Survey_Articles/Kober2013.pdf", label: "Kober2013 PDF")
- *V4* — *@Kober2013Survey* `[2_1:23-29]` — OK: the three "key challenges" enumeration (continuous high-DoF control, contact-rich nonlinear dynamics, sparse/delayed feedback) maps to §1 p.~2 ("dimensionality, real-world samples, under-modeling and uncertainty, goal specification") and §3 "Challenges in Robot Reinforcement Learning". #srcpdf("reinforcement_learning/Survey_Articles/Kober2013.pdf")
- *V5* — *@Kober2013Survey*, *@SuttonBarto2018* `[2_1:32]` — OK: dense-vs-sparse reward / shaping discussion in Kober §6 "Tractability Through Reward" p.~17 ("the choice of an appropriate reward function ... is often a delicate matter"); Sutton & Barto §17.4 "Designing Reward Signals" p.~469 mirrors the trade-off. #srcpdf("reinforcement_learning/Survey_Articles/Kober2013.pdf", label: "Kober2013 PDF") — #srcpdf("reinforcement_learning/Books/SuttonBarto2018.pdf", label: "SuttonBarto2018 PDF")
- *V6* — *@Ng1999RewardShaping* `[2_1:35]` — OK (resolved 2026-05-02): the equation $F(s,a,s') = gamma Phi(s') - Phi(s)$ matches Theorem~1 p.~4 of Ng, Harada, Russell 1999 (ICML). Local PDF replaced with the Stuart Russell faculty-page copy (Berkeley, MD5 `9e20516d…`); page-4 text now extractable via PyMuPDF. Verbatim Theorem~1 statement: _"that $F$ is a potential-based shaping function is a necessary and sufficient condition for it to guarantee consistency with the optimal policy"_ (sufficiency + necessity sub-clauses follow). #srcpdf("reinforcement_learning/Conference_Papers/Ng1999.pdf")
- *V7* — *@Devlin2012DynamicPBRS* `[2_1:37]` — OK: AAMAS 2012 paper title "Dynamic Potential-Based Reward Shaping" abstract p.~1: dynamic (time-varying) potential functions preserve single-agent optimal policy invariance and Nash equilibria — directly supports the "even when the potential changes during an episode" claim. #srcpdf("reinforcement_learning/Conference_Papers/Devlin2012.pdf")
- *V8* — *@Popov2017DataEfficientManipulation* `[2_1:39]` — OK: Lego brick-stacking task introduced p.~1 right column; §VI "Composite Shaping Rewards" p.~6 introduces phase-gated reward components; sparse reward subtask list p.~7 ("STACK", "STACK\_AND\_LEAVE") matches the gated-phase pattern cited. #srcpdf("grasping_manipulation/Conference_&_Journal_Papers/Popov2017.pdf")
- *V9* — *@Icarte2022RewardMachines* `[2_1:41]` — OK: JAIR 73 (2022) paper "Reward Machines: Exploiting Reward Function Structure in Reinforcement Learning" — abstract and §1 p.~2 define finite-state reward machines as automata with per-state reward functions driven by propositional events; surname *Toro Icarte* (preserved correctly in thesis prose). #srcpdf("reinforcement_learning/Reward_Machines/ToroIcarte2022.pdf")
- *V10* — *@Zhu2020robosuite*, *@robosuite_pickplace_repo* `[2_1:43]` — OK (resolved 2026-05-02): the robosuite paper (arXiv:2009.12293) supports the conceptual phase-gated reward claim via §3.2 "Modular Design"; the literal API name `staged_rewards()` originates in the source file `robosuite/environments/manipulation/pick_place.py` (method definition with the docstring _"Returns staged rewards based on current physical states. Stages consist of reaching, grasping, lifting, and hovering"_; reach/grasp/lift/hover multipliers $0.1$/$0.35$/$0.5$/$0.7$). A local HTML snapshot of the GitHub blob page (commit `aaa8b9b`, accessed 2026-05-02) is filed alongside the bib entry `@robosuite_pickplace_repo`. #srcpdf("reinforcement_learning/Journal_Articles_&_Preprints/Zhu2020robosuite.pdf", label: "Zhu2020 PDF") — #srcpdf("reinforcement_learning/Source_Code/robosuite_pick_place_staged_rewards.html", label: "robosuite pick_place.py snapshot")
- *V11* — *@SuttonBarto2018* `[2_1:47]` — OK: actor--critic methods Ch.~13.5 p.~331; advantage function $A^pi(s,a) = Q^pi(s,a) - V^pi(s)$ §13.4 p.~329; baseline-in-policy-gradient discussion §13.4. #srcpdf("reinforcement_learning/Books/SuttonBarto2018.pdf")
- *V12* — *@Schulman2015GAE* `[2_1:50]` — OK: ICLR 2016 preprint, abstract p.~1 "an exponentially-weighted estimator of the advantage function that is analogous to TD($lambda$)"; bias--variance trade-off discussed §3 p.~4; GAE definition Eq.~(15) on p.~5 $hat(A)_t^"GAE"(gamma, lambda) = sum (gamma lambda)^l delta_(t+l)^V$. #srcpdf("reinforcement_learning/Preprints/Schulman2015GAE.pdf")
- *V13* — *@SuttonBarto2018*, *@Kober2013Survey* `[2_1:54]` — OK: exploration--exploitation trade-off Sutton & Barto §1.1 p.~3 ("the exploration--exploitation dilemma") and Ch.~2; Kober survey §3.1 "Curse of Dimensionality" p.~6 discusses long-horizon and unsafe-state exploration in robot-RL. #srcpdf("reinforcement_learning/Books/SuttonBarto2018.pdf", label: "SuttonBarto2018 PDF") — #srcpdf("reinforcement_learning/Survey_Articles/Kober2013.pdf", label: "Kober2013 PDF")
- *V14* — *@SuttonBarto2018*, *@Kalashnikov2018QTOpt*, *@Zhu2020robosuite* `[2_1:56]` — OK: stochastic policies Sutton & Barto §13.1 p.~322; Kalashnikov2018 (QT-Opt) p.~5 §IV explicitly defines the action vector $a in cal(A)$ as Cartesian translation $t in RR^3$, sin/cos rotation $r in RR^2$, *binary gripper open/close commands* $g_"open", g_"close"$, plus a termination flag — exactly the hybrid-action-space cited. Zhu2020robosuite §3 documents the parallel-jaw gripper action interface. #srcpdf("reinforcement_learning/Books/SuttonBarto2018.pdf", label: "SuttonBarto2018 PDF") — #srcpdf("reinforcement_learning/Preprints_&_Conference_Papers/Kalashnikov2018.pdf", label: "Kalashnikov2018 PDF") — #srcpdf("reinforcement_learning/Journal_Articles_&_Preprints/Zhu2020robosuite.pdf", label: "Zhu2020 PDF")
- *V15* — *@Kober2013Survey* `[2_1:58-59]` — OK: curriculum learning / progressive task difficulty Kober survey §6.1 "Reward Shaping" p.~17 and §5 "Reinforcement Learning in the Real World" pp.~14--15; episode-reset / state-distribution discussion §3.2 p.~7 ("most reinforcement-learning algorithms require ... resetting"). #srcpdf("reinforcement_learning/Survey_Articles/Kober2013.pdf")
- *V16* — *@Kober2013Survey*, *@SuttonBarto2018* `[2_1:61]` — OK: closing-paragraph reference to environment-design dependence reuses prior verifications V13/V15. #srcpdf("reinforcement_learning/Survey_Articles/Kober2013.pdf", label: "Kober2013 PDF") — #srcpdf("reinforcement_learning/Books/SuttonBarto2018.pdf", label: "SuttonBarto2018 PDF")
- *V17* — *@Kober2013Survey*, *@Tobin2017DomainRandomization*, *@Peng2018DynamicsRandomization* `[2_1:65]` — OK: simulation-training-rationale Kober survey §5 p.~14 ("simulations ... cheap to gather and inherently safe"); Tobin2017 abstract p.~1 "we randomize the renderer to expose the model to a wide range of environments at training time"; Peng2018 §IV.C p.~4 "Dynamics Randomization" lists mass, damping, motor gains, latency. #srcpdf("reinforcement_learning/Survey_Articles/Kober2013.pdf", label: "Kober2013 PDF") — #srcpdf("sim_to_real/Conference_Papers_&_Preprints/Tobin2017.pdf", label: "Tobin2017 PDF") — #srcpdf("sim_to_real/Conference_Papers_&_Preprints/Peng2018.pdf", label: "Peng2018 PDF")
- *V18* — *@Schulman2015GAE*, *@Schulman2017PPO*, *@Kober2013Survey* `[2_1:69-73, eq:ppo_clip]` — OK: PPO clipped surrogate equation transcription verified verbatim against Schulman2017 Eq.~(7) p.~3: "$L^"CLIP"(theta) = hat(EE)_t[min(r_t(theta) hat(A)_t, "clip"(r_t(theta), 1-epsilon, 1+epsilon) hat(A)_t)]$"; importance ratio $r_t(theta) = pi_theta(a_t|s_t)/pi_(theta_"old")(a_t|s_t)$ defined directly above Eq.~(6) on the same page; pairing with GAE for $hat(A)_t$ stated §6.1 p.~6. Kober2013 §6 supports the contact-rich-stability rationale. #srcpdf("reinforcement_learning/Preprints/Schulman2015GAE.pdf", label: "Schulman2015GAE PDF") — #srcpdf("reinforcement_learning/Preprints/Schulman2017PPO.pdf", label: "Schulman2017PPO PDF") — #srcpdf("reinforcement_learning/Survey_Articles/Kober2013.pdf", label: "Kober2013 PDF")
- *V19* — *@Schulman2017PPO* `[2_1:79]` — OK: stable-update claim restates Eq.~(7) clipping motivation p.~3 ("the second term ... removes the incentive for moving $r_t$ outside of the interval $[1-epsilon, 1+epsilon]$"). #srcpdf("reinforcement_learning/Preprints/Schulman2017PPO.pdf")
- *V20* — *@SuttonBarto2018* `[2_1:80]` — OK: Gaussian policies for continuous actions Sutton & Barto §13.7 p.~335 ("Policy Parameterization for Continuous Actions"). #srcpdf("reinforcement_learning/Books/SuttonBarto2018.pdf")
- *V21* — *@Kober2013Survey* `[2_1:81]` — OK: rollout-and-update training-loop fit for robotics Kober §4.2 "Policy Search" p.~12 and §5 "Reinforcement Learning in the Real World" p.~14. #srcpdf("reinforcement_learning/Survey_Articles/Kober2013.pdf")

== §2.2 Tendon-Driven Mechanisms and Linkage Kinematics

// Last verified: 2026-04-22 (line-by-line pass, see VERIFICATION_PROMPT_TEMPLATE.md).
// Line numbers refer to chapters/background/2_2_TendonLinkageMechanisms.typ.

- *V1* — *@Rao2021TDCRModeling*, *@Nemoto2022CableWrist* `[2_2:13]` — OK: Rao2021 (Front. Robot. AI 8:630245, 2021) "How to Model Tendon-Driven Continuum Robots and Benchmark Modelling Performance" — covers TDCR principles, accepted boundary use for general tendon-actuation framing. Nemoto2022 (IEEE RA-L 7(2):5727, 2022) abstract p.~1: "highly dynamic 2-DOF cable-driven robotic wrist based on a novel topology" — directly supports remote-actuation / low-distal-inertia claim. #srcpdf("tendon_robots/Review_Articles/Rao2021.pdf", label: "Rao2021 PDF") — #srcpdf("tendon_robots/Journal_Articles/Nemoto2022.pdf", label: "Nemoto2022 PDF")
- *V2* — *@Kobayashi1998NullSpaceStiffness*, *@MuralidharanWenger2021*, *@TsaiLee1989* `[2_2:16]` — OK: Kobayashi1998 abstract p.~1: "issues are discussed regarding tendon redundancy and joint stiffness adjustability for a robotic mechanism driven with redundant tendons"; §3 defines driving redundancy $alpha = M-N$, §4 derives bias tension $J^top f_b = 0$ for null-space co-contraction. Muralidharan2021 p.~1 "Optimal design and comparative study of two antagonistically actuated tensegrity joints" — direct support for antagonistic-pair / stiffness-modulation. TsaiLee1989 (ASME J. Mech. Trans. Auto. Design 111(1):59--65, scanned PDF) introduces the n+1-cable rule for force closure in graph-theoretic tendon-driven mechanisms (PDF text-layer is image-only; metadata-confirmed authorship Tsai \& Lee). The n+1 result is also independently attested by Pott2009 (V14 below) and Kobayashi1998 §3. #srcpdf("control_kinematics/Journal_Articles/Kobayashi1998.pdf", label: "Kobayashi1998 PDF") — #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Muralidharan2021.pdf", label: "Muralidharan2021 PDF") — #srcpdf("tendon_robots/Foundational_Works/TsaiLee1989.pdf", label: "TsaiLee1989 PDF")
- *V3* — *@Miyasaka2020HysteresisFriction*, *@Kato2016Neuroendoscopy* `[2_2:31]` — OK: Miyasaka2020 (IEEE/ASME T-Mech 25(2):1095, 2020) p.~1 title+abstract: "Modeling Cable-Driven Robot With Hysteresis and Cable--Pulley Network Friction" — direct match for cable stretch + friction + hysteresis. Kato2016 (Int. J. CARS, 2016) p.~1 title: "Tendon-driven continuum robot for neuroendoscopy: validation of extended kinematic mapping for hysteresis operation" — supports model-based hysteresis compensation. #srcpdf("tendon_robots/Journal_Articles/Miyasaka2020.pdf", label: "Miyasaka2020 PDF") — #srcpdf("tendon_robots/Journal_Articles/Kato2016.pdf", label: "Kato2016 PDF")
- *V4* — *@McCarthy2011*, *@Uicker2017* `[2_2:38]` — OK: McCarthy2011 ("Geometric Design of Linkages", Springer 2nd ed., 2011, doi 10.1007/978-1-4419-7892-9) is the canonical four-bar / loop-closure reference. Uicker2017 ("Theory of Machines and Mechanisms", OUP 5th ed., 2017) §1.9 "Grashof's Law" p.~33 (TOC entry verified, p.~33 in book / ~p.~13 of PDF) — supports the Grashof classification claim. #srcpdf("linkage_mechanisms/Books/McCarthy2011.pdf", label: "McCarthy2011 PDF") — #srcpdf("linkage_mechanisms/Books/Uicker2017.pdf", label: "Uicker2017 PDF")
- *V5* — *@McCarthy2011*, *@Uicker2017* `[2_2:40-42, eq:bg_loop_closure]` — OK (resolved 2026-05-02): co-cited Uicker2017 alongside McCarthy2011 to anchor the complex-exponential form $bold(Z)_1 e^(i theta) + bold(Z)_2 e^(i beta) = bold(Z)_3 e^(i phi) + bold(Z)_4$. Uicker/Sandor/Erdman is the canonical home of the complex-number loop-closure (Uicker2017 Ch.~2 "Position, Posture, and Displacement" / §2.10 "Complex-Number Methods"), while McCarthy2011 covers loop closure in vector/screw form. The equation as written is correct under either textbook's notation. #srcpdf("linkage_mechanisms/Books/McCarthy2011.pdf", label: "McCarthy2011 PDF") — #srcpdf("linkage_mechanisms/Books/Uicker2017.pdf", label: "Uicker2017 PDF")
- *V6* — *@Uicker2017*, *@Hartenberg1955* `[2_2:42]` — OK: Uicker2017 (transmission-angle classical treatment, §3 Mechanical Advantage / §4 Velocity Analysis). Hartenberg1955 (Hartenberg & Denavit, J. Appl. Mech. 22:215, 1955; the foundational kinematic-notation paper) — supports the transmission-angle / near-singular-configuration claim as a historical primary source. #srcpdf("linkage_mechanisms/Books/Uicker2017.pdf", label: "Uicker2017 PDF") — #srcpdf("linkage_mechanisms/Books/Hartenberg1955.pdf", label: "Hartenberg1955 PDF")
- *V7* — *@Dijksman1976MotionGeometry*, *@McCarthy2011* `[2_2:50]` — OK (re-verified 2026-05-11): replaces the previously cited `@Dijksman1977Antiparallelogram`, which could not be verified — DOI 10.1115/1.3439273 resolves to an unrelated tool-life paper, and the local `Dijksman1977.pdf` was actually the 1975 Newcastle conference paper "How to design four-bar function-cognates" (now in `_quarantine_wrong_pdfs/`). Replaced with E. A. Dijksman, *Motion Geometry of Mechanisms*, Cambridge UP, 1976 (ISBN 0-521-20841-6), the canonical mechanism-theory reference for the antiparallelogram topology. McCarthy2011 covers crossed four-bar variants in the four-bar taxonomy chapter. _Caveat:_ no legal PDF available; book-page reference (~p.~203) taken from secondary sources, not yet confirmed by direct reading — recommend FAU/USI ILL before submission. #srcpdf("linkage_mechanisms/Books/McCarthy2011.pdf", label: "McCarthy2011 PDF")
- *V8* — *@Dijksman1976MotionGeometry*, *@BryantSangwin2008HowRound* `[2_2:53]` — OK (re-verified 2026-05-11): the previous V8 entry attributed the semi-axes formula $beta$, $sqrt(beta^2 - alpha^2)$ to Stachel2000 with a "verbatim" quote that does **not** appear in that paper. Direct full-text search of the actual Stachel paper ("Higher-Order Flexibility for a Bipartite Planar Framework", 13 pages) returned 0 hits for `antiparallelogram`, `centrode`, `polode`, `semi-ax`, `tangent`, `focal`, and `Dijksman` — the previous V8 quote was fabricated. The semi-axes claim has been re-attributed to Bryant & Sangwin, *How Round Is Your Circle?*, Princeton UP, 2008, §3.3 pp.~54--56, which is the standard modern reference for this derivation (also cited by Wikipedia). The ellipse-centrode result itself stays attributed to Dijksman 1976. _Caveat:_ Bryant & Sangwin page reference taken from Wikipedia, not confirmed by direct reading. The wrong `Stachel2000.pdf` and `Dijksman1977.pdf` are preserved in `doc/Literatur/_quarantine_wrong_pdfs/`. The auxiliary verification PDF for Stachel 1982 "Eine Ortsaufgabe und der Satz von Ivory" (downloaded 2026-05-11, e-Periodica DOI 10.5169/seals-36394) is kept at `linkage_mechanisms/Papers/Stachel1982_Ortsaufgabe.pdf` for the audit trail; that paper is also unrelated to the antiparallelogram and is not cited.
- *V9* — *@FuretWenger2019* `[2_2:58]` — OK: Furet & Wenger 2019 (ASME J. Mechanisms & Robotics 11(6):060904) p.~1 title: "Kinetostatic Analysis and Actuation Strategy of a Planar Tensegrity 2-X Manipulator" — kinetostatic analysis explicitly addresses the variable-lever-arm / configuration-dependent transmission of the X-joint. #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Furet2019.pdf")
- *V10* — *@FuretWenger2019* `[2_2:61]` — OK: parallelogram/antiparallelogram bifurcation handling at collinear singularity is part of the kinetostatic analysis in Furet2019 (cable-routing prevents mode-switching by maintaining the crossed configuration). #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Furet2019.pdf")
- *V11* — *@Pott2018CDPR* `[2_2:71]` — OK: Pott2018 ("Cable-Driven Parallel Robots — Theory and Application", Springer Tracts in Advanced Robotics 120, 2018) — canonical CDPR textbook; Ch.~2 introduces the cables-only-tension constraint and platform-with-$m$-cables model. #srcpdf("tendon_robots/Books/Pott2018.pdf")
- *V12* — *@Pott2018CDPR*, *@Verhoeven2004TendonPlatforms* `[2_2:72]` — OK: Pott2018 Ch.~2 (cables-only-tension) and Verhoeven2004 (TU Duisburg PhD thesis "Analysis of the Workspace of Tendon-based Stewart Platforms") cover the tensile-only constraint. #srcpdf("tendon_robots/Books/Pott2018.pdf", label: "Pott2018 PDF") — #srcpdf("tendon_robots/Foundational_Works/Verhoeven2004.pdf", label: "Verhoeven2004 PDF")
- *V13* — *@Verhoeven2004TendonPlatforms*, *@Bruckmann2008StructureMatrix* `[2_2:75-79, eq:bg_structure_matrix]` — OK: equation $bold(w) = bold(A)^top bold(t)$ verbatim verified — Verhoeven2004 p.~10 nomenclature: *"$A^T$ structure matrix Eq.~(2.24), p.~26"* — defines the structure-matrix notation cited in the thesis. Bruckmann2008a p.~3 confirms the wire-robot/Stewart-Gough-platform formalism. #srcpdf("tendon_robots/Foundational_Works/Verhoeven2004.pdf", label: "Verhoeven2004 PDF") — #srcpdf("tendon_robots/Structure_Matrix_&_Force_Distribution/Bruckmann2008a.pdf", label: "Bruckmann2008 PDF")
- *V14* — *@Bruckmann2008StructureMatrix*, *@Pott2009ClosedFormForce*, *@Verhoeven2004TendonPlatforms*, *@GouttefardeGosselin2006*, *@Craig2005Robotics*, *@MurrayLiSastry1994* `[2_2:79]` — OK: structure-matrix-as-Jacobian-transpose / kineto-static-duality claim. Verhoeven attribution for "structure matrix" terminology (V13). Gouttefarde2006 uses equivalent "wrench matrix" (V15). Craig2005 Ch.~5 "Jacobians: velocities and static forces" (TOC verified, p.~135) and Murray1994 are the standard textbook references for the kineto-static duality. #srcpdf("tendon_robots/Structure_Matrix_&_Force_Distribution/Bruckmann2008a.pdf", label: "Bruckmann2008 PDF") — #srcpdf("tendon_robots/Structure_Matrix_&_Force_Distribution/Pott2009.pdf", label: "Pott2009 PDF") — #srcpdf("tendon_robots/Foundational_Works/Verhoeven2004.pdf", label: "Verhoeven2004 PDF") — #srcpdf("tendon_robots/Workspace_Analysis_(CDPM)/Gouttefarde2006.pdf", label: "Gouttefarde2006 PDF") — #srcpdf("control_kinematics/Books/Craig2005.pdf", label: "Craig2005 PDF") — #srcpdf("control_kinematics/Books/Murray1994.pdf", label: "Murray1994 PDF")
- *V15* — *@GouttefardeGosselin2006*, *@Bosscher2006WrenchFeasible*, *@Pott2009ClosedFormForce* `[2_2:86]` — OK: Gouttefarde2006 (IEEE TRO 22(3):434, June 2006) p.~1 title: "Analysis of the Wrench-Closure Workspace of Planar Parallel Cable-Driven Mechanisms" — direct definition of wrench-closure workspace + n+1-cable requirement. Bosscher2006 (IEEE TRO 22(5):890, Oct 2006) p.~1: "Wrench-Feasible Workspace Generation for Cable-Driven Robots" — exact match for wrench-feasible-workspace concept with bounded tensions. Pott2009 p.~1: "algorithm to determine feasible force distributions for parallel wire robots in closed form" — supports the closed-form $bold(t) = bold(t)_"particular" + bold(N) lambda$ decomposition. #srcpdf("tendon_robots/Workspace_Analysis_(CDPM)/Gouttefarde2006.pdf", label: "Gouttefarde2006 PDF") — #srcpdf("tendon_robots/Workspace_Analysis_(CDPM)/Bosscher2006.pdf", label: "Bosscher2006 PDF") — #srcpdf("tendon_robots/Structure_Matrix_&_Force_Distribution/Pott2009.pdf", label: "Pott2009 PDF")
- *V16* — *@MurrayLiSastry1994* `[2_2:102, transmission Jacobian eq]` — OK: Murray1994 ("A Mathematical Introduction to Robotic Manipulation", CRC, 1994) Ch.~3 "Manipulator Kinematics" + Ch.~4 "Robot Dynamics and Control" cover the differential-kinematics / transmission-Jacobian formalism $dot(bold(l)) = bold(R)(bold(q)) dot(bold(q))$. #srcpdf("control_kinematics/Books/Murray1994.pdf")
- *V17* — *@Craig2005Robotics*, *@MurrayLiSastry1994*, *@Tsai1999RobotAnalysis* `[2_2:105, eq:bg_jacobian_transpose]` — OK: equation $bold(tau) = bold(R)^top(bold(q)) bold(T)$ is the textbook-standard virtual-work derivation. Craig2005 Ch.~5 "Jacobians: velocities and static forces" p.~135 (TOC verified). Tsai1999 ("Robot Analysis: The Mechanics of Serial and Parallel Manipulators", Wiley, 1999) covers the same derivation. #srcpdf("control_kinematics/Books/Craig2005.pdf", label: "Craig2005 PDF") — #srcpdf("control_kinematics/Books/Murray1994.pdf", label: "Murray1994 PDF") — #srcpdf("control_kinematics/Books/Tsai1999.pdf", label: "Tsai1999 PDF")
- *V18* — *@Salisbury1982ArticulatedHands*, *@TsaiLee1989* `[2_2:108]` — OK: Salisbury1982 (Stanford-JPL hand) p.~5 confirms Jacobian-rank/singularity discussion: *"Singularities occur where the rank of the Jacobian matrix becomes less than full"*; the transpose-mapping passage is on p.~6 lines 13--17 (cf. V21). TsaiLee1989 generalisation to graph-theoretic tendon-driven mechanisms now available locally as scanned PDF (metadata-confirmed authorship; cf. V2). #srcpdf("control_kinematics/Journal_Articles/Salisbury1982.pdf", label: "Salisbury1982 PDF") — #srcpdf("tendon_robots/Foundational_Works/TsaiLee1989.pdf", label: "TsaiLee1989 PDF")
- *V19* — *@TsaiLee1989*, *@FuretWenger2019*, *@MurrayLiSastry1994* `[2_2:112]` — OK: configuration-dependent vs constant Jacobian — MurrayLi1994 covers the general $bold(R)(bold(q))$ formulation. Furet2019 confirms the X-joint produces a configuration-dependent transmission (V9). The TsaiLee1989 attribution for "circular pulleys yield constant $bold(R)$" is supported by the now-available scanned PDF (cf. V2). #srcpdf("tendon_robots/Foundational_Works/TsaiLee1989.pdf", label: "TsaiLee1989 PDF") — #srcpdf("control_kinematics/Books/Murray1994.pdf", label: "Murray1994 PDF") — #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Furet2019.pdf", label: "Furet2019 PDF")
- *V20* — *@Salisbury1982ArticulatedHands*, *@TsaiLee1989*, *@Kobayashi1998NullSpaceStiffness* `[2_2:117]` — OK: positive-tension constraint + n+1 rule (Salisbury1982 p.~5--6) and null-space co-contraction (Kobayashi1998 §4 — verified in V2). #srcpdf("control_kinematics/Journal_Articles/Salisbury1982.pdf", label: "Salisbury1982 PDF") — #srcpdf("control_kinematics/Journal_Articles/Kobayashi1998.pdf", label: "Kobayashi1998 PDF")
- *V21* — *@ShahTensegrityRobotics2022* `[2_2:130]` — OK (Sultan2009 / Skelton2009 substituted 2026-04-24): the tensegrity definition + class-$k$ taxonomy + Snelson--Fuller history is now cited via Shah2022 instead of Sultan2009 / SkeltonDeOliveira2009 (those PDFs are paywalled; Shah2022 covers all the same canonical claims). Shah2022 p.~2 verbatim: *"class 1 tensegrities such as the six-bar icosahedron ... have only one rigid body contacting each node"*; "Class 4 'tbar' tensegrities (resembling the kites built by Snelson, but pinned at the two struts' intersection)". #srcpdf("tensegrity_robots/Review_Articles/Shah2022.pdf", label: "Shah2022 PDF")
- *V22* — *@Bicchi2004FastSoftArm*, *@Walter2023Tensegrity* `[2_2:134]` — OK: Bicchi2004 p.~1: *"A robot arm that is to interact with humans has a single design consideration at a premium--safety"* (passive-compliance-for-safety claim, faster than control). Walter2023 (IFToMM proceedings, paper title "Tensegrity-Inspired Joint Can Protect from Impacts by Isolating", begins PDF p.~348 / chapter p.~344) p.~354 / chapter p.~350 conclusion: *"isolates impact forces up to 83 %"*. #srcpdf("control_kinematics/Journal_Articles/Bicchi2004.pdf", label: "Bicchi2004 PDF") — #srcpdf("tendon_robots/Conference_Papers/Walter2023.pdf", label: "Walter2023 PDF")
- *V23* — *@ShahTensegrityRobotics2022* `[2_2:135]` — OK (SkeltonDeOliveira2009 substituted 2026-04-24): high strength-to-weight / axial-only-loading claim now cited via Shah2022 (no local Skelton PDF available). Shah2022 p.~3 verbatim supports the axial-loading framing: *"each member in a tensegrity primarily only experiences tension or compression"*. #srcpdf("tensegrity_robots/Review_Articles/Shah2022.pdf", label: "Shah2022 PDF")
- *V24* — *@MuralidharanWenger2021*, *@Kobayashi1998NullSpaceStiffness* `[2_2:136]` — OK: cable-pretension stiffness modulation — Muralidharan2021 p.~1 and Kobayashi1998 §4 (V2). #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Muralidharan2021.pdf", label: "Muralidharan2021 PDF") — #srcpdf("control_kinematics/Journal_Articles/Kobayashi1998.pdf", label: "Kobayashi1998 PDF")
- *V25* — *@FuretWenger2019*, *@Fasquelle2020BioInspired3DOF* `[2_2:137]` — OK: remote-actuation / minimal-distal-mass claim. Furet2019 (V9). Fasquelle2020 p.~1 title+abstract: "bio-inspired 3-DOF light-weight manipulator with tensegrity X-joints ... safe interactions" — direct match. #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Furet2019.pdf", label: "Furet2019 PDF") — #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Fasquelle2020.pdf", label: "Fasquelle2020 PDF")
- *V26* — *@ShahTensegrityRobotics2022* `[2_2:145]` — OK: Shah2022 (Soft Robotics, 2022) abstract p.~1 verbatim: *"Tensegrity robots contain compliant networks of rigid struts and soft cables, allowing them to change their shape by adjusting their internal tension"* — direct match for rigid--soft bridge claim and locomotion-spectrum framing. #srcpdf("tensegrity_robots/Review_Articles/Shah2022.pdf")
- *V27* — *@Lessard2016TensegrityManipulator*, *@Fasquelle2020BioInspired3DOF* `[2_2:147]` — OK: Lessard2016 p.~1 title: "A Bio-Inspired Tensegrity Manipulator with Multi-DOF, Structurally Compliant Joints" — direct match. Fasquelle2020 (V25) introduces the 3-DoF X-joint manipulator with axial-only-loaded bars. #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Lessard2016.pdf", label: "Lessard2016 PDF") — #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Fasquelle2020.pdf", label: "Fasquelle2020 PDF")
- *V28* — *@Klein2023*, *@Walter2023Tensegrity* `[2_2:151-152]` — OK: Klein2023 p.~1 verbatim: *"Arbeitsraumanalyse, Simulation und Bewegungsplanung eines seilgetriebenen robotischen Manipulators ... Friedrich-Alexander-Universität Erlangen-Nürnberg, Lehrstuhl für Fertigungsautomatisierung"* — confirms FAPS-internal Masterarbeit attribution. Walter2023 conclusion p.~354/chapter-p.~350 verbatim: *"isolates impact forces up to 83 %"* (cf. V22); the experimental setup (modal hammer applied vertically to joint body, base connected to ground) is described p.~350/chapter-p.~346. #srcpdf("tendon_robots/Theses/Klein2023.pdf", label: "Klein2023 PDF") — #srcpdf("tendon_robots/Conference_Papers/Walter2023.pdf", label: "Walter2023 PDF")
- *V29* — *@Bicchi2004FastSoftArm*, *@Pratt1995SEA* `[2_2:156-157]` — OK: Bicchi2004 (V22). Pratt1995 ("Series Elastic Actuators", MIT AI Lab) p.~1 abstract: *"It is traditional to make the interface between an actuator and its load as stiff as possible ... reducing interface stiffness offers a number of advantages, including greater shock tolerance, lower reflected inertia, more accurate and stable force control ... As a trade-off, reducing interface stiffness also lowers zero motion force bandwidth"* — direct support for SEA bandwidth/shock-tolerance trade-off. #srcpdf("control_kinematics/Journal_Articles/Bicchi2004.pdf", label: "Bicchi2004 PDF") — #srcpdf("tensegrity_robots/Journal_Articles/Pratt1995.pdf", label: "Pratt1995 PDF")

== §2.3 Workspace Analysis

// Last verified: 2026-04-22 (line-by-line pass, see VERIFICATION_PROMPT_TEMPLATE.md).
// Line numbers refer to chapters/background/2_3_WorkspaceAnalysis.typ.

- *V1* — *@Rastegar1990WorkspaceMonteCarlo*, *@Dong2013WorkspaceDensity* `[2_3:10]` — OK: framing claim that workspace analysis verifies reachability and exposes singular/poor-quality regions. Rastegar1990 (MMT 25(2):233--239) p.~1 §1 "Introduction": "The workspace of manipulators has been studied using analytical and numerical techniques ... extreme reach ... boundary surfaces have been investigated"; Dong2013 (MMT 70:508--522) p.~1 abstract: "reachable workspaces of robotic manipulators ... sampling joint angles and evaluating the boundary of the resulting set in the space of rigid-body motions". #srcpdf("workspace_analysis/Journal_Articles/Rastegar1990.pdf", label: "Rastegar1990 PDF") — #srcpdf("workspace_analysis/Journal_Articles/Dong2013.pdf", label: "Dong2013 PDF")
- *V2* — *@Rastegar1990WorkspaceMonteCarlo* `[2_3:18]` — OK: Monte Carlo motivation. p.~1 abstract verbatim: "The Monte Carlo method is shown to be very simple, and readily implemented"; p.~1 §1: "probabilistic methods have not been applied to the problems of analysis and synthesis of manipulators" — supports the "no explicit boundary derivation" rationale. #srcpdf("workspace_analysis/Journal_Articles/Rastegar1990.pdf")
- *V3* — *@mathworks_generaterobotworkspace* `[2_3:22]` — OK (resolved 2026-05-02): MathWorks Robotics System Toolbox reference page `generateRobotWorkspace` (R2026a release; URL `/help/robotics/ref/generaterobotworkspace.html`) documents an API that returns reachable workspace point sets paired with joint configurations — directly matches the cited workflow. Local HTML snapshot now archived at `workspace_analysis/Web_Resources/mathworks_generaterobotworkspace.html`. #srcpdf("workspace_analysis/Web_Resources/mathworks_generaterobotworkspace.html", label: "MathWorks generateRobotWorkspace snapshot")
- *V4* — *@Dong2013WorkspaceDensity* `[2_3:24]` — OK: voxel discretisation + density-based indicators. Dong2013 p.~4 verbatim: "We divide the workspace, W, into small boxes (voxels) of equal size $Delta x = 0.15$, $Delta y = 0.15$, $Delta theta = pi/4$. The workspace density $rho$ assigns each box of the workspace W the number of points within the box that are reachable, normalized so as to be a probability density." #srcpdf("workspace_analysis/Journal_Articles/Dong2013.pdf")
- *V5* — *@Yoshikawa1985Manipulability* `[2_3:33, eq:yoshikawa_manipulability]` — OK: equation $w = sqrt(det(J J^top))$ matches the measure introduced in Yoshikawa1985 (IJRR 4(2):3--9). p.~2 verbatim: "$w$ is equal to the volume of the manipula-bility ellipsoid except for the constant coefficient $d$"; p.~1 (singular state passage): "the manipulator is in a singular state. This state $theta^*$ is not desirable because the manipulation vector $r$ cannot move in a certain direction" — supports the "becomes zero at kinematic singularities" claim. #srcpdf("workspace_analysis/Journal_Articles/Yoshikawa1985.pdf")
- *V6* — *@Salisbury1982ArticulatedHands* `[2_3:36-41, eq:inv_condition_number]` — OK: condition-number-as-isotropy index. Salisbury & Craig 1982 (IJRR 1(1):4--17) p.~6 ll.~18--33 verbatim: "the relative error is bounded by the product of the condition number of the Jacobian transpose matrix and the relative error in joint torque ... Points in the workspace that minimize the condition number of the Jacobian matrix are the best conditioned to minimize error propagation." The inverse condition number $kappa_"inv" = sigma_min / sigma_max in [0,1]$ is the standard reciprocal of $"cond"(J) = sigma_max / sigma_min$ (textbook identity, no symbol-level mismatch with the source). The "Salisbury and Craig introduced" attribution is consistent with Yoshikawa1985 p.~6 acknowledging "Craig (1982) have used the condition number ... as a measure of workspace quality". #srcpdf("control_kinematics/Journal_Articles/Salisbury1982.pdf")
- *V7* — *@Dong2013WorkspaceDensity* `[2_3:44]` — OK: reachability-density definition. Dong2013 p.~4 (cf.~V4) defines density per voxel as the count of reachable points normalised to a probability density — direct match for the thesis's "joint-space volume that maps into the voxel region" framing. #srcpdf("workspace_analysis/Journal_Articles/Dong2013.pdf")
- *V8* — *@Yoshikawa1985Manipulability*, *@Salisbury1982ArticulatedHands*, *@Dong2013WorkspaceDensity* `[2_3:48]` — OK: implications-for-RL paragraph reuses V5/V6/V7 evidence (manipulability volume + condition number + reachability density) to motivate task-space placement; no new quantitative claim is added beyond what those three sources establish. #srcpdf("workspace_analysis/Journal_Articles/Yoshikawa1985.pdf", label: "Yoshikawa1985 PDF") — #srcpdf("control_kinematics/Journal_Articles/Salisbury1982.pdf", label: "Salisbury1982 PDF") — #srcpdf("workspace_analysis/Journal_Articles/Dong2013.pdf", label: "Dong2013 PDF")
- *V9* — *@Miyasaka2020HysteresisFriction*, *@Bicchi2004FastSoftArm* `[2_3:50]` — OK: tendon/tensegrity-compliance-amplifies-Cartesian-error claim. Miyasaka2020 (T-Mech 25(2):1095, 2020) hysteresis/cable-friction modelling — already verified in §2.2 V3. Bicchi2004 (passive-compliance / contact-force argument) — already verified in §2.2 V22; the implication that compliance can amplify positional uncertainty into contact forces follows from the same modelling stance. #srcpdf("tendon_robots/Journal_Articles/Miyasaka2020.pdf", label: "Miyasaka2020 PDF") — #srcpdf("control_kinematics/Journal_Articles/Bicchi2004.pdf", label: "Bicchi2004 PDF")

== §2.4 Physics Simulation

// Last verified: 2026-04-22 (line-by-line pass, see VERIFICATION_PROMPT_TEMPLATE.md).
// Line numbers refer to chapters/background/2_4_PhysicsSimulation.typ.

- *V1* — *@openusd_usdphysics_schema*, *@omni_physx_overview* `[2_4:9]` — OK: USD-physics-schema layering claim. `openusd_usdphysics_schema.html` (local snapshot under `simulation/Documentation/`) page title verbatim: "UsdPhysics: USD Physics Schema — OpenUSD Documentation". `omni_physx_overview.html` body: "The omni.physx extension provides a connection between USD physics content and the NVIDIA PhysX simulation engine. Physics content in USD is defined through two USD schemas: UsdPhysics ... and PhysXS[chema]". #srcpdf("simulation/Documentation/openusd_usdphysics_schema.html", label: "openusd_usdphysics_schema") — #srcpdf("simulation/Documentation_(Online)/omni_physx_overview.html", label: "omni_physx_overview")
- *V2* — *@omni_physx_overview*, *@isaac_sim_510_physics_fundamentals*, *@physx_welcome_513*, *@physx_541_gpu_rigid_bodies* `[2_4:11]` — OK: omni.physx parses USD + PhysX 5 backend + GPU pipeline claim. `omni_physx_overview.html` documents the USD↔PhysX connection (cf. V1). `physx_541_gpu_rigid_bodies.html` body verbatim: "PhysX simulation can be configured to take advantage of CUDA capable GPUs under Linux or Windows. ... It supports the entire rigid body feature-set including articulation[s]". `isaac_sim_510_physics_fundamentals.html` and `physx_welcome_513.html` confirm Isaac Sim 5.1 / PhysX 5 stack. #srcpdf("simulation/Documentation_(Online)/omni_physx_overview.html", label: "omni_physx_overview") — #srcpdf("simulation/Documentation_(Online)/isaac_sim_510_physics_fundamentals.html", label: "isaac_sim_510_physics_fundamentals") — #srcpdf("simulation/Documentation_(Online)/physx_welcome_513.html", label: "physx_welcome_513") — #srcpdf("simulation/Documentation_(Online)/physx_541_gpu_rigid_bodies.html", label: "physx_541_gpu_rigid_bodies")
- *V3* — *@Jakobi1995RealityGap*, *@Salvato2021RealityGapSurvey* `[2_4:13]` — OK: reality-gap framing. Jakobi1995 (SAB 1995, Sussex) p.~1 title verbatim: "Noise and The Reality Gap: The Use of Simulation in Evolutionary Robotics" (PDF text-layer is letter-spaced; title established from filename + p.~1 header); p.~3 body: "system robust enough to cope with such an envelope-of-noise may handle the transfer from simulation to reality better". Salvato2021 (IEEE Access, DOI 10.1109/ACCESS.2021.3126658) p.~1 title verbatim: "Crossing the Reality Gap: A Survey on Sim-to-Real Transferability of Robot Controllers in Reinforcement Learning". #srcpdf("sim_to_real/Conference_&_Journal_Papers/Jakobi1995.pdf", label: "Jakobi1995 PDF") — #srcpdf("sim_to_real/Conference_&_Journal_Papers/Salvato2021.pdf", label: "Salvato2021 PDF")
- *V4* — *@Salvato2021RealityGapSurvey*, *@Peng2018DynamicsRandomization* `[2_4:13]` — OK: simulator-as-data-generator + transition-distribution claim. Salvato2021 abstract (cf. V3) frames the survey around RL controllers crossing the reality gap. Peng2018 p.~4 §IV.C verbatim: "Dynamics Randomization. During training, rollouts are organized into episodes ... a random set of dynamics parameters $mu$ are sampled according to $rho_mu$ and held fixed for the duration of the episode" — directly supports the modelling-shapes-the-transition-distribution claim. #srcpdf("sim_to_real/Conference_&_Journal_Papers/Salvato2021.pdf", label: "Salvato2021 PDF") — #srcpdf("sim_to_real/Conference_Papers_&_Preprints/Peng2018.pdf", label: "Peng2018 PDF")
- *V5* — *@Peng2018DynamicsRandomization*, *@physx_best_practices_541* `[2_4:13]` — OK: solver/timestep/contact choices as part of the learning-system design. Peng2018 p.~7 conclusion: "Training policies with randomized dynamics in simulation enables the resulting policies to be deployed directly on a physical robot despite poor calibrations". `physx_best_practices_541.html` documents stiffness/timestep/contact-tuning recommendations directly. #srcpdf("sim_to_real/Conference_Papers_&_Preprints/Peng2018.pdf", label: "Peng2018 PDF") — #srcpdf("simulation/Documentation_(Online)/physx_best_practices_541.html", label: "physx_best_practices_541")
- *V6* — *@physx_welcome_513*, *@physx_rigid_body_dynamics_511* `[2_4:23]` — OK: rigid-body actors/shapes/materials description. `physx_welcome_513.html` is the PhysX 5.1.3 docs entry-point covering the whole rigid-body feature-set. `physx_rigid_body_dynamics_511.html` body lists "Actors Kinematic Surface Velocities Active Actors Dominance Solver Iterations ... Joints Articulations GPU Rigid Bodies" — directly matches the static/kinematic/dynamic-actor framing. #srcpdf("simulation/Documentation_(Online)/physx_welcome_513.html", label: "physx_welcome_513") — #srcpdf("simulation/Documentation_(Online)/physx_rigid_body_dynamics_511.html", label: "physx_rigid_body_dynamics_511")
- *V7* — *@physx_articulations_513* `[2_4:26]` — OK: reduced-coordinates articulation claim. `physx_articulations_513.html` TOC verbatim: "Reduced-Coordinates and Comparison to Rigid Bodies" — direct match for the cited reduced-coordinates formulation and the mass-ratio / long-chain stability rationale. #srcpdf("simulation/Documentation_(Online)/physx_articulations_513.html", label: "physx_articulations_513")
- *V8* — *@physx_articulations_513*, *@omni_physics_tendon_authoring* `[2_4:29]` — OK: fixed/spatial articulation tendons. `physx_articulations_513.html` TOC: "Articulation Tendons / Fixed Tendons / Spatial Tendons". `omni_physics_tendon_authoring.html` verbatim: "Creating a Fixed Tendon ... the tendon cannot link arbitrary joints in the articulation, but must follow the articulat[ion structure]" and "Spatial tendons are created by adding attachments to articulation links". #srcpdf("simulation/Documentation_(Online)/physx_articulations_513.html", label: "physx_articulations_513") — #srcpdf("simulation/Documentation_(Online)/omni_physics_tendon_authoring.html", label: "omni_physics_tendon_authoring")
- *V9* — *@physx_rigid_body_collision_510* `[2_4:35]` — OK: contact-as-constrained-dynamics + interpenetration prevention. `physx_rigid_body_collision_510.html` is the PhysX 5.1.0 rigid-body-collision docs page covering contact generation, restitution, friction. #srcpdf("simulation/Documentation_(Online)/physx_rigid_body_collision_510.html", label: "physx_rigid_body_collision_510")
- *V10* — *@physx_rigid_body_dynamics_511*, *@physx_material_api_510* `[2_4:35]` — OK: friction/restitution via materials with static + dynamic coefficients. `physx_material_api_510.html` is the PhysX material API page (static/dynamic friction + restitution). #srcpdf("simulation/Documentation_(Online)/physx_rigid_body_dynamics_511.html", label: "physx_rigid_body_dynamics_511") — #srcpdf("simulation/Documentation_(Online)/physx_material_api_510.html", label: "physx_material_api_510")
- *V11* — *@Salvato2021RealityGapSurvey*, *@Peng2018DynamicsRandomization* `[2_4:35]` — OK: contact-rich-grasping + sim-to-real-robustness coupling — Salvato2021 survey (cf. V3) and Peng2018 dynamics-randomisation (cf. V4) jointly support this; no new quantitative claim. #srcpdf("sim_to_real/Conference_&_Journal_Papers/Salvato2021.pdf", label: "Salvato2021 PDF") — #srcpdf("sim_to_real/Conference_Papers_&_Preprints/Peng2018.pdf", label: "Peng2018 PDF")
- *V12* — *@physx_rigid_body_dynamics_511* `[2_4:38]` — OK: PGS vs TGS solver claim. `physx_rigid_body_dynamics_511.html` body verbatim: "PhysX 5.1 the new default solver is the Temporal Gauss-Seidel (TGS) solver. As an alternative and for compatibility the previously-default Projected Gauss-Seidel-style (PGS) solver is still available. Temporal gauss-seidel offers several advantages over the PGS-style solver: Dramatically improved convergence". #srcpdf("simulation/Documentation_(Online)/physx_rigid_body_dynamics_511.html", label: "physx_rigid_body_dynamics_511")
- *V13* — *@Macklin2019SmallSteps*, *@physx_best_practices_541* `[2_4:38]` — OK: smaller substeps > more iterations for stiff systems. Macklin2019 (NVIDIA) p.~1 verbatim: "performing a single large time step with $n$ constraint solver iterations is less effective than computing $n$ smaller time steps, each with a single constraint solver iteration"; "split every visual time step into $n$ substeps of length $Delta t/n$ and ... perform a single iteration of extended position-based dynamics (XPBD)". #srcpdf("simulation/Conference_Papers/Macklin2019SmallSteps.pdf", label: "Macklin2019 PDF") — #srcpdf("simulation/Documentation_(Online)/physx_best_practices_541.html", label: "physx_best_practices_541")
- *V14* — *@physx_simulation_541* `[2_4:51]` — OK (table row "Time step $h$"): `physx_simulation_541.html` documents the simulation-stepping API and time-step trade-offs. #srcpdf("simulation/Documentation_(Online)/physx_simulation_541.html", label: "physx_simulation_541")
- *V15* — *@physx_rigid_body_dynamics_511* `[2_4:52]` — OK (table row "Solver iterations"): cf. V12; PhysX 5.1.1 rigid-body docs document position/velocity solver-iteration counts. #srcpdf("simulation/Documentation_(Online)/physx_rigid_body_dynamics_511.html", label: "physx_rigid_body_dynamics_511")
- *V16* — *@physx_advanced_collision_detection_512* `[2_4:53]` — OK (table row "contactOffset/restOffset"): `physx_advanced_collision_detection_512.html` is the canonical PhysX 5.1.2 advanced-collision-detection docs page covering the contact/rest-offset parameters. #srcpdf("simulation/Documentation_(Online)/physx_advanced_collision_detection_512.html", label: "physx_advanced_collision_detection_512")
- *V17* — *@physx_material_api_510* `[2_4:54]` — OK (table row "Friction coefficients"): cf. V10. #srcpdf("simulation/Documentation_(Online)/physx_material_api_510.html", label: "physx_material_api_510")
- *V18* — *@physx_simulation_541*, *@physx_best_practices_541* `[2_4:61]` — OK: time-step accuracy/stability discussion. `physx_simulation_541.html` (timestep + substepping) and `physx_best_practices_541.html` (best-practice recommendations on timestep selection) jointly support the claim. #srcpdf("simulation/Documentation_(Online)/physx_simulation_541.html", label: "physx_simulation_541") — #srcpdf("simulation/Documentation_(Online)/physx_best_practices_541.html", label: "physx_best_practices_541")
- *V19* — *@physx_rigid_body_collision_510*, *@physx_geometry_541* `[2_4:63]` — OK: collider-cost ranking (primitives < convex meshes). `physx_geometry_541.html` is the PhysX 5.4.1 geometry/shape docs page that documents primitive vs convex/triangle-mesh trade-offs; `physx_rigid_body_collision_510.html` covers shape-attached collision. #srcpdf("simulation/Documentation_(Online)/physx_rigid_body_collision_510.html", label: "physx_rigid_body_collision_510") — #srcpdf("simulation/Documentation_(Online)/physx_geometry_541.html", label: "physx_geometry_541")
- *V20* — *@physx_541_gpu_rigid_bodies*, *@Makoviychuk2021IsaacGym* `[2_4:67]` — OK: GPU pipeline + order-of-magnitude throughput claim. `physx_541_gpu_rigid_bodies.html` body verbatim: "PhysX simulation can be configured to take advantage of CUDA capable GPUs ... a performance benefit proportional to the arithmetic complexity of a scene". Makoviychuk2021 (Isaac Gym, NeurIPS Datasets/Benchmarks 2021) p.~1 abstract verbatim: "communicate by directly passing data from physics buffers to PyTorch tensors without ever going through CPU bottlenecks. This leads to blazing fast training times for complex robotics tasks on a single GPU with 2-3 orders of magnitude improvements compared to conventional RL training". #srcpdf("simulation/Documentation_(Online)/physx_541_gpu_rigid_bodies.html", label: "physx_541_gpu_rigid_bodies") — #srcpdf("simulation/Journal_Articles_&_Preprints/Makoviychuk2021.pdf", label: "Makoviychuk2021 PDF")

== §2.5 NVIDIA Isaac Sim and IsaacLab

// Last verified: 2026-04-22 (line-by-line pass, see VERIFICATION_PROMPT_TEMPLATE.md).
// Line numbers refer to chapters/background/2_5_IsaacSimLab.typ.

- *V1* — *@nvidia_isaac_sim_510_what_is*, *@Mittal2025IsaacLab* `[2_5:9]` — OK: integrated-Omniverse-stack + GPU-parallel-MDP-training framing. `isaac_sim_510_overview.html` body verbatim: "Isaac Sim is the simulation itself: a high-fidelity GPU-based PhysX engine, capable of supporting multi-sensor RTX rendering at an industrial scale". Mittal2025 p.~1 abstract verbatim: "We present Isaac Lab, the natural successor to Isaac Gym, which extends the paradigm of GPU-native robotics simulation into the era of large-scale multi-modal learning". #srcpdf("simulation/Documentation_(Online)/isaac_sim_510_overview.html", label: "isaac_sim_510_overview") — #srcpdf("simulation/Journal_Articles_&_Preprints/Mittal2025IsaacLab.pdf", label: "Mittal2025 PDF")
- *V2* — *@nvidia_isaac_sim_510_what_is* `[2_5:13]` — OK: USD-as-scene-representation + Omniverse-Kit-extension architecture. `isaac_sim_510_overview.html` is the canonical "What Is Isaac Sim?" v5.1.0 page that documents Isaac Sim as an Omniverse reference application with USD-based assets and Kit extensions (cf. V1 quote on the GPU-PhysX/RTX stack). #srcpdf("simulation/Documentation_(Online)/isaac_sim_510_overview.html", label: "isaac_sim_510_overview")
- *V3* — *@nvidia_isaac_sim_510_what_is*, *@physx_gpu_rigid_bodies_510* `[2_5:22]` — OK (resolved 2026-05-02): PhysX~5 GPU-accelerated rigid-body and articulation backend. PhysX 5.1.0 page (`physx_510_gpu_rigid_bodies.html`, version-matched to bib URL, snapshotted 2026-05-02): "GPU Rigid Bodies — physx 5.1.0 documentation" — covers GPU-accelerated rigid-body feature-set including articulations. `isaac_sim_510_overview.html` confirms "high-fidelity GPU-based PhysX engine" (cf. V1). The 5.4.1 snapshot is retained for §2.4 cross-references. #srcpdf("simulation/Documentation_(Online)/isaac_sim_510_overview.html", label: "isaac_sim_510_overview") — #srcpdf("simulation/Documentation_(Online)/physx_510_gpu_rigid_bodies.html", label: "physx_5.1.0_gpu_rigid_bodies")
- *V4* — *@nvidia_isaac_sim_510_extensions_api* `[2_5:23]` — OK (resolved 2026-05-02): the Isaac Sim 5.1.0 Python Extensions API root page is now snapshotted locally at `isaac_sim_510_extensions_api.html` (page title verbatim "Isaac Sim: Extensions API"; the snapshot contains 410+ references to extensions including `isaacsim.core.cloner` for environment cloning). The cloner-tutorial snapshot (`isaacsim_cloner_tutorial.html`) is retained as supplementary evidence. #srcpdf("simulation/Documentation_(Online)/isaac_sim_510_extensions_api.html", label: "isaac_sim_510_extensions_api snapshot") — #srcpdf("simulation/Documentation_(Online)/isaacsim_cloner_tutorial.html", label: "isaacsim_cloner_tutorial")
- *V5* — *@nvidia_isaac_sim_510_what_is* `[2_5:24]` — OK: USD-centric asset pipeline + scalable instancing. Same "What Is Isaac Sim?" page as V1/V2; documents USD assets (Nova Carter, SimReady USD assets) as the scene representation. #srcpdf("simulation/Documentation_(Online)/isaac_sim_510_overview.html", label: "isaac_sim_510_overview")
- *V6* — *@Mittal2025IsaacLab*, *@Makoviychuk2021IsaacGym*, *@Mittal2023Orbit* `[2_5:28]` — OK: Isaac Gym → Orbit → IsaacLab lineage. Mittal2025 p.~1 abstract verbatim "natural successor to Isaac Gym" (cf. V1). Makoviychuk2021 p.~1 title verbatim: "Isaac Gym: High Performance GPU Based Physics Simulation For Robot Learning". Mittal2023 p.~1 abstract verbatim: "We present ORBIT, a unified and modular framework for robot learning powered by NVIDIA Isaac Sim". #srcpdf("simulation/Journal_Articles_&_Preprints/Mittal2025IsaacLab.pdf", label: "Mittal2025 PDF") — #srcpdf("simulation/Journal_Articles_&_Preprints/Makoviychuk2021.pdf", label: "Makoviychuk2021 PDF") — #srcpdf("simulation/Journal_Articles_&_Preprints/Mittal2023Orbit.pdf", label: "Mittal2023 PDF")
- *V7* — *@isaaclab_manager_based_rl_env* `[2_5:31]` — OK: manager-based architecture with reusable action/observation/event managers extended by reward/termination/command/curriculum components. `isaaclab_manager_based_rl_env.html` verbatim: "build a reinforcement learning task environment by extending Isaac Lab's base environment with task-specific components"; "leverages the ManagerBasedRLEnv class, which extends the base environment with RL-specific functionality. Rather than modifying the core class directly, users implement a configuration object (ManagerBasedRLEnvCfg)". #srcpdf("simulation/Documentation_(Online)/isaaclab_manager_based_rl_env.html", label: "isaaclab_manager_based_rl_env")
- *V8* — *@isaaclab_manager_based_rl_env* `[2_5:33]` — OK: `ManagerBasedRLEnv` returns MDP-relevant signals and is compatible with `gymnasium.make`. Same snapshot as V7 documents the `ManagerBasedRLEnv` class (verbatim quote in V7); compatibility with the Gymnasium interface is the standard Isaac Lab env-creation pattern documented across the manager-based env tutorial chain. #srcpdf("simulation/Documentation_(Online)/isaaclab_manager_based_rl_env.html", label: "isaaclab_manager_based_rl_env")
- *V9* — *@Makoviychuk2021IsaacGym*, *@Mittal2025IsaacLab*, *@isaaclab_multi_gpu_multinode* `[2_5:36]` — OK: GPU-resident pipeline + order-of-magnitude throughput + IsaacLab multi-GPU/multi-node extension. Makoviychuk2021 p.~1 abstract verbatim: "communicate by directly passing data from physics buffers to PyTorch tensors without ever going through CPU bottlenecks. This leads to blazing fast training times for complex robotics tasks on a single GPU with 2-3 orders of magnitude improvements compared to conventional RL training". Mittal2025 p.~2 verbatim: "these capabilities scale efficiently across multi-GPU and multi-node setups". `isaaclab_multi_gpu_doc.html` body verbatim: "Isaac Lab supports multi-GPU and multi-node reinforcement learning. Currently, this feature is only available for RL-Games, RSL-RL and skrl libraries workflows". #srcpdf("simulation/Journal_Articles_&_Preprints/Makoviychuk2021.pdf", label: "Makoviychuk2021 PDF") — #srcpdf("simulation/Journal_Articles_&_Preprints/Mittal2025IsaacLab.pdf", label: "Mittal2025 PDF") — #srcpdf("simulation/Documentation_(Online)/isaaclab_multi_gpu_doc.html", label: "isaaclab_multi_gpu_doc")
- *V10* — *@nvidia_isaac_sim_510_what_is*, *@Mittal2025IsaacLab* `[2_5:47]` — OK (table row "Isaac Sim + IsaacLab — Integrated Omniverse stack: PhysX, RTX, RL tooling"): supported by the same evidence as V1 ("high-fidelity GPU-based PhysX engine ... multi-sensor RTX rendering" + Mittal2025 abstract on the manager-based composable architecture). #srcpdf("simulation/Documentation_(Online)/isaac_sim_510_overview.html", label: "isaac_sim_510_overview") — #srcpdf("simulation/Journal_Articles_&_Preprints/Mittal2025IsaacLab.pdf", label: "Mittal2025 PDF")
- *V11* — *@Todorov2012MuJoCo* `[2_5:48]` — OK (table row "MuJoCo — Efficient dynamics for model-based control"): Todorov2012 p.~1 verbatim title "MuJoCo: A physics engine for model-based control" and abstract "We describe a new physics engine tailored to model-based control. Multi-joint dynamics are represented in generalized coordinates and computed via recursive algorithms". #srcpdf("simulation/Conference_Papers/Todorov2012.pdf", label: "Todorov2012 PDF")
- *V12* — *@pybullet_homepage* `[2_5:49]` — OK (table row "PyBullet/Bullet — Accessible real-time physics"): local snapshot `pybullet_org.html` is the canonical Bullet/PyBullet project homepage entry as cited in `literature.bib` (URL `https://pybullet.org/wordpress/`). #srcpdf("simulation/Web_Resources/pybullet_org.html", label: "pybullet_org snapshot")
- *V13* — *@Todorov2012MuJoCo*, *@pybullet_homepage*, *@nvidia_isaac_sim_510_what_is*, *@Mittal2025IsaacLab* `[2_5:55]` — OK: closing-paragraph qualitative comparison reuses V11/V12/V1/V10 evidence (MuJoCo as efficient per-step continuous-control engine; PyBullet as Python-accessible prototyping; Isaac Sim+IsaacLab as integrated USD/PhysX/MDP-training stack). No new quantitative claim. #srcpdf("simulation/Conference_Papers/Todorov2012.pdf", label: "Todorov2012 PDF") — #srcpdf("simulation/Web_Resources/pybullet_org.html", label: "pybullet_org snapshot") — #srcpdf("simulation/Documentation_(Online)/isaac_sim_510_overview.html", label: "isaac_sim_510_overview") — #srcpdf("simulation/Journal_Articles_&_Preprints/Mittal2025IsaacLab.pdf", label: "Mittal2025 PDF")

== §2.6 Robot and Scene Description Formats

// Last verified: 2026-04-22 (line-by-line pass, see VERIFICATION_PROMPT_TEMPLATE.md).
// Line numbers refer to chapters/background/2_6_DescriptionFormats.typ.

- *V1* — *@openusd_usd_faq* `[2_6:13]` — OK (resolved 2026-05-02): prose rewritten to put composition first and interchange second, matching the FAQ §"Isn't USD just another file format?" framing verbatim: "While USD does provide interchange services (more below), its primary function is to compose together scene description spread across many files (or other data sources) in many different formats ... to present a single hierarchical scenegraph view of the data." Thesis now reads: _"USD is a system for composing scalable, hierarchically organised scene description from many layers and assets, and additionally provides interchange services across digital content creation applications."_ #srcpdf("simulation/Documentation/openusd_usd_faq.html", label: "openusd_usd_faq")
- *V2* — *@openusd_usd_faq* `[2_6:13]` — OK: composition / sparse-overrides / references / variants. FAQ §"What is USD?" verbatim: "aggregate multiple assets into a single scenegraph while still allowing for sparse overrides"; §"non-destructive": "shared between instances and scenes, and retain its integrity thanks to USD's many non-destructive editing features". #srcpdf("simulation/Documentation/openusd_usd_faq.html", label: "openusd_usd_faq")
- *V3* — *@openusd_usdphysics_schema* `[2_6:15]` — OK: UsdPhysics schemas for rigid bodies, joints, articulations. Local snapshot verbatim: "Joint types: Fixed, Revolute, Prismatic, Spherical, Distance, and D6 (generic). Articulations: Support reduced-coordinate systems"; "extends Universal Scene Description to represent real-time physics data, enabling rigid body simulations". #srcpdf("simulation/Documentation/openusd_usdphysics_schema.html", label: "openusd_usdphysics_schema")
- *V4* — *@omni_physics_physx_joint_schema* `[2_6:15]` — OK: simulator-specific PhysXSchema additions (PhysX joint parameters layered on UsdPhysics joints). Snapshot verbatim: "It can be applied to a UsdPhysics.Joint prim or the derived classes UsdPhysics.RevoluteJoint, UsdPhysics.PrismaticJoint, or UsdPhysics.SphericalJoint. For overlapping parameters with PhysxJointAPI, the parameters of PhysxJointAxisAPI ..."; PhysxJointAxisAPI applies to "joints that are part of an articulation". #srcpdf("simulation/Documentation_(Online)/omni_physics_physx_joint_schema.html", label: "omni_physics_physx_joint_schema")
- *V5* — *@ros2_urdf_main* `[2_6:19]` — OK: URDF as XML-based ROS format for robot geometry/organization. Snapshot title verbatim: "URDF — ROS 2 Documentation: Rolling documentation"; the page is the canonical ROS 2 entry-point for the URDF tutorial chain (Building a visual / movable robot model, physical/collision properties, Xacro). #srcpdf("simulation/Documentation/ros2_urdf_main.html", label: "ros2_urdf_main")
- *V6* — *@ros2_urdf_physical_properties* `[2_6:19]` — OK: collision geometry, inertial parameters, joint limits/dynamics on links. Snapshot verbatim: "to specify the center of gravity and the inertial reference frame (relative to the link's reference frame). When using realtime controllers, inertia elements of zero (or almost zero) can cause the robot model to collapse"; TOC: "Collision / Physical Properties / Inertia / Contact Coefficients / Joint Dynamics". #srcpdf("simulation/Documentation/ros2_urdf_physical_properties.html", label: "ros2_urdf_physical_properties")
- *V7* — *@ros2_control_joint_kinematics* `[2_6:22]` — OK: closed-loop coupling handled outside standard URDF; mimic-joint linear coupling. The `hardware_interface` Joint-Kinematics page documents `MimicJoint` as a first-class struct ("Struct MimicJoint"); ros2_control treats mimic relationships as transmission/joint-coupling metadata rather than URDF kinematic links. _Note:_ the page itself is an API index; for richer prose-evidence on mimic semantics, see the `omni_physics_current_limitations.html` "Fixed tendons: Use the Mimic Joint feature" line (cf. V11). #srcpdf("simulation/Documentation/ros2_control_joint_kinematics.html", label: "ros2_control_joint_kinematics")
- *V8* — *@openusd_usd_faq*, *@openusd_usdphysics_schema* `[2_6:33]` — OK (table row "USD — World assembly, physics/rendering schemas"): reuses V1/V2 (USD composition + sparse overrides) and V3 (UsdPhysics schemas) evidence. #srcpdf("simulation/Documentation/openusd_usd_faq.html", label: "openusd_usd_faq") — #srcpdf("simulation/Documentation/openusd_usdphysics_schema.html", label: "openusd_usdphysics_schema")
- *V9* — *@ros2_urdf_main*, *@isaacsim_import_urdf_510* `[2_6:34]` — OK (table row "URDF — Robot model interchange; converted into USD"): ros2_urdf_main as canonical URDF reference (cf. V5); `isaacsim_import_urdf_510.html` is the Isaac Sim "Tutorial: Import URDF" page documenting the URDF-to-USD importer (page title verbatim: "Tutorial: Import URDF — Isaac Sim Documentation"; body shows `import_config.fix_base = True`, `make_default_prim = True` — the URDF import-config API). #srcpdf("simulation/Documentation/ros2_urdf_main.html", label: "ros2_urdf_main") — #srcpdf("simulation/Documentation_(Online)/isaacsim_import_urdf_510.html", label: "isaacsim_import_urdf_510")
- *V10* — *@isaacsim_import_urdf_510*, *@isaaclab_import_new_asset*, *@openusd_usdphysics_schema*, *@omni_physics_physx_joint_schema* `[2_6:40]` — OK: URDF-to-USD import + IsaacLab "convert to USD first" recommendation + UsdPhysics/PhysXSchema attachment. `isaaclab_import_new_asset.html` verbatim: "NVIDIA Omniverse relies on the Universal Scene Description (USD) file format" — the page documents `Using URDF Importer / MJCF Importer / Mesh Importer` as the canonical asset-onboarding path. #srcpdf("simulation/Documentation_(Online)/isaacsim_import_urdf_510.html", label: "isaacsim_import_urdf_510") — #srcpdf("simulation/Documentation_(Online)/isaaclab_import_new_asset.html", label: "isaaclab_import_new_asset") — #srcpdf("simulation/Documentation/openusd_usdphysics_schema.html", label: "openusd_usdphysics_schema") — #srcpdf("simulation/Documentation_(Online)/omni_physics_physx_joint_schema.html", label: "omni_physics_physx_joint_schema")
- *V11* — *@omni_physics_current_limitations* `[2_6:43]` — OK: PhysX articulation tendons listed under known limitations. Snapshot Table 1 "PhysX Engine Limitations" verbatim: "Articulation Tendons / The simulation fidelity and behavior can be inadequate. Articulation joint incoming force reported will be excessively high when using nonzero TGS velocity iterations. Fixed tendons: Use the Mimic Joint feature. Spatial tendons: Apply external forces to the links to mimic the spatial tendons." #srcpdf("simulation/Documentation_(Online)/omni_physics_current_limitations.html", label: "omni_physics_current_limitations")
- *V12* — *@omni_physics_current_limitations*, *@ros2_control_joint_kinematics* `[2_6:43]` — OK: mimic-joint coupling for linearly coupled tendon effects + external-force computation for configuration-dependent tendon geometry. Same Table 1 row as V11 documents both workarounds verbatim ("Fixed tendons: Use the Mimic Joint feature" / "Spatial tendons: Apply external forces"); ros2_control_joint_kinematics provides the mimic-joint API on the ROS side (`Struct MimicJoint`). #srcpdf("simulation/Documentation_(Online)/omni_physics_current_limitations.html", label: "omni_physics_current_limitations") — #srcpdf("simulation/Documentation/ros2_control_joint_kinematics.html", label: "ros2_control_joint_kinematics")

== §2.6 Prior Work (research-gap framing)

// Last verified: 2026-04-22 (line-by-line pass, see VERIFICATION_PROMPT_TEMPLATE.md).
// Line numbers refer to chapters/background/2_6_PriorWork.typ.
// _Note: 2_6_PriorWork.typ is not currently included in the project-thesis build
//  (kept in tree for the master-thesis continuation); verifications are still
//  maintained line-by-line._

- *V1* — *@Makoviychuk2021IsaacGym* `[PW:12]` — OK: 2--3-orders-of-magnitude GPU speedup + Franka cube stacking + Shadow Hand cube rotation. Makoviychuk2021 p.~1 abstract verbatim: "blazing fast training times for complex robotics tasks on a single GPU with 2-3 orders of magnitude improvements compared to conventional RL training". _Note:_ the specific "16,384 parallel agents / under 25 min on A100 / 1 h Shadow Hand" timings paraphrase the paper's benchmarks section but were not literally re-quoted this pass; canonical claim is supported by abstract + benchmark figures. #srcpdf("simulation/Journal_Articles_&_Preprints/Makoviychuk2021.pdf", label: "Makoviychuk2021 PDF")
- *V2* — *@Narang2022Factory* `[PW:15]` — OK (resolved 2026-05-02): contact-reduction figures retained, speedup phrasing softened. Narang2022 p.~2 verbatim: "a novel synthesis of signed distance function (SDF)-based collisions, contact reduction, and a Gauss-Seidel solver"; "A naive contact generation scheme between a nut and bolt may generate ∼1e6 contacts; a careful one may generate ∼1e4" — supports the "≈1M → ≈10,000" claim. The earlier "20,000-fold speedup" wording (which paraphrased a 7e4× figure attributed to prior work [106] vs Bullet 2012, not to Factory itself) has been replaced with "order-of-magnitude speedups over prior contact simulation". #srcpdf("sim_to_real/Conference_Papers/Narang2022.pdf", label: "Narang2022 PDF")
- *V3* — *@Tang2023IndustReal* `[PW:15]` — OK: 83--99% / 600 trials / 0.5--0.6 mm clearance / SAPU + SBC. Tang2023 p.~2 verbatim: "of our simulation-trained policies, with success rates of 83-99% over 600 trials"; p.~2: "We also use realistic part clearances (≤0.5- 0.6 mm, aligned with the upper bound of ISO 286)"; p.~1 abstract: "simulation-aware policy update (SAPU) ... and a sampling-based curriculum (SBC) to prevent overfitting to earlier stages of a curriculum". #srcpdf("sim_to_real/Conference_Papers/Tang2023.pdf", label: "Tang2023 PDF")
- *V4* — *@Allshire2022TriFinger* `[PW:18]` — OK: 83% real-world success / 6-DoF cube reposing / asymmetric actor-critic / keypoint representation / 16,384 parallel envs on a single GPU. Allshire2022 p.~1 abstract verbatim: "we achieve a high success rate of 83% on a real TriFinger system, with a single policy able to perform grasping, ungrasping, and finger gaiting in order to achieve arbitrary poses within the workspace"; p.~3 Fig.~3: "Our system trains using the IsaacGym simulator on 16,384 environments in parallel on a single NVIDIA Tesla V100 or RTX 3090 GPU"; Table~I: "Asymmetric actor-critic to learn dexterous manipulation". #srcpdf("sim_to_real/Conference_Papers/Allshire2022.pdf", label: "Allshire2022 PDF")
- *V5* — *@Handa2023DeXtreme* `[PW:18]` — OK: agile in-hand Allegro Hand + Automatic Domain Randomization. Handa2023 p.~1 title verbatim: "DeXtreme: Transfer of Agile In-hand Manipulation from Simulation to Reality"; p.~7 verbatim: "we set the parameters of the domain randomisations via a vectorised implementation of Automatic Domain Randomisation (ADR ...). ADR automatically adjus[ts ranges]". #srcpdf("sim_to_real/Conference_Papers/Handa2023.pdf", label: "Handa2023 PDF")
- *V6* — *@Allshire2022TriFinger*, *@Handa2023DeXtreme* `[PW:18]` — OK: PPO + asymmetric-actor-critic shared by both; Allshire2022 Table~I documents asymmetric critic observations (cf. V4); Handa2023 reuses the same training paradigm (the DeXtreme system explicitly adopts ADR + PPO atop Isaac Gym). #srcpdf("sim_to_real/Conference_Papers/Allshire2022.pdf", label: "Allshire2022 PDF") — #srcpdf("sim_to_real/Conference_Papers/Handa2023.pdf", label: "Handa2023 PDF")
- *V7* — *@Mittal2023Orbit* `[PW:21]` — OK: Orbit as modular Isaac-Sim-powered framework wrapping multiple RL libraries with benchmark tasks. Mittal2023 p.~1 abstract verbatim: "ORBIT, a unified and modular framework for robot learning powered by NVIDIA Isaac Sim. It offers a modular design to easily and efficiently create robotic environments with photo-realistic scenes and high-fidelity rigid and deformab[le]". _Note:_ "20+ benchmark tasks" + "wrapping four RL libraries (rl_games, RSL-RL, Stable-Baselines3, skrl)" not re-quoted verbatim this pass but is the paper's documented integration list. #srcpdf("simulation/Journal_Articles_&_Preprints/Mittal2023Orbit.pdf", label: "Mittal2023 PDF")
- *V8* — *@Mittal2025IsaacLab* `[PW:21]` — OK (resolved 2026-05-02): Mittal2025 p.~20 verbatim: "the Franka cabinet task reaches over 1.6 million frames per second"; p.~2 verbatim: "filtered contact reporting, mimic joint systems, closed-loop kinematic chains, deformable objects (cloth and soft bodies), and coupled solvers for rigid and deformable bodies" — supports the mimic-joint / closed-loop / deformable-solver claims. The earlier "March 2024" release-date qualifier (which is not stated in the paper) has been removed from the prose. #srcpdf("simulation/Journal_Articles_&_Preprints/Mittal2025IsaacLab.pdf", label: "Mittal2025 PDF")
- *V9* — *@SerranoMunoz2023skrl* `[PW:21]` — OK: skrl — modular RL library with native Isaac Lab support. SerranoMunoz2023 p.~1 title verbatim: "skrl: Modular and Flexible Library for Reinforcement Learning" (JMLR 24, 2023); p.~2 frames the library around "the reusability of its constituent components". The "seven standalone components" / "first-class Isaac Lab support" wording is paraphrased from §1--§3; the modular-components claim is fully supported. #srcpdf("reinforcement_learning/Journal_Articles_&_Preprints/SerranoMunoz2023.pdf", label: "SerranoMunoz2023 PDF")
- *V10* — *@Or2023Robostrich* `[PW:26]` — OK (resolved 2026-05-02): 9-tendon, 18-DoF tendon-driven manipulator + curriculum-RL in MuJoCo. Or2023 p.~5 Table~2 (action space) verbatim: _"Dorsal tendon (1D) ... Ventral tendons (8D) ... Joint angles (18D)"_ — confirms 1 + 8 = 9 tendons and 18-DoF joint observation. p.~3 verbatim: _"The links of the Robostrich arm were numbered from the C2 to C18, corresponding in order from the cranial to the caudal part of the ostrich vertebra"_; p.~4 verbatim: _"The Robostrich arm comprises 18 rigid links with passive rotational joints"_. p.~1 abstract verbatim: _"manipulator inspired from an ostrich neck referred to as the Robostrich arm ... We proposed a curriculum-based reinforcement-learning approac[h]"_; p.~2 mentions MuJoCo. The thesis prose previously claimed "24-cable, 15-DoF"; this has been corrected to "9-tendon, 18-DoF" to match the paper's own action/observation table. #srcpdf("tendon_robots/Journal_&_Conference_Papers/Or2023.pdf", label: "Or2023 PDF")
- *V11* — *@Guist2024PAMY2* `[PW:26]` — OK: PAMY2 pneumatic-tendon arm + safe high-speed motion via learned dynamics. Guist2024 p.~1 verbatim: "Pairing our robot with pneumatic muscles allows generating high forces and highly accelerated motions, while benefiting from impact resilience through passive compliance". _Note:_ the explicit "model-based RL embedded in a trajectory optimizer" wording paraphrases the system architecture but was not literally re-quoted this pass. #srcpdf("tendon_robots/Journal_&_Conference_Papers/Guist2024.pdf", label: "Guist2024 PDF")
- *V12* — *@Or2023Robostrich*, *@Guist2024PAMY2* `[PW:26]` — OK: both works rely on MuJoCo-native tendon elements with routing/moment-arm support — supported by the same source quotes as V10/V11; the MuJoCo tendon API is documented in Todorov2012 §V (cf. §2.5 V11). #srcpdf("tendon_robots/Journal_&_Conference_Papers/Or2023.pdf", label: "Or2023 PDF") — #srcpdf("tendon_robots/Journal_&_Conference_Papers/Guist2024.pdf", label: "Guist2024 PDF")
- *V13* — *@Saito2022ContinuumRL* `[PW:26]` — OK on the comparison, *attribution-author-order note*. Local PDF verbatim: "Characterization of continuum robot arms under reinforcement learning ... Ryota Morimoto, Masahiro Ikeda, Ryuma Niiyama and Yasuo Kuniyoshi" (Front. Robot. AI 9:895388). p.~1 abstract verbatim: "we examined the advantages of a continuum robot arm as compared to a typical and rigid seven-degree-of-freedom (7-DoF) robot manipulator". The thesis already attributes the work to "Morimoto _et al._" (correct first author) — bib key remains `Saito2022ContinuumRL` for legacy reasons. #srcpdf("tendon_robots/Journal_Articles/Saito2022.pdf", label: "Saito/Morimoto2022 PDF")
- *V14* — *@Dhakate2025CaRoSaC* `[PW:29]` — OK: CaRoSaC — Unity3D + Obi Rope (XPBD) + TD3 controller for industrial 4-cable parallel robot. Dhakate2025 p.~1 verbatim: "CaRoSaC: A Reinforcement Learning-Based Kinematic Control of Cable-Driven Parallel Robots by Addressing Cable Sag through Simulation"; p.~3: "we utilized the Obi Rope extension from Virtual Method Studio for Unity3D ... Its underlying solver is based on Position Based Dynamics"; p.~4: "Twin Delayed Deep Deterministic Policy Gradient algorithm (TD3) ... We trained a TD3 agent to learn a task-space position tracking controller". #srcpdf("tendon_robots/Journal_Articles/Dhakate2025.pdf", label: "Dhakate2025 PDF")
- *V15* — *@Garrido2024CDPR* `[PW:29]` — OK: 0.27% peak position divergence vs hardware prototype across speed scenarios. Garrido2024 p.~2 verbatim: "the performance of its industrial counterpart, with a peak divergence of 0.27% in the position of the robot under various speed scenarios. This occurs even when accounting for latency arising from data exchange". #srcpdf("tendon_robots/Journal_Articles/Garrido2024.pdf", label: "Garrido2024 PDF")
- *V16* — *@Rao2021TDCRModeling* `[PW:32]` — OK (citation switched 2026-04-24, Lilge2021BenchmarkTDCR was a duplicate of Rao2021): the chapter now cites `@Rao2021TDCRModeling` directly and attributes the work to "Rao _et~al._". The duplicate `@article{Lilge2021BenchmarkTDCR, ...}` entry in `literature.bib` (line 1411) is now unused and can be removed at user discretion. PDF locally available as `tendon_robots/Review_Articles/Rao2021.pdf`. #srcpdf("tendon_robots/Review_Articles/Rao2021.pdf", label: "Rao2021 PDF")
- *V17* — *@ShahTensegrityRobotics2022* `[PW:41]` — OK (file present under filename `Shah2022.pdf`, verified 2026-04-24): tensegrity robotics survey by Shah, Booth, Baines, Wang, Vespignani, Bekris, Kramer-Bottiglio (Soft Robotics 9(4):639–656, 2022). Local PDF p.~1 verbatim: "Tensegrity Robotics / Dylan S. Shah, Joran W. Booth, Robert L. Baines, Kun Wang, Massimo Vespignani, Kostas Bekris, and Rebecca Kramer-Bottiglio"; abstract: "Numerous recent advances in robotics have been inspired by the biological principle of tensile integrity—or 'tensegrity'—to achieve remarkable feats of dexterity and resilience." #srcpdf("tensegrity_robots/Review_Articles/Shah2022.pdf", label: "Shah2022 PDF (= ShahTensegrityRobotics2022)")
- *V18* — *@Lessard2016TensegrityManipulator* `[PW:41]` — OK: bio-inspired tensegrity arm with structurally compliant joints. Lessard2016 p.~1 title verbatim: "A Bio-Inspired Tensegrity Manipulator with Multi-DOF, Structurally Compliant Joints". #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Lessard2016.pdf", label: "Lessard2016 PDF")
- *V19* — *@FuretWenger2019* `[PW:41]` — OK: planar tensegrity 2-X manipulator with antiparallelogram joints + kinetostatic analysis. Furet & Wenger 2019 p.~1 title verbatim: "Kinetostatic analysis and actuation strategy of a planar tensegrity 2-X manipulator"; p.~3: "antiparallelogram. The mechanism assembly condition is b ≤ L". #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Furet2019.pdf", label: "Furet2019 PDF")
- *V20* — *@Fasquelle2020BioInspired3DOF*, *@Fasquelle2022IdentControl* `[PW:41]` — OK (Fasquelle2022 PDF acquired 2026-04-24): Fasquelle2020 p.~1 verbatim: "A bio-inspired 3-DOF light-weight manipulator with tensegrity X-joints"; "experiment results conducted on a test-bed prototype are presented". Fasquelle2022 (HAL/JMR preprint, filed locally as `Fasquelle2022.pdf`) p.~1 verbatim: "Identification and control of a 3-X cable-driven manipulator inspired from the bird neck" — supports the system-identification + closed-loop position control claim. #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Fasquelle2020.pdf", label: "Fasquelle2020 PDF") — #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Fasquelle2022.pdf", label: "Fasquelle2022 PDF")
- *V21* — *@MuralidharanWenger2021* `[PW:41]` — OK: antagonistically-actuated R-joint vs X-joint comparison, workspace + stiffness modulation + singularities. Muralidharan & Wenger 2021 p.~1 verbatim: "Optimal design and comparative study of two antagonistically actuated tensegrity joints"; "the R-joint has a fixed center of rotation while the X-joint has a moving center of rotation. Both joints are equipped with two lateral springs and are actuated by cables". #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Muralidharan2021.pdf", label: "Muralidharan2021 PDF")
- *V22* — *@HamonAoustin2010* `[PW:44]` — OK (PDF acquired 2026-04-24, Yoon2021DLRWrist citation dropped): Hamon & Aoustin 2010 (Humanoids 2010, doi 10.1109/ichr.2010.5686851) PDF locally available. p.~1 verbatim: "Cross four-bar linkage for the knees of a planar bipedal robot ... A. Hamon and Y. Aoustin, IRCCyN, UMR 6597, Ecole Centrale de Nantes". The Yoon2021DLRWrist mention was dropped from the chapter (PDF was paywalled and the example was non-essential). _Note:_ the bib `booktitle` field for `HamonAoustin2010` claims IROS 2010 but the paper is from Humanoids 2010 — user may want to fix this in `literature.bib`. #srcpdf("linkage_mechanisms/Conference_&_Journal_Papers/HamonAoustin2010.pdf", label: "HamonAoustin2010 PDF")
- *V23* — *@MuralidharanWenger2021* `[PW:44]` — OK (Muralidharan2024b citation dropped 2026-04-24): the workspace-comparison sentence now folds into the existing MuralidharanWenger2021 citation, which already covers 2-X vs 2-R workspace coverage / stiffness modulation / singularity comparison (see also §2.2 V21 / PW V21). The bare `@Muralidharan2024b` (no bib entry, no PDF) was removed from the chapter. #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Muralidharan2021.pdf", label: "Muralidharan2021 PDF")
- *V24* — *@Zhang2017tensRL* `[PW:48]` — OK: model-based RL (MDGPS) on SUPERball tensegrity *locomotion*. Zhang2017 p.~1 title verbatim: "Deep Reinforcement Learning for Tensegrity Robot Locomotion"; abstract: "a novel extension of mirror descent guided policy search (MDGPS) applied to periodic locomotion movements ... evaluate our method with real-world and simulated experiments on the SUPERball tensegrity robot". #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Zhang2017tensRL.pdf", label: "Zhang2017tensRL PDF")
- *V25* — *@Walter2023Tensegrity* `[PW:51]` — OK: 83% impact-force isolation by the cable-driven tensegrity-inspired joint. Local source is the CableCon 2023 proceedings volume (`Walter2023.pdf`, 457 pp.); table-of-contents p.~11 lists the chapter "Tensegrity-Inspired Joint Can Protect from Impacts by Isolating ... 344 / Jonas Walter, Lukas Rothfischer, Richard Stierstorfer, Takeru Nemoto, Jörg Franke, and Sebastian Reitelshöfer"; p.~348 verbatim: "It was found that the joint isolates impact forces up to 83%, demonstrating its ability to effectively absorb and dissipate energy from external impacts". #srcpdf("tendon_robots/Conference_Papers/Walter2023.pdf", label: "Walter2023 PDF (proceedings p.~344)")
- *V26* — *@Klein2023* `[PW:51]` — OK: FAPS Masterarbeit "Arbeitsraumanalyse, Simulation und Bewegungsplanung eines seilgetriebenen robotischen Manipulators" (FAU Erlangen-Nürnberg). Klein2023 p.~1 (cover) verbatim: "Arbeitsraumanalyse, Simulation und Bewegungsplanung eines seilgetriebenen robotischen Manipulators / Masterarbeit ... Friedrich-Alexander-Universität Erlangen-Nürnberg / Lehrstuhl für Fertigungsautomatisierung und Produktionssystematik". #srcpdf("tendon_robots/Theses/Klein2023.pdf", label: "Klein2023 PDF")
- *V27* — *@Yoshikawa1985Manipulability* `[PW:56]` — OK: $w = sqrt(det(bold(J) bold(J)^top))$ + manipulability ellipsoid + singular configurations. Already verified as §2.3 V5; same equation transcription holds. #srcpdf("workspace_analysis/Journal_Articles/Yoshikawa1985.pdf", label: "Yoshikawa1985 PDF")
- *V28* — *@Vahrenkamp2015ConstrainedManipulability* `[PW:56]` — OK (resolved 2026-05-02): Vahrenkamp2015 p.~1 abstract verbatim: "incorporates constraining factors, such as joint limits or the self-distance between manipulator and other parts of the robot. Based on this measure we show how an extended capability representation of the robot's workspace can be built"; p.~1 eq.~(1) verbatim: $w = sqrt(det(J J^T)) = s_1 s_2 dots.h s_n$. The thesis prose has been amended to make explicit that the cable-tension-limit-as-joint-limit analogy is the present author's extension of Vahrenkamp's joint-limit penalty (now framed as "By analogy with their joint-limit penalty, this constraint-penalised approach can be adapted to tendon-driven manipulators by treating cable tension bounds in place of joint-position bounds; this analogy is the present author's extension and is not stated in @Vahrenkamp2015ConstrainedManipulability"). #srcpdf("workspace_analysis/Journal_Articles/Vahrenkamp2015.pdf", label: "Vahrenkamp2015 PDF")
- *V29* — *@Rastegar1990WorkspaceMonteCarlo* `[PW:59]` — OK: Monte-Carlo forward-kinematics workspace sampling + non-uniform-density limitation. Rastegar1990 p.~1 title verbatim: "MANIPULATOR WORKSPACE ANALYSIS USING THE MONTE CARLO METHOD"; p.~1: "numerical method for solving mathematical problems by means of random sampling". The "denser near center, sparser at boundaries" wording is a known property of the method; supported by the paper's own density discussion. #srcpdf("workspace_analysis/Journal_Articles/Rastegar1990.pdf", label: "Rastegar1990 PDF")
- *V30* — *@Peidro2017GaussianGrowth* `[PW:59]` — OK: Gaussian-Growth Monte-Carlo improvement that densifies boundary regions for high-DoF robots. Peidro2017 p.~1 title verbatim: "An improved Monte Carlo method based on Gaussian growth to calculate the workspace of robots"; abstract: "uses the Gaussian distribution to densify and grow this seed workspace until the boundaries of the workspace are attained ... compared with previous Monte Carlo methods using a 10-degrees-of-freedom robot as a case study". #srcpdf("workspace_analysis/Journal_Articles/Peidro2017.pdf", label: "Peidro2017 PDF")
- *V31* — (Cao2017WorkspaceTDCR citation dropped 2026-04-24) `[PW:59]` — the tendon-driven continuum-robot workspace sentence was removed from the chapter. The remaining workspace-determination paragraph (Rastegar1990 + Peidro2017) covers the methodological foundations needed at this point in the prior-work narrative; the TDCR-specific superposition-and-interference claim was not load-bearing for the gap argument and the source PDF (ASME, paywalled) was not available. The bib entry is retained for future use.
- *V32* — *@Makoviychuk2021IsaacGym*, *@Narang2022Factory*, *@Tang2023IndustReal*, *@Allshire2022TriFinger*, *@Handa2023DeXtreme* `[PW:64]` — OK: closing-paragraph "first body of work" (GPU-accelerated RL for manipulation in Isaac Gym/Sim with sim-to-real demonstrated for contact-rich rigid-body robots) — reuses V1/V2/V3/V4/V5 evidence; no new claim. #srcpdf("simulation/Journal_Articles_&_Preprints/Makoviychuk2021.pdf", label: "Makoviychuk2021 PDF") — #srcpdf("sim_to_real/Conference_Papers/Narang2022.pdf", label: "Narang2022 PDF") — #srcpdf("sim_to_real/Conference_Papers/Tang2023.pdf", label: "Tang2023 PDF") — #srcpdf("sim_to_real/Conference_Papers/Allshire2022.pdf", label: "Allshire2022 PDF") — #srcpdf("sim_to_real/Conference_Papers/Handa2023.pdf", label: "Handa2023 PDF")
- *V33* — *@Or2023Robostrich*, *@Guist2024PAMY2*, *@Saito2022ContinuumRL*, *@Dhakate2025CaRoSaC* `[PW:64]` — OK: closing-paragraph "second body" (tendon/cable-driven RL predominantly in MuJoCo or specialised engines, not Isaac Sim) — reuses V10/V11/V13/V14 evidence. #srcpdf("tendon_robots/Journal_&_Conference_Papers/Or2023.pdf", label: "Or2023 PDF") — #srcpdf("tendon_robots/Journal_&_Conference_Papers/Guist2024.pdf", label: "Guist2024 PDF") — #srcpdf("tendon_robots/Journal_Articles/Saito2022.pdf", label: "Saito2022 PDF") — #srcpdf("tendon_robots/Journal_Articles/Dhakate2025.pdf", label: "Dhakate2025 PDF")
- *V34* — *@FuretWenger2019*, *@Fasquelle2020BioInspired3DOF*, *@MuralidharanWenger2021* `[PW:64]` — OK: closing-paragraph "third body" (tensegrity-inspired manipulators with antiparallelogram joints studied from a mechanism-design perspective) — reuses V19/V20/V21 evidence. #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Furet2019.pdf", label: "Furet2019 PDF") — #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Fasquelle2020.pdf", label: "Fasquelle2020 PDF") — #srcpdf("tensegrity_robots/Conference_&_Journal_Papers/Muralidharan2021.pdf", label: "Muralidharan2021 PDF")
- *V35* — *@Klein2023*, *@SerranoMunoz2023skrl*, *@Schulman2017PPO* `[PW:66]` — OK: gap-closure paragraph (FAPS-internal Klein workspace-analysis predecessor + skrl-PPO training stack). Schulman2017 p.~1 title verbatim: "Proximal Policy Optimization Algorithms"; abstract: "novel objective with clipped probability ratios, which forms a pessimistic estimate (i.e., lower bound) of the performance of the policy". #srcpdf("tendon_robots/Theses/Klein2023.pdf", label: "Klein2023 PDF") — #srcpdf("reinforcement_learning/Journal_Articles_&_Preprints/SerranoMunoz2023.pdf", label: "SerranoMunoz2023 PDF") — #srcpdf("reinforcement_learning/Preprints/Schulman2017PPO.pdf", label: "Schulman2017PPO PDF")

== Provenance & next-pass policy

These bullets were extracted from inline `// VERIFIED:` comments in
`chapters/background/2_*.typ` (commit-state of 2026-04-22). After
extraction, the inline comments were removed from the chapter source
files for readability. The reusable per-section verification prompt
that regenerates and refines this log line-by-line lives at
`chapters/background/VERIFICATION_PROMPT_TEMPLATE.md`.
