"""Regenerate step-response time-trace CSVs and validation_metrics.json.

Sources of truth:

* ``src/tensegrity_pick/scripts/step_response_results/``
    Newest constant-tension tendon CSVs (May 2026 rerun) — already
    synced to the thesis ``assets/data/step_response/`` directory.

* ``src/tensegrity_pick/outputs/model_validation/{pd,tendon_physical}/data/``
    NPZ trial files produced by ``run_step_response_pd.py`` /
    ``run_step_response_tendon.py`` (April 2026).  Used to populate the
    PD ``wrist_x`` traces and *all* physical-antiparallelogram traces,
    which are not regenerated by the newer tendon-only test script.

Outputs (under ``doc/Theses/project_thesis/assets/data/step_response/``):

* ``step_pd_wrist_x_{10,20,30}.csv``           — extracted from PD NPZ
* ``step_physical_{elbow,wrist_x,wrist_y}_*.csv`` — extracted from physical NPZ
* ``step_response_results.csv``               — copied from src/ (newest tendon)
* ``validation_metrics.json``                 — recomputed from time traces

Klein (2023) Tabelle 4.2 reference values (Gazebo vs. real robot) are
embedded as ``klein_*`` keys.  Settling-time data is NOT available in
Klein's report, so those entries remain ``null``.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Final

import numpy as np
import pandas as pd

# ── Paths ────────────────────────────────────────────────────────────────────
HERE: Final = Path(__file__).resolve().parent
THESIS_DATA: Final = HERE.parent / "assets" / "data" / "step_response"
SRC_ROOT: Final = HERE.parents[3] / "src" / "tensegrity_pick"
SRC_NEW_TENDON_DIR: Final = SRC_ROOT / "scripts" / "step_response_results"
SRC_PD_NPZ: Final = SRC_ROOT / "outputs" / "model_validation" / "pd" / "data"
SRC_PHYS_NPZ: Final = SRC_ROOT / "outputs" / "model_validation" / "tendon_physical" / "data"


# ── Klein 2023 Tabelle 4.2 (Gazebo simulator vs. real-robot reference) ───────
# Values lifted verbatim from the printed table.  ``-`` / blank cells are
# stored as ``None`` (Klein did not derive a value).  Settling time is NOT
# part of Tabelle 4.2 — Klein only reports rise time, overshoot, NRMSE,
# RMSE, max velocity and motor currents.
KLEIN_TABLE_4_2: Final[dict[tuple[str, int], dict[str, float | None]]] = {
    ("wrist_x_joint", 10): {"nrmse": 25.5, "rise_ms": None,  "overshoot": None},
    ("wrist_x_joint", 20): {"nrmse":  9.9, "rise_ms": None,  "overshoot": 23.4},
    ("wrist_x_joint", 30): {"nrmse": 11.2, "rise_ms": 125.0, "overshoot": 31.5},
    ("wrist_y_joint", 10): {"nrmse": 19.2, "rise_ms": None,  "overshoot": None},
    ("wrist_y_joint", 20): {"nrmse": 11.6, "rise_ms": None,  "overshoot": 33.4},
    ("wrist_y_joint", 30): {"nrmse": 12.5, "rise_ms":  84.5, "overshoot": 40.6},
    ("elbow_joint",   20): {"nrmse": 39.1, "rise_ms": None,  "overshoot": None},
    ("elbow_joint",   30): {"nrmse": 11.7, "rise_ms": None,  "overshoot": None},
    ("elbow_joint",   40): {"nrmse": 12.1, "rise_ms": 367.5, "overshoot":  7.8},
}

# Joints/amplitudes covered.
JOINT_AMPS: Final[list[tuple[str, list[int]]]] = [
    ("elbow_joint",   [20, 30, 40]),
    ("wrist_x_joint", [10, 20, 30]),
    ("wrist_y_joint", [10, 20, 30]),
]

# Short joint label used in CSV filenames (matches plot_step_responses.py).
JOINT_SHORT: Final[dict[str, str]] = {
    "elbow_joint":   "elbow",
    "wrist_x_joint": "wrist_x",
    "wrist_y_joint": "wrist_y",
}


# ── Step-response metric computation (mirrors model_validation/common.py) ────
def _compute_metrics(
    t: np.ndarray,
    actual: np.ndarray,
    setpoint: np.ndarray,
    *,
    settling_band_pct: float = 2.0,
) -> dict[str, float | None]:
    """Compute rise (10 → 90 %), settling (±2 %), overshoot, NRMSE.

    Mirrors :func:`tensegrity_pick.scripts.model_validation.common.compute_step_metrics`
    so the regenerated JSON stays consistent with the NPZ values.
    """
    t = np.asarray(t, dtype=float)
    y = np.asarray(actual, dtype=float)
    sp = np.asarray(setpoint, dtype=float)

    # Find the first commanded step (0 → amplitude transition).
    sp_diff = np.abs(np.diff(sp))
    step_idx = int(np.argmax(sp_diff > 0.5)) + 1 if np.any(sp_diff > 0.5) else 0
    if step_idx <= 0 or step_idx >= len(sp):
        return {
            "rise_time_ms": None, "settling_time_ms": None,
            "overshoot_pct": None, "nrmse_pct": 0.0,
        }
    setpoint_amp = float(sp[step_idx])
    step_start_s = float(t[step_idx])

    # Restrict to the hold window (until setpoint changes again or end).
    next_change = step_idx + 1
    while next_change < len(sp) and abs(sp[next_change] - setpoint_amp) < 0.5:
        next_change += 1
    end_idx = min(next_change, len(t))

    t_seg = t[step_idx:end_idx]
    y_seg = y[step_idx:end_idx]

    # Rise time 10 → 90 %.
    rise_ms: float | None = None
    if abs(setpoint_amp) > 1e-3:
        thr10 = 0.1 * setpoint_amp
        thr90 = 0.9 * setpoint_amp
        if setpoint_amp > 0:
            i10 = np.where(y_seg >= thr10)[0]
            i90 = np.where(y_seg >= thr90)[0]
        else:
            i10 = np.where(y_seg <= thr10)[0]
            i90 = np.where(y_seg <= thr90)[0]
        if i10.size and i90.size:
            dt_rise = t_seg[i90[0]] - t_seg[i10[0]]
            if dt_rise > 0:
                rise_ms = float(dt_rise * 1000.0)

    # Overshoot (sign-aware).
    overshoot_pct: float | None = None
    if abs(setpoint_amp) > 1e-3:
        if setpoint_amp > 0:
            peak = float(np.max(y_seg))
            if peak > setpoint_amp:
                overshoot_pct = float((peak - setpoint_amp) / setpoint_amp * 100.0)
        else:
            peak = float(np.min(y_seg))
            if peak < setpoint_amp:
                overshoot_pct = float((peak - setpoint_amp) / setpoint_amp * 100.0)

    # Settling time (±2 % band).
    settle_ms: float | None = None
    band = settling_band_pct / 100.0 * abs(setpoint_amp)
    if band > 0:
        out_of_band = np.where(np.abs(y_seg - setpoint_amp) > band)[0]
        if out_of_band.size:
            last_out = int(out_of_band[-1])
            if last_out + 1 < len(t_seg):
                settle_ms = float((t_seg[last_out + 1] - step_start_s) * 1000.0)
        else:
            settle_ms = 0.0

    # NRMSE over the hold window, normalised by trial range.
    err = y_seg - setpoint_amp
    rmse = float(np.sqrt(np.mean(err ** 2)))
    rng = float(np.max(y) - np.min(y))
    nrmse = rmse / rng * 100.0 if rng > 1e-6 else 0.0

    return {
        "rise_time_ms": rise_ms,
        "settling_time_ms": settle_ms,
        "overshoot_pct": overshoot_pct,
        "nrmse_pct": float(nrmse),
    }


# ── NPZ → CSV extraction ─────────────────────────────────────────────────────
def _npz_to_csv(npz_path: Path, csv_path: Path) -> None:
    d = np.load(npz_path)
    df = pd.DataFrame({
        "time_s":       np.asarray(d["time_s"], dtype=float),
        "actual_deg":   np.asarray(d["actual_deg"], dtype=float),
        "setpoint_deg": np.asarray(d["setpoint_deg"], dtype=float),
    })
    df.to_csv(csv_path, index=False, float_format="%.4f")
    print(f"  [npz→csv] {npz_path.name}  →  {csv_path.name}")


def extract_missing_csvs() -> None:
    """Generate PD-wrist_x and physical CSV traces from the NPZ archive."""
    THESIS_DATA.mkdir(parents=True, exist_ok=True)

    # PD wrist_x — only joint missing from the May 2026 rerun.
    for amp in (10, 20, 30):
        npz = SRC_PD_NPZ / f"wrist_x_joint__{amp}deg.npz"
        if npz.exists():
            _npz_to_csv(npz, THESIS_DATA / f"step_pd_wrist_x_{amp}.csv")

    # Physical antiparallelogram tendon (elbow + both wrists).
    physical_files = {
        "elbow":   ("elbow_physical",   [20, 30, 40]),
        "wrist_x": ("wrist_x_joint",    [10, 20, 30]),
        "wrist_y": ("wrist_y_joint",    [10, 20, 30]),
    }
    for short, (npz_joint, amps) in physical_files.items():
        for amp in amps:
            npz = SRC_PHYS_NPZ / f"{npz_joint}__{amp}deg.npz"
            if npz.exists():
                _npz_to_csv(npz, THESIS_DATA / f"step_physical_{short}_{amp}.csv")


def sync_newest_tendon_results() -> None:
    """Copy the newest `step_response_results.csv` from the source tree."""
    src = SRC_NEW_TENDON_DIR / "step_response_results.csv"
    dst = THESIS_DATA / "step_response_results.csv"
    if src.exists():
        shutil.copy2(src, dst)
        print(f"  [copy] {src} → {dst}")


# ── validation_metrics.json regeneration ─────────────────────────────────────
def _metrics_from_csv(csv_path: Path) -> dict[str, float | None] | None:
    if not csv_path.exists():
        return None
    df = pd.read_csv(csv_path)
    return _compute_metrics(df["time_s"].to_numpy(),
                            df["actual_deg"].to_numpy(),
                            df["setpoint_deg"].to_numpy())


def regenerate_validation_metrics() -> None:
    records: list[dict] = []
    for joint, amps in JOINT_AMPS:
        short = JOINT_SHORT[joint]
        for amp in amps:
            klein = KLEIN_TABLE_4_2[(joint, amp)]
            pd_metrics = _metrics_from_csv(THESIS_DATA / f"step_pd_{short}_{amp}.csv")
            tn_metrics = _metrics_from_csv(THESIS_DATA / f"step_tendon_{short}_{amp}.csv")
            ph_short = "elbow" if joint == "elbow_joint" else short
            ph_metrics = _metrics_from_csv(THESIS_DATA / f"step_physical_{ph_short}_{amp}.csv")

            rec: dict = {
                "joint": joint,
                "amplitude": amp,
                # Klein (2023) Gazebo reference (Tabelle 4.2).
                "klein_nrmse":     klein["nrmse"],
                "klein_rise_ms":   klein["rise_ms"],
                "klein_overshoot": klein["overshoot"],
                # No settling-time data in Klein 2023.
                "klein_settling_ms": None,
            }
            for tag, m in (("pd", pd_metrics), ("tendon", tn_metrics), ("physical", ph_metrics)):
                if m is None:
                    rec[f"{tag}_nrmse"] = None
                    rec[f"{tag}_rise_ms"] = None
                    rec[f"{tag}_settling_ms"] = None
                    rec[f"{tag}_overshoot"] = None
                else:
                    rec[f"{tag}_nrmse"]        = m["nrmse_pct"]
                    rec[f"{tag}_rise_ms"]      = m["rise_time_ms"]
                    rec[f"{tag}_settling_ms"]  = m["settling_time_ms"]
                    rec[f"{tag}_overshoot"]    = m["overshoot_pct"]
            records.append(rec)

    out = THESIS_DATA / "validation_metrics.json"
    out.write_text(json.dumps(records, indent=2))
    print(f"  [json]  wrote {len(records)} records → {out}")


def main() -> None:
    print("Regenerating step-response data ...")
    extract_missing_csvs()
    sync_newest_tendon_results()
    regenerate_validation_metrics()
    print("Done.")


if __name__ == "__main__":
    main()
