// §4.6 Reinforcement Learning Tasks
#import "../../../../shared/formatting/macros.typ": *
#import "../../../../shared/formatting/acronyms.typ": *
#import "../../../../shared/formatting/template.typ": faps-figure, faps-table
#import "../../../../shared/formatting/diagrams.typ": reward-structure

== Reinforcement Learning Task Formulation <sec:rl_tasks>

Two progressive #ac("RL") tasks are defined on the validated robot model. The _reach_ task tests fundamental motion control across actuation modes. The _cube place_ task extends reach to a full manipulation sequence including grasping, transport, and release. Both tasks share a common simulation environment and use the manager-based #ac("MDP") workflow provided by IsaacLab~@isaaclab_task_design_workflows.

Both tasks are formulated against the tendon-driven arm as their fixed reference, in line with the role of the arm as the only physical subsystem of the manipulator (see @sec:physical_robot). The base and the gripper enter the task definitions only through the modular robot configuration: observations, actions, and rewards are written so that the prismatic base or the parallel-jaw gripper can be replaced by an alternative subsystem without rewriting the task itself, which is important for re-using these tasks on future iterations of the platform.

=== Simulation Environment <subsec:sim_env>

All tasks share a common base scene configuration (`ProjBaseSceneCfg`) that provides the physical environment for conveyor-based manipulation. @tab:scene_elements summarizes the scene elements.

#faps-table(
  table(
    columns: (auto, 1fr),
    table.header([*Element*], [*Details*]),
    [Ground plane], [Flat collision surface at $z = 0$],
    [Dome light], [Uniform scene illumination],
    [Dual conveyor belt], [4~m total length, belt surface at 0.80~m height],
    [Target drum], [Plastic drum at $(0.15, 0.85, 0.0)$~m, diameter $0.547$~m],
    [Environment spacing], [5.0~m between parallel environment replicas],
  ),
  caption: [Shared scene elements inherited by all tasks. The conveyor and drum are positioned to represent an industrial pick-and-place station.],
  short-caption: [Shared scene elements],
) <tab:scene_elements>

The robot is ceiling-mounted at a configurable position above the conveyor belt. This mounting configuration places the end-effector workspace directly above the belt surface, enabling top-down grasping motions representative of industrial sorting stations.

=== Reach Task <subsec:reach_task>

The reach task trains the robot to track arbitrary end-effector poses (position and orientation). It serves two purposes: validating that each actuation mode supports effective #ac("RL")-based control, and providing baseline learning curves for cross-variant comparison.

==== Target generation
Targets are generated by a custom forward-kinematics-sampled pose command generator: random joint configurations within the joint limits from @tab:joint_ranges are evaluated through forward kinematics, guaranteeing that every target is kinematically reachable. Targets are resampled every 4.0~s. Early resampling occurs when the position error drops below 0.05~m, preventing the policy from stalling on already-reached targets.

==== Observations
The policy observes: relative joint positions with additive uniform noise ($plus.minus 0.01$), relative joint velocities ($plus.minus 0.01$), the 7-D target pose (3-D position + 4-D quaternion), and the previous action vector. The total observation dimension varies with actuation mode: 22 (PD), 24 (tendon), 28 (physical tendon).

==== Actions
The action parameterization differs by actuation mode:
- *PD-driven:* 5-D joint position deltas (scale 0.5), processed by `ImplicitActuator`.
- *Tendon-driven (constant $J^top$):* 2 base position deltas + 5 cable tensions, mapped per tendon to the saturation envelope of @subsec:drive_system.
- *Physical tendon (body-force):* 2 base position-to-limit actions + 5 physical tendon effort commands.

==== Rewards
@tab:reach_rewards summarizes the reward function. The design uses a combination of dense tracking penalties and a fine-grained proximity bonus to shape smooth approach behavior.

#faps-table(
  table(
    columns: (auto, auto, 1fr),
    table.header([*Term*], [*Weight*], [*Function*]),
    [`position_tracking`], [$-0.2$], [L2 position error $||bold(p) - bold(p)^*||_2$],
    [`position_tracking_fine`], [$+0.1$], [$1 - tanh(||bold(p) - bold(p)^*||_2 / 0.1)$],
    [`orientation_tracking`], [$-0.1$], [Quaternion angular error],
    [`action_rate`], [$-10^(-4) arrow -0.005$], [L2 action delta (curriculum)],
    [`joint_vel`], [$-10^(-4) arrow -0.001$], [L2 joint velocity (curriculum)],
    [`position_reached`#super[\*]], [$+10^(-6)$], [Indicator: $||bold(p) - bold(p)^*||_2 < 0.05$~m],
    [`orientation_reached`#super[\*]], [$+10^(-6)$], [Indicator: angular error below threshold],
    [`pose_reached`#super[\*]], [$+10^(-6)$], [Indicator: position and orientation both reached],
  ),
  caption: [Reach task reward terms. Arrows indicate curriculum-scheduled weight ramping. Position and orientation tracking are dense; regularization terms increase over training to discourage jerky motions. Terms marked #super[\*] carry a negligible weight ($10^(-6)$) and act as TensorBoard-logged success metrics rather than learning signals.],
  short-caption: [Reach task reward terms],
) <tab:reach_rewards>

==== Terminations
Episodes terminate at the 12.0~s timeout (360 steps at 30~Hz control frequency) or upon joint velocity divergence ($> 100$~rad/s, indicating simulation instability).

==== Curriculum
The regularization weights for `action_rate` and `joint_vel` ramp linearly from their initial (low) values to their final (higher) values over 4,500 environment steps. This permits aggressive early exploration before penalizing high-frequency motion.

==== Variants
Five robot/actuation configurations are trained under identical #ac("PPO") hyperparameters: Tensegrity PD-driven, Tensegrity Tendon-driven (constant $J^top$), Tensegrity Physical tendon (body-force), UR10e PD-driven, and Kinova Gen3 PD-driven. The latter two (from the Isaac Sim asset library) are included as industrial-robot baselines for cross-actuation calibration of the reach reward shaping; their full performance analysis and any tendon-driven port are deferred to the master thesis.

=== Cube Place Task <subsec:cube_place_task>

The cube place task extends reach to a full pick-transport-place sequence using the Robotiq 2F-140 gripper. The robot must grasp a green cube from the conveyor belt, transport it to the target drum, and release it inside.

==== Success criterion
An episode is successful when the green cube's center enters the cylindrical drum success-detection volume (radius~$=0.2735$~m, height~$=0.30$~m, axially aligned with the physical drum). This detection volume is slightly larger than the actual drum opening to tolerate residual cube oscillation after release; the physical drum diameter ($0.547$~m, see @tab:scene_elements) is used only for collision geometry. Episodes run the full 5~s without early success termination — the per-step success reward (weight = 100) accumulates, causing successful policies to maximize the number of time steps the cube spends inside the drum.

==== Observations
The policy receives 47 (PD-driven) or 49 (tendon-driven) observations: joint positions and velocities, end-effector pose and linear velocity, the green cube's position relative to the gripper's grasp center, fingertip-to-cube distance vectors, gripper closure and joint torque, cube linear and angular velocities, the cube's position relative to the drum, and the previous action vector.

==== Actions
The action parameterization is:
- *PD-driven:* 6-D — 2 base position deltas, 3 arm joint deltas, 1 binary gripper.
- *Tendon-driven (constant $J^top$):* 8-D — 2 base position deltas, 5 cable tensions (per-tendon $T_"max"$ as in the reach task; see @subsec:drive_system), 1 binary gripper.

==== Reward functions
The reward implements a sequential pipeline guiding the agent through approach, grasp, lift, transport, and release. Two persistent latches gate the downstream reward terms: `was_grasped` activates once the gripper has successfully closed on the cube and lifted it (verified by closure ratio, proximity, and low cube velocity), and `was_placed` activates once the green cube is detected inside the drum volume. Both latches remain set for the rest of the episode. This prevents reward hacking — the agent cannot collect transport or success rewards without first establishing a stable grasp, and the cleanup reward only opens once placement is confirmed. @fig:reward_structure summarises every reward term, the phases in which it is active, and its associated gating condition; the complete weight specification (task rewards, regularisation, and metric-only terms) is tabulated in @appendix:place_regularization.

#faps-figure(
  reward-structure(),
  caption: [Reward structure of the cube place task. Each row is one reward term (left: identifier and weight); the right strip shows in which of the six task phases the term contributes a non-zero value. Bar colour groups terms by purpose. The two vertical markers on the top strip indicate where the latches `was_grasped` (after _Lift_) and `was_placed` (after _Release_) flip on, gating the downstream rewards listed in the rightmost column. Penalties and regularisation terms are active throughout the episode.],
  short-caption: [Reward structure of the cube place task],
) <fig:reward_structure>

==== Terminations
Episodes run the full 5.0~s (250 steps at 50~Hz). Truncation occurs on joint velocity divergence or belt collision (end-effector penetration $> 0.20 "m"$ below belt surface).

==== Curriculum
Four curriculum events are scheduled (all triggered on global environment-step counts): (1)~the cube spawn band widens linearly from $plus.minus 0.10$~m to $plus.minus 0.30$~m between 25,000 and 100,000 steps (`widen_spawn`), exposing the agent to progressively harder reach geometries; (2)~the red distractor cube is activated at 125,000 steps (`activate_red`), introducing colour-selective grasping once the agent reliably handles the green cube alone; (3)~the action-rate regularisation weight is ramped from $-10^(-4)$ to $-2 times 10^(-3)$ at 150,000 steps; and (4)~the joint-velocity regularisation weight is ramped likewise at 150,000 steps, encouraging smoother motions once the basic task is learned.

=== Cube Sort Task (Outlook) <subsec:cube_sort>

The cube sort task extends cube place to a multi-object scenario with eight green and eight red cubes on a moving conveyor belt. The robot must selectively pick green cubes and place them in the drum while ignoring red cubes. This task introduces object discrimination, dynamic planning, and multi-grasp sequencing. Full formulation and training results are deferred to the master thesis.
