// §4.6 Reinforcement Learning Tasks
#import "../../../../shared/formatting/macros.typ": *
#import "../../../../shared/formatting/acronyms.typ": *
#import "../../../../shared/formatting/template.typ": faps-figure, faps-table
#import "../../../../shared/formatting/diagrams.typ": reward-structure

== Reinforcement Learning Task Formulation <sec:rl_tasks>

Two progressive #ac("RL") tasks are defined on the validated robot model. The _reach_ task tests fundamental motion control across actuation modes. The _cube place_ task extends reach to a full manipulation sequence including grasping, transport, and release. Both tasks share a common simulation environment and use the manager-based #ac("MDP") workflow provided by Isaac~Lab~@isaaclab_task_design_workflows.

Both tasks are formulated robot agnostic. The robot variants enter the task definitions only through modular robot configuration. Observations, actions, and rewards are written so that robot subsystems or entire robots can be replaced by an alternative construction without rewriting the task itself, which is important for re-using these tasks on future iterations of the platform and adapting the tasks to future iterations of the task.

=== Simulation Environment <subsec:sim_env>

All tasks share a common base scene configuration (`ProjBaseSceneCfg`) that provides the physical environment for conveyor-based manipulation. @tab:scene_elements summarizes the scene elements. @fig:reach_scene shows the scene layout for the reach task, which is identical to the cube place task except for the absence of the cube and drum. The conveyor belt provides a dynamic workspace with a moving target object, while the drum serves as a spatially constrained goal region for placement.

#faps-table(
  table(
    columns: (auto, 1fr),
    table.header([*Element*], [*Details*]),
    [Ground plane], [Flat collision surface at $z = 0$],
    [Dome light], [Uniform scene illumination],
    [Dual conveyor belt], [4~m total length, belt surface at 0.80~m height],
    [Target drum], [Plastic drum at $(0.15, 0.85, 0.0)$~m, diameter $0.547$~m],
    [Environment spacing], [5.0~m between parallel environment replicas],
  ),
  caption: [Shared scene elements inherited by all tasks. The conveyor and drum are positioned to represent an industrial pick-and-place station.],
  short-caption: [Shared scene elements],
) <tab:scene_elements>

The robot is ceiling-mounted at a configurable position above the conveyor belt. This mounting configuration places the end-effector workspace directly above the belt surface, enabling top-down grasping motions representative of industrial sorting stations.

=== Reach Task <subsec:reach_task>

The reach task trains the robot to track arbitrary end-effector poses (position and orientation). It serves two purposes: validating that each actuation mode supports effective #ac("RL")-based control, and providing baseline learning curves for cross-variant comparison.

#faps-figure(
  image("../../../assets/figures/tasks/reach_physical_1.png", width: 100%),
  caption: [Reach task scene overview. The robot is ceiling-mounted above the conveyor belt, with the target pose randomly sampled within the reachable workspace. The task objective is to move the end-effector to the target pose and hold it there for as long as possible within the 12~s episode duration.],
  short-caption: [Reach task scene overview],
) <fig:reach_scene>

==== Target generation
Targets are generated by a custom forward-kinematics-sampled pose command generator: random joint configurations within the joint limits from @tab:joint_ranges are evaluated through forward kinematics, guaranteeing that every target is kinematically reachable. Targets are resampled every episode. The target pose is represented as a 7-D vector of 3-D position and 4-D quaternion orientation.

==== Observations
The policy observes relative joint positions with additive uniform noise ($plus.minus 0.01$), relative joint velocities ($plus.minus 0.01$), the 7-D target pose (3-D position + 4-D quaternion), and the previous action vector. The total observation dimension varies with actuation mode: 22 (PD), 24 (tendon), 28 (physical tendon).

==== Actions
The action parameterization differs by actuation mode:
- *PD-driven:* 5-D joint position deltas (scale 0.5), processed by `ImplicitActuator`.
- *Tendon-driven (constant $J^top$):* 2 base position deltas + 5 cable tensions, mapped per tendon to the saturation envelope of @subsec:drive_system.
- *Physical tendon (body-force):* 2 base position-to-limit actions + 5 physical tendon effort commands.

==== Rewards
@tab:reach_rewards summarizes the reward function. The design uses a combination of dense tracking penalties and a fine-grained proximity bonus to shape smooth approach behavior. The rewards are based on the Isaac Lab example task `Reach`, with added success indicators and curriculum-scheduled regularisation terms to encourage smooth motions. The reward weights are tuned to balance the competing objectives of accurate tracking, energy-efficient motion, and successful task completion. 

#faps-table(
  table(
    columns: (auto, auto, 1fr),
    table.header([*Term*], [*Weight*], [*Function*]),
    [`position_tracking`], [$-0.2$], [L2 position error $||bold(p) - bold(p)^*||_2$],
    [`position_tracking_fine`], [$+0.1$], [$1 - tanh(||bold(p) - bold(p)^*||_2 / 0.1)$],
    [`orientation_tracking`], [$-0.1$], [Quaternion angular error],
    [`action_rate`], [$-10^(-4) arrow -0.005$], [L2 action delta (curriculum)],
    [`joint_vel`], [$-10^(-4) arrow -0.001$], [L2 joint velocity (curriculum)],
    [`position_reached`#super[\*]], [$+10^(-6)$], [Indicator: $||bold(p) - bold(p)^*||_2 < 0.05$~m],
    [`orientation_reached`#super[\*]], [$+10^(-6)$], [Indicator: angular error below threshold],
    [`pose_reached`#super[\*]], [$+10^(-6)$], [Indicator: position and orientation both reached],
  ),
  caption: [Reach task reward terms. Arrows indicate curriculum-scheduled weight ramping. Position and orientation tracking are dense. Regularization terms increase over training to discourage jerky motions. Terms marked #super[\*] carry a negligible weight ($10^(-6)$) and act as TensorBoard-logged success metrics rather than learning signals.],
  short-caption: [Reach task reward terms],
) <tab:reach_rewards>

==== Terminations
Episodes terminate at the 6.0~s timeout (180 steps at 30~Hz control frequency) or upon joint velocity divergence ($> 100$~rad/s, indicating simulation instability).

==== Curriculum
The regularization weights for `action_rate` and `joint_vel` ramp linearly from their initial (low) values to their final (higher) values over 4,500 environment steps. This permits aggressive early exploration before penalizing high-frequency motion.

==== Variants
Three actuation configurations are trained under identical #ac("PPO") hyperparameters: Tensegrity PD-driven, Tensegrity Tendon-driven (constant $J^top$), Tensegrity Physical tendon (body-force).

==== Multi-Seed Training Protocol <subsec:reach_multi_seed>
Each of the three actuation variants is trained with $N = 5$ independent random seeds (seeds 0--4) under otherwise identical hyperparameters, scene configuration, and reward terms. The seeds are propagated consistently to `random`, `numpy`, `torch`, and the CUDA generator at environment construction. Aggregating over several seeds rather than reporting a single run follows the reproducibility guidance of Henderson _et al._, who use five trials per evaluation in their own study and show that a single learning curve is an unreliable summary of deep #ac("RL") performance.
// Henderson2018DeepRLMatters — p.2 §"Experimental Analysis" ("To ensure fairness we run five experiment trials for each evaluation, each with a different preset random seed") and p.5 §"Random Seeds and Trials" + Fig.5 (two 5-seed splits of one 10-seed run differ significantly; "there can be no specific number of trials specified as a recommendation"). Uploaded arXiv PDF.
The chosen budget of $N = 5$ is the smallest sample that still supports a seed-aggregated mean and a dispersion estimate; it matches the trial count used by Henderson _et al._, but lies below the $N gt.eq 20$ samples that Colas _et al._ recommend for confirmatory bootstrap-based inference, so the cross-variant comparison is treated accordingly (cf.~@subsec:reach_significance)~@Henderson2018DeepRLMatters~@Colas2018HowManySeeds.
// Colas2018HowManySeeds — p.18--19 §6 "Final recommendations" ("A bootstrap test should not be used with less than 20 samples") and p.16 §5.1 + Fig.6 (small-N false-positive inflation). Uploaded PDF.
The limitation imposed by this sample size and a planned rerun on the high-variance physical tendon variant are discussed in @ch:discussion.

==== Evaluation Harness <subsec:reach_eval_harness>
After training, each of the $3 times 5 = 15$ #ac("PPO") policies is evaluated by a unified harness (`evaluate.py`) that constructs the play-mode environment, loads the final agent checkpoint, runs $50$ parallel envs $times$ $10$ episodes ($= 500$ episodes per (variant, seed) cell), and writes a per-cell JSON file. The same harness also evaluates three reference agents on the same target stream:

- *Zero:* Emits a zero action every step (the #ac("PD") setpoint coincides with the current pose, the cable variants apply no length change).
- *Random:* Uniform $cal(U)(-1, 1)$ over the wrapped action space.
- *Heuristic (DLS-IK):* A damped-least-squares differential inverse-kinematics controller with position priority, mapped through the inverse of the `JointPositionToLimitsAction` term to the $[-1, 1]$ action range. This baseline is defined only for the #ac("PD") variant. The two tendon variants act in cable-tension space and a torque-to-tension controller for them is itself a separate research problem outside the scope of this thesis.

The metrics recorded per cell are the episode-level mean and standard deviation of the position-reach success rate (any-step indicator of $bold(p) - bold(p)^* lt.eq 0.05 "m"$), the final-step position error, the final-step orientation error, and the time-to-first-reach over successful episodes. The threshold is read from the command term configuration to keep harness and environment definitions in sync. To prevent the auto-reset that Isaac~Lab applies inside `env.step()` from corrupting the recorded final-step values, the position and orientation error tensors are snapshotted _before_ each step and the snapshot is recorded for environments that terminate in the corresponding step.

#pagebreak()

=== Cube Place Task <subsec:cube_place_task>

The cube place task extends reach to a full pick-transport-place sequence using the Robotiq 2F-140 gripper. The robot must grasp a green cube from the conveyor belt, transport it to the target drum, and drop it inside.

#faps-figure(
  image("../../../assets/figures/tasks/cube_place_approx.png", width: 100%),
  caption: [Cube place task scene overview. The robot is ceiling-mounted above the conveyor belt. The task objective is to pick up the green cube, transport it to the drum, and place it inside within the 5~s episode duration.],
  short-caption: [Cube place task scene overview],
) <fig:cube_place_scene>

==== Success criterion
An episode is successful when the green cube's center enters the cylindrical drum success-detection volume (radius~$=0.2735$~m, height~$=0.30$~m, axially aligned with the physical drum). This detection volume is slightly larger than the actual drum opening to tolerate residual cube oscillation after release. The physical drum diameter ($0.547$~m, see @tab:scene_elements) is used only for collision geometry. Episodes run the full 5~s without early success termination. The per-step success reward (weight = 100) accumulates, causing successful policies to maximize the number of time steps the cube spends inside the drum.

==== Observations
The policy receives 47 (PD-driven) or 49 (tendon-driven) observations: joint positions and velocities, end-effector pose and linear velocity, the green cube's position relative to the gripper's grasp center, fingertip-to-cube distance vectors, gripper closure and joint torque, cube linear and angular velocities, the cube's position relative to the drum, and the previous action vector.

==== Actions
The action parameterization is:
- *PD-driven:* 6-D — 2 base position deltas, 3 arm joint deltas, 1 binary gripper.
- *Tendon-driven (constant $J^top$):* 8-D — 2 base position deltas, 5 cable tensions (per-tendon $T_"max"$ as in the reach task. See @subsec:drive_system), 1 binary gripper.

#pagebreak()

==== Reward functions
The reward implements a sequential pipeline guiding the agent through approach, grasp, lift, transport, and release. Two persistent latches gate the downstream reward terms: `was_grasped` activates once the gripper has successfully closed on the cube and lifted it (verified by closure ratio, proximity, and low cube velocity), and `was_placed` activates once the green cube is detected inside the drum volume. Both latches remain set for the rest of the episode. This prevents reward hacking. The agent cannot collect transport or success rewards without first establishing a stable grasp, and the cleanup reward only opens once placement is confirmed. @fig:reward_structure summarises every reward term, the phases in which it is active, and its associated gating condition. The complete weight specification (task rewards, regularisation, and metric-only terms) is tabulated in @appendix:place_regularization.

#faps-figure(
  reward-structure(),
  caption: [Reward structure of the cube place task. Each row is one reward term (left: identifier and weight). The right strip shows in which of the six task phases the term contributes a non-zero value. Bar colour groups terms by purpose. The two vertical markers on the top strip indicate where the latches `was_grasped` (after _Lift_) and `was_placed` (after _Release_) flip on, gating the downstream rewards listed in the rightmost column. Penalties and regularisation terms are active throughout the episode.],
  short-caption: [Reward structure of the cube place task],
) <fig:reward_structure>

#pagebreak()

==== Sequential reward shaping <subsec:place_reward_shaping>

The dense reward terms of the cube place task implement a staged shaping scheme. Each phase of the manipulation pipeline contributes one continuous shaping signal whose gradient is non-zero only in the spatial or temporal region where it must guide the policy, and the corresponding gates ensure that the cumulative reward landscape preserves the original task objective. The composition is motivated by three constraints that emerged during the iterative reward design. The start configuration places the end-effector approximately $0.25 "m"$ above the cube, so a single proximity term cannot cover both the long-range approach and the near-grasp precision. The transition from holding to releasing exhibits a strong local optimum because the per-step accumulated reward of carrying the cube exceeds the instantaneous release reward. And the introduction of the red distractor cube must shape active separation rather than passive avoidance.

The shaping signals are derived from a common $tanh$-based potential of the form 
$ r(d) = 1 - tanh(d / sigma_"std") $ <eq:shaping_potential>
, where $d$ is the relevant distance metric and $sigma_"std"$ is a tunable standard deviation. This potential, which is used for all distance-based shaping terms, provides a smooth gradient that encourages proximity while avoiding excessively large rewards at the start of the episode. The function's output, which is bounded in $[0,1]$, has its steepest gradient near $d=0$, saturates at large distances and therefore behaves well numerically across the entire workspace.

Two paired terms cover the approach to the cube. A coarse reaching reward 
$ r_"reach,c" = 2.0 dot (1 - tanh(d_"fc" / 2.0)) $ 
with $d_"fc"$ the fingertip-to-cube distance and a fine reaching reward 
$ r_"reach,f" = 5.0 dot (1 - tanh(d_"fc" / 0.5)) $
. The wide standard deviation in the coarse term provides a measurable gradient across the full $0.25 "m"$ initial offset, while the narrower fine term sharpens the gradient inside the gripper's pre-grasp envelope. Both terms are gated by `(not grasp_active) and (not task_done)`, so they switch off once a stable grasp is established and do not compete with the transport rewards downstream. A gating condition that proved necessary in the optimisation iterations to break the policy out of an early local optimum in which the arm hovered next to the cube without closing the gripper.

Grasping is shaped by 
$ r_"grasp" = 3.0 dot c dot (1 - tanh(d_"fc" / 0.08)) $
, where $c in [0,1]$ is the gripper closure fraction. The product structure rewards closure only when the cube is actually between the fingers, which prevents the trivial "close anywhere" policy. The lifting step uses a binary reward of weight $5.0$ that fires when the cube is above the belt and the gripper is closed with low cube velocity, complemented by a smooth height bonus of weight $5.0$ proportional to the cube's altitude relative to the drum rim. Together these terms provide the dense signal required for #ac("PPO") to credit the moment of stable contact, after which the `was_grasped` latch opens the transport phase.

Transport is again split into a coarse and a fine term. A goal-tracking reward 
$ r_"goal,c" = 40.0 dot (1 - tanh(d_"cg,xy" / 1.0)) $ 
acting on the horizontal cube-to-drum distance, and a fine goal-tracking reward 
$ r_"goal,f" = 10.0 dot (1 - tanh(d_"cg,xy" / 0.20)) $ 
that pulls the cube tightly over the drum opening. The asymmetric weighting (coarse $4 times$ fine) was chosen because the coarse term must overcome the per-step holding incentive. The policy is otherwise rewarded for keeping the cube grasped indefinitely. 

The release reward 
$ r_"rel" = 25.0 dot (1 - c) dot bb(1)_{"xy in drum"} dot bb(1)_{"above rim"} $ 
is granted only when the gripper opens above the drum opening and was tuned from an initial weight of $10.0$. The per-step reward received while holding the cube above the drum (goal tracking, lift, height bonus, arm utilisation) sums to approximately $72$ units, which exceeds the original release reward and creates a local optimum in which the policy holds the cube indefinitely. Raising the release weight to $25.0$ makes opening the gripper the better single-step decision, after which the in-target success bonus of $100$ units per step dominates the remaining episode return.

The success bonus 
$ r_"succ" = 100 dot bb(1)_{"green in drum"} $ 
is intentionally large and per-step rather than terminal, so that successful policies maximise the time the cube spends inside the drum. This design follows the Popov~_et al._~@Popov2017DataEfficientManipulation pattern of dense terminal-region rewards for data-efficient manipulation and matches the no-early-termination episode structure described above.

Red-cube safety is shaped by two terms that act before the green cube has been grasped. 
$ r_"red,clr" = 5.0 dot tanh(d_"rd,xy" / 0.4) $ 
rewards red-cube clearance from the drum, and 
$ r_"red,sep" = 3.0 dot tanh(d_"rg" / 0.15) $
 rewards separation between the two cubes. The tanh growth (rather than $1 - tanh$) is chosen so that the reward starts at zero when the cubes overlap and grows as they separate, which provides an active push-aside gradient when the red cube blocks access to the green one. Both terms are gated on `not was_grasped` and were introduced after observing that a passive penalty alone does not generate a corrective gradient until after the failure mode has occurred. Together with the soft regularisation terms (action rate, joint velocity, joint torque, belt contact), the reward composition therefore distributes a non-zero gradient across every phase of the task and avoids the sparse-reward exploration problem that motivated the staged structure in the first place.

==== Terminations
Episodes run the full 5.0~s (250 steps at 50~Hz). Truncation occurs on joint velocity divergence or belt collision (end-effector penetration $> 0.20 "m"$ below belt surface).

==== Curriculum
Four curriculum events are scheduled (all triggered on global environment-step counts): (1)~the cube spawn band widens linearly from $plus.minus 0.10$~m to $plus.minus 0.30$~m between 25,000 and 100,000 steps (`widen_spawn`), exposing the agent to progressively harder reach geometries. (2)~the red distractor cube is activated at 125,000 steps (`activate_red`), introducing colour-selective grasping once the agent reliably handles the green cube alone. (3)~the action-rate regularisation weight is ramped from $-10^(-4)$ to $-2 times 10^(-3)$ at 150,000 steps and (4)~the joint-velocity regularisation weight is ramped likewise at 150,000 steps, encouraging smoother motions once the basic task is learned.

==== Evaluation Scope
In contrast to the reach task (@subsec:reach_multi_seed), the cube-place task is trained and reported on a single random seed per variant. Each place run spans the full $300"k"$-step budget on a markedly heavier, contact-rich scene (graspable cube, distractor, and drum), so a seed-aggregated sweep across all three variants exceeded the time and compute budget available for the project thesis. The multi-seed evaluation harness is therefore reserved for the master-thesis follow-up, and the cube-place metrics in @sec:place_results are reported as single-seed point estimates rather than seed-aggregated results (cf.~@sec:discussion_limitations).

=== Cube Sort Task (Outlook) <subsec:cube_sort>

The cube sort task extends cube place to a multi-object scenario with eight green and eight red cubes on a moving conveyor belt. The robot must selectively pick green cubes and place them in the drum while ignoring red cubes. This task introduces object discrimination, dynamic planning, and multi-grasp sequencing. Full formulation and training results are deferred to the master thesis.
