// §4.6 Reinforcement Learning Tasks
#import "../../../../shared/formatting/macros.typ": *
#import "../../../../shared/formatting/acronyms.typ": *
#import "../../../../shared/formatting/template.typ": faps-figure, faps-table
#import "../../../../shared/formatting/diagrams.typ": reward-pipeline

== Reinforcement Learning Task Formulation <sec:rl_tasks>

Two progressive #ac("RL") tasks are defined on the validated robot model. The _reach_ task tests fundamental motion control across actuation modes. The _cube place_ task extends reach to a full manipulation sequence including grasping, transport, and release. Both tasks share a common simulation environment and use the manager-based #ac("MDP") workflow provided by IsaacLab~@isaaclab_task_design_workflows.

=== Simulation Environment <subsec:sim_env>

All tasks share a common base scene configuration (`ProjBaseSceneCfg`) that provides the physical environment for conveyor-based manipulation. @tab:scene_elements summarizes the scene elements.

#faps-table(
  table(
    columns: (auto, 1fr),
    stroke: 0.5pt,
    inset: 6pt,
    table.header([*Element*], [*Details*]),
    [Ground plane], [Flat collision surface at $z = 0$],
    [Dome light], [Uniform scene illumination],
    [Dual conveyor belt], [4~m total length, belt surface at 0.80~m height],
    [Target drum], [Plastic drum at $(0.15, 0.85, 0.0)$~m, diameter $approx 0.55$~m],
    [Environment spacing], [5.0~m between parallel environment replicas],
  ),
  caption: [Shared scene elements inherited by all tasks. The conveyor and drum are positioned to represent an industrial pick-and-place station.],
  short-caption: [Shared scene elements],
) <tab:scene_elements>

The robot is ceiling-mounted at a configurable position above the conveyor belt. This mounting configuration places the end-effector workspace directly above the belt surface, enabling top-down grasping motions representative of industrial sorting stations.

=== Reach Task <subsec:reach_task>

The reach task trains the robot to track arbitrary end-effector poses (position and orientation). It serves two purposes: validating that each actuation mode supports effective #ac("RL")-based control, and providing baseline learning curves for cross-variant comparison.

==== Target generation
Targets are generated by a custom forward-kinematics-sampled pose command generator: random joint configurations within the joint limits from @tab:joint_ranges are evaluated through forward kinematics, guaranteeing that every target is kinematically reachable. Targets are resampled every 4.0~s. Early resampling occurs when the position error drops below 0.05~m, preventing the policy from stalling on already-reached targets.

==== Observations
The policy observes: relative joint positions with additive Gaussian noise ($sigma = 0.01$), relative joint velocities ($sigma = 0.01$), the 7-D target pose (3-D position + 4-D quaternion), and the previous action vector. The total observation dimension varies with actuation mode: 22 (#ac("PD")), 24 (tendon), 28 (physical tendon).

==== Actions
The action parameterization differs by actuation mode:
- *#ac("PD"):* 5-D joint position deltas (scale 0.5), processed by `ImplicitActuator`.
- *Tendon:* 2 base position deltas + 5 cable tensions ($T_"max" = 500 "N"$).
- *Physical tendon:* 2 base position-to-limit actions + 5 physical tendon effort commands.

==== Rewards
@tab:reach_rewards summarizes the reward function. The design uses a combination of dense tracking penalties and a fine-grained proximity bonus to shape smooth approach behavior.

#faps-table(
  table(
    columns: (auto, auto, 1fr),
    stroke: 0.5pt,
    inset: 6pt,
    table.header([*Term*], [*Weight*], [*Function*]),
    [`position_tracking`], [$-0.2$], [L2 position error $||bold(p) - bold(p)^*||_2$],
    [`position_tracking_fine`], [$+0.1$], [$1 - tanh(||bold(p) - bold(p)^*||_2 / 0.1)$],
    [`orientation_tracking`], [$-0.1$], [Quaternion angular error],
    [`action_rate`], [$-10^(-4) arrow -0.005$], [L2 action delta (curriculum)],
    [`joint_vel`], [$-10^(-4) arrow -0.001$], [L2 joint velocity (curriculum)],
  ),
  caption: [Reach task reward terms. Arrows indicate curriculum-scheduled weight ramping. Position and orientation tracking are dense; regularization terms increase over training to discourage jerky motions.],
  short-caption: [Reach task reward terms],
) <tab:reach_rewards>

==== Terminations
Episodes terminate at the 12.0~s timeout (360 steps at 30~Hz control frequency) or upon joint velocity divergence ($> 100$ rad/s, indicating simulation instability).

==== Curriculum
The regularization weights for `action_rate` and `joint_vel` ramp linearly from their initial (low) values to their final (higher) values over 4,500 environment steps. This permits aggressive early exploration before penalizing high-frequency motion.

==== Variants
Five robot/actuation configurations are trained under identical #ac("PPO") hyperparameters: Tensegrity #ac("PD"), Tensegrity Tendon, Tensegrity Physical Tendon, UR10e #ac("PD"), and Kinova Gen3 #ac("PD"). The latter two (from the Isaac Sim asset library) provide industrial-robot baselines; their full analysis is deferred to the master thesis.

=== Cube Place Task <subsec:cube_place_task>

The cube place task extends reach to a full pick-transport-place sequence using the Robotiq 2F-140 gripper. The robot must grasp a green cube from the conveyor belt, transport it to the target drum, and release it inside.

==== Success criterion
An episode is successful when the green cube's center enters the cylindrical drum volume (radius $= 0.2735 "m"$, height $= 0.30 "m"$). Episodes run the full 5~s without early success termination — the per-step success reward (weight = 100) accumulates, causing successful policies to maximize the number of time steps the cube spends inside the drum.

==== Observations
The policy receives 47 (#ac("PD")) or 49 (tendon) observations: joint positions and velocities, end-effector pose and linear velocity, the green cube's position relative to the gripper's grasp center, fingertip-to-cube distance vectors, gripper closure and joint torque, cube linear and angular velocities, the cube's position relative to the drum, and the previous action vector.

==== Actions
The action parameterization is:
- *#ac("PD"):* 6-D — 2 base position deltas, 3 arm joint deltas, 1 binary gripper.
- *Tendon:* 8-D — 2 base position deltas, 5 cable tensions ($T_"max" = 500 "N"$), 1 binary gripper.

==== Reward functions
The reward implements a sequential pipeline guiding the agent through approach, grasp, lift, transport, and release. A persistent `was_grasped` latch gates the transport and release rewards: once the gripper has successfully grasped and lifted the cube (verified by closure ratio, proximity, and low cube velocity), the latch activates and remains set for the remainder of the episode. This prevents reward hacking where the agent collects transport rewards without maintaining a stable grasp. @fig:reward_pipeline illustrates the phased reward structure.

#faps-figure(
  reward-pipeline(),
  caption: [Sequential reward pipeline for the cube place task. The `was_grasped` latch persists once activated and gates all transport and release rewards, ensuring that the policy must actually maintain a grasp to collect downstream rewards.],
  short-caption: [Sequential reward pipeline for the cube place task],
) <fig:reward_pipeline>

#faps-table(
  table(
    columns: (auto, auto, 1fr, auto),
    stroke: 0.5pt,
    inset: 6pt,
    table.header([*Term*], [*Weight*], [*Function*], [*Gate*]),
    [`reaching_object`], [$+1$], [$1 - tanh(d / 0.1)$], [—],
    [`grasping`], [$+5$], [closure $times$ proximity], [—],
    [`lifting_object`], [$+8$], [Binary: above belt, within gripper proximity], [—],
    [`height_bonus`], [$+8$], [$min(Delta z, 0.30) / 0.30$], [—],
    [`goal_tracking`], [$+50$], [$1 - tanh(d_"xy" / 1.0)$], [`was_grasped`],
    [`goal_tracking_fine`], [$+5$], [$1 - tanh(d_"xy" / 0.20)$], [`was_grasped`],
    [`release`], [$+10$], [$(1 - "closure") times "in"_"xy" times "above"_"drum"$], [`was_grasped`],
    [`green_in_target`], [$+100$], [Cube center inside drum], [`was_grasped`],
    [`red_in_target`], [$-12$], [Red cube in drum], [Red active],
  ),
  caption: [Cube place task reward terms. Weights are tuned to create a clear incentive gradient from approach to release. Transport rewards are gated by the `was_grasped` latch to prevent reward hacking.],
  short-caption: [Cube place task reward terms],
) <tab:place_rewards>

==== Terminations
Episodes run the full 5.0~s (250 steps at 25~Hz). Truncation occurs on joint velocity divergence or belt collision (end-effector penetration $> 0.20 "m"$ below belt surface).

==== Curriculum
Two curriculum events are scheduled: (1)~a red distractor cube is introduced at 100,000 environment steps, testing color-selective grasping behavior; (2)~action-rate and joint-velocity regularization weights increase at 200,000 steps, encouraging smoother motions once the basic task is learned.

=== Cube Sort Task (Outlook) <subsec:cube_sort>

The cube sort task extends cube place to a multi-object scenario with eight green and eight red cubes on a moving conveyor belt. The robot must selectively pick green cubes and place them in the drum while ignoring red cubes. This task introduces object discrimination, dynamic planning, and multi-grasp sequencing. Full formulation and training results are deferred to the master thesis.
