// §2.2 Physics Simulation in Isaac Sim 5.1
#import "../../../../shared/formatting/macros.typ": *
#import "../../../../shared/formatting/acronyms.typ": *
#import "../../../../shared/formatting/diagrams.typ": physx-pipeline
#import "../../../../shared/formatting/template.typ": faps-figure, faps-table

== Physics Simulation in Isaac Sim 5.1 <sec:physics_sim>

Physics-based simulation in Isaac~Sim~5.1 is implemented as a layered stack that separates (i) scene and asset description, (ii) binding of these descriptions to a concrete backend, and (iii) numerical solvers that evolve the physical state over time. In the Omniverse ecosystem, physics properties are authored in #ac("USD") through the `UsdPhysics` schema (engine-agnostic physics description) and `PhysXSchema` (backend-specific extensions), allowing assets and environments to be defined declaratively in the scene graph~@openusd_usdphysics_schema @omni_physx_overview. During simulation, the `omni.physx` runtime parses the #ac("USD") stage, constructs the corresponding physics scene, advances the simulation, and writes back poses and state to #ac("USD")~@omni_physx_overview. Isaac~Sim~5.1 uses NVIDIA PhysX~5 as its primary physics backend, providing rigid-body dynamics, articulations, contacts, and particle-based phenomena, with optional #ac("GPU")-accelerated pipelines for throughput-critical workloads such as robot learning experiments with many parallel environments~@isaac_sim_simulation_fundamentals_510 @physx_welcome_513 @physx_gpu_rigid_bodies_510.

A detailed understanding of the underlying physics models and numerical methods is required for two reasons. First, sim-to-real transfer is fundamentally limited by discrepancies between simulated and real dynamics (the _reality gap_), where unmodelled effects, incorrect parameters (e.g., friction and damping), and solver artefacts can lead to policies that exploit simulator-specific regularities~@Jakobi1995RealityGap @Salvato2021RealityGapSurvey. Second, in #ac("RL"), the simulator acts as a data-generating process; thus, modelling and solver choices directly shape the transition distribution used for learning, influencing both policy quality and generalization~@Salvato2021RealityGapSurvey @Peng2018DynamicsRandomization. In practice, this implies that solver selection, time-step choice, contact modelling, and collision geometry approximations must be treated as part of the learning system design, not as interchangeable implementation details~@Peng2018DynamicsRandomization @physx_best_practices_541.

#faps-figure(
  physx-pipeline(),
  caption: [Conceptual physics simulation stack in Isaac~Sim~5.1: physics is authored in #ac("USD") via `UsdPhysics` and `PhysXSchema`, interpreted by `omni.physx`, and simulated using PhysX~5 with optional #ac("GPU")-accelerated pipelines.],
  short-caption: [Isaac Sim physics simulation stack],
) <fig:isaac_sim_physics_stack>

=== Rigid Body Dynamics

Rigid-body simulation assumes that each object moves as a rigid transform, i.e., deformation is neglected and the state is represented by position/orientation and linear/angular velocity. PhysX represents the simulated world as a set of actors (static, kinematic, dynamic) with attached collision shapes and material properties; dynamics are advanced under external loads (e.g., gravity), contact constraints, and joint constraints~@physx_welcome_513 @physx_rigid_body_dynamics_511. In Isaac~Sim, these concepts are exposed through #ac("USD") physics schemas and their PhysX extensions, enabling rigid bodies, colliders, and constraints to be authored on scene primitives~@isaac_sim_simulation_fundamentals_510 @openusd_usdphysics_schema.

*Articulated bodies, joints, and robot mechanisms.*
Robotic manipulators are modelled as articulated mechanisms, i.e., rigid links connected by joints that constrain relative motion and optionally apply actuation (drives). PhysX provides an _articulation_ abstraction that is simulated in reduced coordinates, where the configuration is parameterized by the root pose and joint coordinates rather than the world pose of each link~@physx_articulations_513. This formulation is designed to improve numerical fidelity for mechanisms (e.g., reduced joint error and improved behavior under large mass ratios) compared to independently simulating rigid bodies connected by generic constraints~@physx_articulations_513. In robotics applications, robot mechanisms such as tendon-driven arms and multi-finger grippers are simulated as chains of rigid links with joint constraints and joint drives, such that control inputs act on joint coordinates while the solver enforces inter-link constraints and contacts~@physx_articulations_513 @isaac_sim_simulation_fundamentals_510. PhysX also exposes explicit _articulation tendons_ as additional constraint structures within an articulation, including fixed tendons (coupling joint coordinates) and spatial tendons (spring-damper and limit constraints defined over attachment trees across links), which are relevant when cable-like actuation or joint coupling must be represented at the physics level~@physx_articulations_513 @omni_physics_tendon_authoring.

*Contacts and friction models.*
Rigid-body collision response is formulated as a constrained dynamics problem in which contacts prevent interpenetration and can transfer or dissipate energy through restitution and friction~@physx_rigid_body_collision_510 @isaac_sim_simulation_fundamentals_510. In PhysX, friction and restitution are specified via materials attached to shapes; friction is parameterized by static and dynamic coefficients and can be combined for contacting pairs using configurable combine modes~@physx_rigid_body_dynamics_511 @physx_material_api_510. Because contact-rich manipulation is common in robotic assembly, grasping, and textile handling, parameter choices for friction and restitution are directly coupled to learning outcomes and to sim-to-real robustness~@Salvato2021RealityGapSurvey @Peng2018DynamicsRandomization.

*#acs("TGS") constraint solving in PhysX.*
Rigid-body dynamics with contacts and joints is solved in PhysX using iterative constraint solvers. PhysX supports a classic #acs("PGS")-style solver and the newer #acs("TGS") solver, with #acs("TGS") introduced in PhysX~5.1 and recommended for improved convergence and joint drive accuracy in many scenarios~@physx_rigid_body_dynamics_511. Both solvers operate iteratively over constraint manifolds (contacts, joints, friction), and accuracy is traded for performance by limiting iteration counts. A key motivation for temporal formulations is the observation that, for stiff constraint systems, replacing multiple solver iterations at a long time step by multiple smaller substeps can yield superior stability and accuracy at comparable computational cost~@Macklin2019SmallSteps @physx_best_practices_541. This perspective is consistent with PhysX guidance to consider smaller time steps (or substepping) when joint stability and contact behavior are insufficient under a fixed number of iterations, rather than indefinitely increasing iteration counts~@physx_best_practices_541.

*Simulation parameters and numerical tradeoffs.*
#reg-sym("sym:h")
For robotics and #ac("RL"), the most consequential rigid-body parameters are those controlling temporal discretization, solver convergence, and contact generation. The simulation time step $h$ determines how frequently dynamics are integrated and how often the policy interacts with the environment; overly large $h$ can lead to missed collisions, unstable joint behavior, and biased contact impulses, whereas smaller $h$ improves accuracy at increased compute cost~@physx_simulation_541 @physx_best_practices_541. Solver iteration counts control how many passes are made over constraints; PhysX allows per-actor iteration counts (position and velocity iterations), and the effective iterations for a connected island are determined by the maximum requested within that island~@physx_simulation_541 @physx_rigid_body_dynamics_511. Contact generation is influenced by the pair `contactOffset` and `restOffset`: contact points are generated once shapes are within the combined contact distance, while the rest offset defines the target separation distance at rest, enabling predictive enforcement and reducing jitter at the cost of introducing a small separation bias~@physx_advanced_collision_detection_512. Finally, friction coefficients (static/dynamic) and restitution parameters are specified in materials and substantially affect sliding, sticking, and impact behavior~@physx_material_api_510 @physx_rigid_body_dynamics_511.

#faps-table(
  table(
    columns: (auto, auto, auto),
    align: (left, center, left),
    table.header(
      [*Parameter*], [*Location*], [*Primary effect*],
    ),
    [Time step $h$], [Physics scene], [Accuracy vs.~throughput; contact/joint stability~@physx_simulation_541],
    [Solver iterations], [Actor / island], [Constraint convergence; joint error; contact quality~@physx_rigid_body_dynamics_511],
    [`contactOffset`/`restOffset`], [Shape], [Contact prediction and resting separation~@physx_advanced_collision_detection_512],
    [Friction coefficients], [Material], [Sliding/sticking behavior; grasp stability~@physx_material_api_510],
  ),
  caption: [Selected rigid-body simulation parameters relevant to robot learning in Isaac~Sim / PhysX.],
  short-caption: [Key rigid-body simulation parameters],
) <tab:physx_rigid_body_parameters>

*#ac("GPU")-accelerated rigid bodies for parallel #ac("RL") environments.*
PhysX provides a #ac("GPU") rigid-body pipeline that accelerates broad-phase, narrow-phase, contact generation, and constraint solving on CUDA-capable hardware, while exposing the same API concepts as the #ac("CPU") pipeline~@physx_gpu_rigid_bodies_510. Large performance gains are expected when many rigid bodies are active, which aligns with robot learning workloads where hundreds to thousands of environment replicas are simulated in parallel to increase sample throughput~@physx_gpu_rigid_bodies_510 @Makoviychuk2021IsaacGym. In IsaacLab, PhysX #ac("GPU") simulation is enabled by default and can be configured explicitly; however, #ac("GPU") simulation requires preallocation of internal buffers and may fail when insufficient capacities are specified, which makes sizing and profiling part of simulation configuration for large-scale training~@isaaclab_sim_doc. The broader motivation for #ac("GPU")-resident simulation in #ac("RL") is that physics stepping and policy learning can share device memory, avoiding #ac("CPU")--#ac("GPU") transfer bottlenecks; this design has been demonstrated to yield substantial throughput improvements in GPU-based robot learning platforms~@Makoviychuk2021IsaacGym.

*Collision detection and geometry approximations.*
Collision detection cost is highly sensitive to the chosen collider representation. Primitive shapes (e.g., spheres, boxes, capsules) provide the strongest performance and numerical robustness because intersection tests and contact generation are simple and well-conditioned~@physx_rigid_body_collision_510. Convex meshes provide a practical middle ground for complex objects by enabling efficient collision queries while approximating concave geometry; PhysX requires _convex mesh cooking_ to transform input geometry into an optimized representation for collision detection~@physx_geometry_541. In Isaac~Sim, mesh colliders are often approximated by convex hulls by default for performance, with more expensive approximations available when needed~@isaac_sim_simulation_fundamentals_510. When concavity is important for dynamic objects, convex decomposition (a set of convex parts) is typically preferred over a single triangle mesh collider because triangle-mesh contact generation is expensive and, depending on pipeline and version, may require additional structures. In PhysX~5.3+, dynamic triangle meshes in the #ac("GPU") collision pipeline require an associated #ac("SDF") to accelerate collision detection, increasing memory use but improving query performance~@physx_geometry_530. Therefore, collider selection becomes a modelling choice that trades geometric fidelity against computational cost and solver stability, and this tradeoff must be balanced against the throughput requirements of #ac("RL") training.
