// §2.4 Tendon-Driven Robot Kinematics and Modeling
#import "../../../../shared/formatting/macros.typ": *
#import "../../../../shared/formatting/acronyms.typ": *
#import "../../../../shared/formatting/diagrams.typ": tendon-mapping
#import "../../../../shared/formatting/template.typ": faps-figure

== Tendon-Driven Robot Kinematics and Modeling <sec:tendon_robot>

Tendon-driven robots are articulated mechanisms in which joint motion is generated by tensile elements (tendons) that transmit forces from remote actuators to the joints through pulleys, guides, or routing channels. In this actuation paradigm, the actuators and transmissions can be placed proximally, while the distal structure remains lightweight. This design is widely used in continuum and cable-driven mechanisms, particularly when low distal inertia, compact joint packaging, or intrinsic compliance is desired~@Rao2021TDCRModeling @Nemoto2022CableWrist. At the same time, the mechanical transmission characteristics of tendons introduce additional modeling complexity. The mapping between actuator commands and joint motion depends on geometry (routing and moment arms), tendon elasticity, and non-idealities such as friction and hysteresis, which are frequently reported as dominant error sources in cable- and tendon-driven systems~@Miyasaka2020HysteresisFriction @Kato2016Neuroendoscopy.

=== Tendon-driven actuation principles

In tendon-driven architectures, actuation is typically realized by commanding tendon displacement (spooling length) or tendon tension. For common antagonistic arrangements, a joint is actuated by at least two tendons such that differential tension generates a net joint torque while co-contraction modifies apparent stiffness. When tendons span multiple joints, a single tendon displacement can induce coupled motions, which is advantageous for compact designs but complicates decoupled joint control~@Rao2021TDCRModeling. The mechanical benefit of remote actuation is that motors and gear reductions can be located near the base, reducing distal mass and inertia and thereby enabling higher angular accelerations and dynamic performance for a given torque budget~@Nemoto2022CableWrist.

The same properties that reduce distal inertia also reduce transmission rigidity. Tendon stretch, cable-pulley compliance, and frictional effects can cause configuration-dependent motion errors, phase lags, and hysteresis loops under load. These effects are not only relevant for force control but also for kinematic accuracy because they break the assumption of a unique, memoryless mapping between actuator displacement and end-effector pose~@Miyasaka2020HysteresisFriction @Kato2016Neuroendoscopy. As a result, tendon-driven systems are often controlled using either (i) local joint sensing (e.g., encoders placed near joints) to close the loop in joint space, or (ii) model-based compensation and identification to improve the actuator-to-joint mapping, depending on the available sensing and the targeted accuracy~@Miyasaka2020HysteresisFriction.

=== Kinematic modeling: from tendon space to task space

*Rigid-link jointed mechanisms.*
For tendon-driven mechanisms built from rigid links and discrete joints, the kinematic structure in task space is formally identical to that of a direct-drive serial manipulator once the joint coordinates are defined. The principal difference is that the commanded variables are naturally expressed in tendon space (tendon lengths or tensions) rather than joint space. Consequently, the overall mapping is typically decomposed into two stages: (i) a transmission model from tendon variables to generalized joint coordinates, and (ii) a conventional rigid-body forward kinematic chain from joint coordinates to end-effector pose. In practice, the transmission model is required because routing geometry and tendon elasticity determine how a commanded spool displacement converts into a joint angle, and multi-joint tendons can create coupling terms that are absent in direct-drive designs~@Miyasaka2020HysteresisFriction.

#faps-figure(
  tendon-mapping(),
  caption: [Two-stage kinematic mapping in tendon-driven mechanisms: tendon variables are mapped to joint coordinates through a transmission model that is affected by friction, hysteresis, and multi-joint coupling; joint coordinates are then mapped to end-effector pose through conventional forward kinematics.],
  short-caption: [Tendon-driven kinematic mapping stages],
) <fig:tendon_actuation_mapping>

*Continuum and cable-driven bending mechanisms.*
For tendon-driven continuum robots, joint coordinates are not associated with discrete revolute joints but with distributed deformation of a flexible backbone. A widespread modeling approach is the piecewise constant-curvature assumption, in which the backbone is approximated as a sequence of constant-curvature arcs. This assumption reduces an effectively infinite-dimensional shape description to a finite set of arc parameters, enabling closed-form forward and differential kinematics for many designs~@Webster2010ConstantCurvature. The assumption is frequently used as a baseline model and remains attractive for control and planning because it yields tractable Jacobians and efficient computations. However, tendon friction and hysteresis can substantially degrade the predictive accuracy of purely geometric constant-curvature mappings, motivating extended models that incorporate frictional memory effects and tension propagation along the tendons~@Kato2016Neuroendoscopy.

*Implications for inverse kinematics and control.*
In tendon-driven systems, the #ac("IK") problem is frequently formulated in actuator space (tendon lengths) rather than in joint space. Even if a rigid-link #ac("IK") solution exists in terms of joint angles, the implementation of that solution on real tendon-driven hardware can be limited by transmission nonlinearities. In particular, hysteresis implies that the same tendon command can yield different end-effector poses depending on motion history and external loading, such that a purely kinematic #ac("IK") solution may not be repeatable without feedback~@Kato2016Neuroendoscopy. For learning-based control pipelines, this motivates the separation between an _idealized kinematic model_ used for planning or workspace analysis and a _simulation/control model_ that includes compliance and control bandwidth limitations to represent actuation uncertainty~@Miyasaka2020HysteresisFriction.

=== Simulation considerations for tendon-driven systems in Isaac Sim

Tendon-driven mechanisms pose specific simulation challenges because their behavior depends on cable routing, compliance, and frictional effects that are not captured by joint kinematics alone. In #ac("USD")-based simulation pipelines, these effects must either be represented explicitly using tendon/cable primitives or approximated through coupled joints and compliant actuation.

*Articulation tendons and coupled #acp("DoF").*
Omniverse Physics (PhysX backend) provides an articulation tendon concept with two main variants: fixed tendons (coupling joint coordinates) and spatial tendons (imposing constraints on distances between selected links through attachment points). These constructs are intended to represent coupled joint relationships and cable-like constraints inside articulated mechanisms~@omni_physics_articulations_tendons. In principle, joint coupling through fixed tendons can emulate certain tendon-driven topologies by enforcing linear relationships between generalized coordinates. Spatial tendons can represent a cable path between attachments but still abstract away detailed contact mechanics inside routing guides~@omni_physics_articulations_tendons.

*URDF mimic joints as a pragmatic approximation.*
When a robot is imported via #ac("URDF"), coupled motion can be encoded by mimic joints. The Isaac Sim #ac("URDF") importer can apply the PhysX mimic joint mechanism to joints carrying a mimic tag, enabling linear coupling between a reference joint and a mimicking joint~@isaacsim_urdf_importer. This mechanism is frequently used to represent mechanically linked joints such as parallelogram linkages or differential couplings. For tendon-driven approximations, mimic joints can be used to enforce idealized coupling relationships that would otherwise arise from shared tendon routing. It is noted in the Omni Physics documentation that mimic joints can introduce numerical instability when enforced as stiff constraints and that compliance can be introduced to improve stability when competing constraints apply~@omni_physics_articulations_tendons.

*Limitations relevant to tendon-driven fidelity.*
Although tendon primitives and mimic couplings allow tendon-like behavior to be introduced into an articulation, several fidelity gaps remain for tendon-driven robots: (i) distributed friction along tendon routing and hysteresis are typically not captured by ideal constraints, (ii) tendon stretch and tension propagation require tuned compliance parameters to remain stable at simulation time steps, and (iii) multi-contact routing through pulleys and guides is usually simplified to a small set of attachment points. These limitations are significant because tendon friction and hysteresis are reported to dominate motion errors in tendon-driven systems in applications such as surgical robotics, and improved prediction accuracy is obtained only when frictional effects are included in the mapping~@Kato2016Neuroendoscopy @Miyasaka2020HysteresisFriction. As a consequence, tendon-driven robots are often simulated using a hybrid strategy: the _kinematic chain_ is represented by standard joints, while tendon effects are represented by coupled joints (tendons or mimic constraints) and by compliant joint drives tuned to reproduce the apparent stiffness/damping observed in the physical system. Where higher fidelity is required, custom actuation models that map tendon commands to joint torques with friction/hysteresis compensation are required~@Miyasaka2020HysteresisFriction.

=== Precision, dynamics, and compliance

Tendon-driven designs differ from direct-drive manipulators in both achievable dynamics and precision characteristics. Reduced distal inertia can enable rapid wrist motions and high dynamic bandwidth in configurations that would be limited by motor mass and gearbox inertia if actuators were placed distally~@Nemoto2022CableWrist. However, because the actuation forces are transmitted through compliant tendons and routed interfaces, the closed-loop behavior is sensitive to friction, elastic stretch, and hysteresis effects. These phenomena can manifest as configuration-dependent tracking error and reduced repeatability compared to stiff, direct-drive solutions, and they motivate calibration and model-based compensation strategies when high positional accuracy is required~@Miyasaka2020HysteresisFriction @Kato2016Neuroendoscopy.

The safety-performance tradeoff in physical interaction is classically addressed by introducing compliance in the actuation/transmission, which reduces impact severity and can improve robustness in contact-rich tasks at the cost of reduced rigidity~@Bicchi2004FastSoftArm. Therefore, tendon-driven designs can be regarded as mechanically aligned with manipulation scenarios in which force limiting and safe contact are prioritized over sub-millimeter absolute accuracy.

=== Workspace analysis and dexterity metrics <sec:workspace_analysis_sampling_metrics>

#reg-sym("sym:w", "sym:J_mat", "sym:kappa")

The workspace of a serial manipulator is the set of all end-effector poses that are reachable under joint limits and kinematic constraints. Workspace analysis is used to verify that a robot can reach task-relevant regions and to identify configurations that should be avoided due to singularities or poor motion quality~@Rastegar1990WorkspaceMonteCarlo @Dong2013WorkspaceDensity.

*Forward kinematics and sampling motivation.*
Forward kinematics (#ac("FK")) is defined as the mapping from a joint configuration $bold(q)$ to an end-effector pose, i.e., position and orientation of a designated tool frame. For a general serial chain, this mapping can be written as

$ bold(T)_"EE" = f(bold(q)), $ <eq:fk_mapping>

where $bold(T)_"EE" in S E(3)$ denotes a homogeneous transformation of the end-effector frame. In many practical systems, analytical derivation of workspace boundary surfaces is intractable due to high #ac("DoF"), joint coupling, or non-standard kinematics. In such cases, the workspace is frequently approximated numerically by sampling joint space and evaluating #ac("FK") repeatedly. The Monte Carlo approach is widely used because it is simple to implement, directly incorporates joint limits, and does not require explicit boundary derivation~@Rastegar1990WorkspaceMonteCarlo.

*Monte Carlo workspace sampling and voxel aggregation.*
In the Monte Carlo approach, configurations are sampled from a prescribed distribution over the admissible joint ranges. In the simplest implementation, each joint $q_i$ is sampled independently and uniformly within its limit interval. For each sample $bold(q)^((k))$, the corresponding end-effector pose is computed by #ac("FK"). The resulting set of poses is then aggregated into a discrete spatial representation, e.g., Cartesian voxels, to estimate reachability statistics per region. This computation is conceptually aligned with established robotics software workflows that generate reachable workspace point sets paired with joint configurations~@mathworks_generaterobotworkspace.

When voxel aggregation is used, the workspace is partitioned into a regular grid of bins (voxels) in position space (and optionally orientation space). Each sample contributes to the occupancy count of the voxel containing the sampled pose. This discretization supports additional metrics beyond mere reachability, including density-based indicators of how many joint-space configurations map to a given region~@Dong2013WorkspaceDensity.

*Yoshikawa manipulability.*
Dexterity is commonly evaluated using Jacobian-based indices. Let $J(bold(q))$ denote the geometric Jacobian that maps joint velocities to end-effector twist. The Yoshikawa manipulability measure is defined as~@Yoshikawa1985Manipulability

$ w(bold(q)) = sqrt(det(J(bold(q)) J(bold(q))^top)). $ <eq:yoshikawa_manipulability>

This scalar is proportional to the volume of the manipulability ellipsoid and becomes zero at kinematic singularities where the Jacobian loses rank. Higher values indicate that small joint motions can produce motion in a wider range of Cartesian directions, which is desirable for tasks requiring dexterous repositioning and local adjustments~@Yoshikawa1985Manipulability.

*Inverse condition number as an isotropy index.*
A complementary measure is derived from the Jacobian condition number. Salisbury and Craig introduced the use of Jacobian conditioning to identify well-conditioned (isotropic) operating points and to quantify error amplification through the kinematic mapping~@Salisbury1982ArticulatedHands. Let $sigma_min$ and $sigma_max$ denote the minimum and maximum singular values of $J(bold(q))$. The inverse condition number is defined as

$ kappa_"inv" (bold(q)) = sigma_min (J(bold(q))) / sigma_max (J(bold(q))). $ <eq:inv_condition_number>

This index lies in $[0,1]$, approaches zero near singular configurations, and equals one at perfectly isotropic configurations (equal singular values), where motion/force transmission properties are directionally uniform~@Salisbury1982ArticulatedHands.

*Reachability density.*
Reachability density is defined here as the number of sampled configurations whose end-effector poses fall within a given voxel. Under uniform joint sampling, this count is proportional to the joint-space volume that maps into the voxel region; thus, higher density indicates that more distinct configurations can realize poses in that region. This concept is closely related to workspace density formulations that assign each voxel the number of reachable points (or a normalized probability density) and interpret higher density as higher positional/orientational reach richness and, in discretely actuated systems, higher achievable pose resolution~@Dong2013WorkspaceDensity.

*Implications for task-space design in learning-based manipulation.*
For manipulation tasks in cluttered scenes and for #ac("RL")-based control, the workspace and dexterity metrics directly inform environment layout and action-space design. Task objects (e.g., pick targets, placement zones) are preferably positioned in regions with high reachability density and consistently high manipulability to reduce the probability that the robot is driven into near-singular configurations during exploration. Similarly, action bounds for end-effector motion primitives can be restricted to dexterous regions to improve learning stability and to reduce large corrective motions caused by kinematic ill-conditioning~@Yoshikawa1985Manipulability @Salisbury1982ArticulatedHands @Dong2013WorkspaceDensity. When tendon-driven compliance is present, these considerations become more important because poor kinematic conditioning can amplify transmission uncertainties into larger Cartesian errors, which in turn increases undesired contact forces during object interaction~@Miyasaka2020HysteresisFriction @Bicchi2004FastSoftArm.
