// Chapter 1: Introduction
#import "../../../shared/formatting/macros.typ": *
#import "../../../shared/formatting/acronyms.typ": *

= Introduction <ch:introduction>

== Motivation and Context

Post-consumer textile waste is rapidly expanding as a fraction of municipal solid waste, fundamentally driven by the massive production volumes and increasingly short product lifecycles of fast-fashion garments~@EllenMacArthur2017NewTextilesEconomy @Robinson2026FibreSorting. Within the European Union, *regulatory pressures are shifting waste management away from incineration and landfilling toward the mandatory separate collection and material recovery* of used textiles by 2025~@Robinson2026FibreSorting. However, the primary *bottleneck in any such recovery chain is the sorting stage*~@Lopes2026TextileRecyclingReview @Robinson2026FibreSorting. Here, heterogeneous garments arrive on conveyors as disorganized, crumpled, self-occluded, and often soiled items that must be accurately separated by material composition, color, and condition before reuse or fiber-to-fiber recycling~@Lopes2026TextileRecyclingReview @Nellstrom2022Siptex. Currently, state-of-the-art facilities rely heavily on *manual labor, which is characterized by high physical and ergonomic strain, poor working conditions, and limited throughput*~@Lopes2026TextileRecyclingReview @Halvorsen2025AutonomousTextileSorting @Imamoglu2024ErgonomicTextile. These severe operational limitations strongly *motivate the development of autonomous robotic systems capable of selectively retrieving, presenting, and classifying individual garments from moving streams*~@Lopes2026TextileRecyclingReview @Halvorsen2025AutonomousTextileSorting.

Robotic manipulation in this setting differs fundamentally from classical industrial pick-and-place. Garments are deformable, self-occluding and exhibit high inter-instance variability. Sensing is unreliable, and grasps frequently fail or slip. A manipulator that interacts with such objects benefits from intrinsic mechanical compliance: it can absorb impacts when colliding with stacked items on the conveyor, and it can tolerate small kinematic errors during grasping without injecting large forces into the object or the surrounding hardware. Tendon-driven mechanisms address exactly this requirement. By transmitting joint forces through tensile elements from remotely placed actuators, they reduce distal mass and inertia and introduce passive elasticity that is beneficial for contact-rich manipulation~@Rao2021TDCRModeling @Nemoto2022CableWrist @Bicchi2004FastSoftArm. The cable-driven antiparallelogram architecture studied in this thesis~@Walter2023Tensegrity @Klein2023 was experimentally shown to reduce peak impact forces by up to~83% relative to a comparable rigid arm~@Walter2023Tensegrity, making it a candidate manipulator for the textile-handling stage of the sorting pipeline.

Designing a controller for such a robot is, however, non-trivial. Tendon routing geometry, cable elasticity, friction and hysteresis create a non-linear mapping between actuator commands and joint motion that is difficult to capture analytically~@Miyasaka2020HysteresisFriction @Kato2016Neuroendoscopy. #ac("RL") has emerged as a viable alternative that learns control policies directly from interaction data, sidestepping the need for closed-form models~@SuttonBarto2018 @Kober2013Survey. The practical feasibility of #ac("RL") for high-#ac("DoF") manipulation rests in turn on #ac("GPU")-accelerated physics engines that run thousands of environment instances in parallel, allowing policy training to converge in hours rather than weeks of wall-clock time and without wear on physical hardware~@Makoviychuk2021IsaacGym. NVIDIA Isaac~Sim and the IsaacLab framework provide an integrated stack for this workflow, combining PhysX~5 articulated rigid-body dynamics, a #ac("USD")-based scene representation and a unified #ac("MDP") interface for large-scale policy training~@nvidia_isaac_sim_510_what_is @Mittal2025IsaacLab.

== Two-Part Project: Scope of this Thesis and Outlook to the Master Thesis

The work presented here is the first part of a two-part project carried out at the Institute for Factory Automation and Production Systems (FAPS) at Friedrich-Alexander-Universität Erlangen-Nürnberg. The long-term objective of the project is a multi-agent robotic cell in which a ceiling-mounted, tendon-driven manipulator selectively retrieves garments from a conveyor belt and hands them to a second, collaborative robot arm that stretches each item, presents it to a camera for damage classification, and finally sorts it into a condition-specific bin. Achieving this end-to-end pipeline requires capabilities that span rigid-body manipulation, deformable-object handling, multi-agent coordination, perception-based classification, and sim-to-real transfer.

This *project thesis* deliberately restricts its scope to the foundational layer of that vision. The *construction and verification* of a faithful simulation of the tendon-driven manipulator, and a first demonstration that #ac("RL") policies can control it on rigid-object pick-and-place tasks. Concretely, the present work delivers a modular Isaac~Sim scene, three actuation variants of the same robot (a #ac("PD")-driven baseline, a constant-tension cable model, and a physical antiparallelogram four-bar tendon model), a quantitative validation of these variants against step-response and workspace benchmarks, and `skrl` #ac("PPO") policies for a reach task and a cube-place task. The validated platform, reward shaping, training infrastructure and code base are explicitly designed to be re-used unchanged in the follow-up *master thesis*, which will extend the pipeline with PhysX deformable cloth simulation, integration of a second robot arm, vision-based damage classification, multi-agent coordination, and the #ac("ROS")~2 interfaces required for sim-to-real deployment. 
//Where the project thesis answers _"can this robot be modelled and controlled in simulation at all?"_, the master thesis will answer _"does the resulting system sort real garments?"_.

== Problem Statement and Objectives

Deploying a custom tendon-driven manipulator in a simulation-based #ac("RL") pipeline requires more than loading a #ac("URDF") . #ac("RL") policies trained against an unfaithful model are known to exploit simulator-specific artifacts and to fail on transfer~@Salvato2021RealityGapSurvey @Peng2018DynamicsRandomization. The specific manipulator considered here is a 5-#ac("DoF") arm consisting of a 2-#ac("DoF") prismatic positioning stage (linear motion in the $y$- and $z$-directions), a 3-#ac("DoF") tendon-driven distal section (a proximal antiparallelogram bending joint and a 2-#ac("DoF") cable-driven wrist), and a Robotiq~2F-140 parallel gripper as end-effector. The mechanism builds on the design described by Klein~@Klein2023 and Walter~_et~al._~@Walter2023Tensegrity. Within the Isaac~Sim/IsaacLab ecosystem, no native, #ac("RL")-compatible tendon primitive exists comparable to MuJoCo's tendon element (cf. @sec:prior_tendon_sim). The cable-driven antiparallelogram joint must therefore be modelled through custom Jacobian and body-force mappings before any learning can take place.

From this constellation, the thesis pursues four objectives:

+ *Modular and validated simulation model.*
  Construct a reproducible Isaac~Sim scene and a modular #ac("USD") assembly of the 5-#ac("DoF") manipulator, comprising a #ac("PD")-driven reference variant, a constant-tension tendon variant, and a physical antiparallelogram four-bar tendon variant that share the same kinematic interface.

+ *Quantitative model verification.*
  Verify the three actuation variants against the #ac("PID") step-response benchmark of Klein~@Klein2023 and against a Monte-Carlo workspace and manipulability characterisation, demonstrating that the simulated robot covers the intended task workspace with realistic dynamic behaviour.

+ *Reinforcement-learning baseline on rigid-object tasks.*
  Formulate two #ac("RL") tasks of increasing difficulty and train `skrl` #ac("PPO") policies~@SerranoMunoz2023skrl @Schulman2017PPO for each actuation variant, in order to quantify how the choice of actuation model affects sample efficiency, final return and success rate.

+ *Reusable foundation for the master thesis.*
  Document the simulation, validation and training infrastructure to a level of reproducibility sufficient for the master thesis to extend it with deformable cloth simulation, a second collaborative arm, camera-based damage classification, multi-agent coordination and #ac("ROS")~2-based sim-to-real preparation, without revisiting the tendon model itself.

A secondary research question that is _explicitly deferred_ to the master thesis, but already framed by the present work, concerns the transferability of the compliant tendon-driven wrist mechanism to a conventional industrial robot arm and whether such a transfer yields measurable manipulation benefits.

== Thesis Outline

This thesis is structured as follows.
@ch:background introduces the theoretical and technical background. #ac("RL") for robotic manipulation with an emphasis on #ac("PPO")~@Schulman2017PPO, tendon-driven and antiparallelogram-linkage mechanisms, workspace and dexterity metrics, rigid-body physics in PhysX~5, the Isaac~Sim/IsaacLab architecture~@Mittal2025IsaacLab, and the #ac("USD")/#ac("URDF") description formats underlying the modular scene.
@ch:research_gap reviews the state of the art along three converging axes ( #ac("GPU")-accelerated #ac("RL") for manipulation, tendon- and cable-driven robot simulation, and tensegrity-inspired serial arms ) and identifies the specific research gap addressed by the present thesis.

@ch:methodology details the methodological workflow. The physical robot description, the modular Isaac~Sim model construction, the custom tendon actuation layer with its three variants, the validation procedures (step-response and Monte-Carlo workspace analysis), the #ac("MDP") formulations of the reach and cube-place tasks, and the `skrl`-based training infrastructure.
@ch:results presents the quantitative results. Step-response and workspace metrics for the three actuation variants and learning curves and success rates for the trained #ac("PPO") policies on both tasks.

@ch:discussion interprets these results, contrasts them with related work and discusses the limitations of the chosen approach, in particular regarding simulation fidelity and the gap between the rigid-object tasks studied here and the deformable-object tasks targeted by the master thesis.
@ch:conclusion summarises the contributions of the project thesis and outlines the path toward the master thesis, where the validated platform will be extended toward the full multi-agent textile-sorting pipeline that motivates the project as a whole.