// Chapter 1: Introduction
#import "../../../shared/formatting/macros.typ": *
#import "../../../shared/formatting/acronyms.typ": *

= Introduction <ch:introduction>

== Motivation and Context

Tendon-driven robots are articulated mechanisms in which joint motion is generated by tensile elements that transmit forces from remotely placed actuators to the joints. This design reduces distal mass and inertia, enables compact joint packaging, and introduces intrinsic mechanical compliance that can be beneficial for contact-rich manipulation tasks~@Rao2021TDCRModeling @Nemoto2022CableWrist @Bicchi2004FastSoftArm. At the same time, the cable-based transmission introduces modeling complexity: tendon routing geometry, elasticity, friction, and hysteresis effects create a non-trivial mapping between actuator commands and joint motion that is difficult to capture with classical analytical models alone~@Miyasaka2020HysteresisFriction @Kato2016Neuroendoscopy.

#ac("RL") has emerged as a promising paradigm for learning robot control policies directly from interaction data, reducing the reliance on explicit analytical models and hand-crafted control strategies~@SuttonBarto2018 @Kober2013Survey. In the context of robotic manipulation, #ac("RL") has demonstrated the ability to discover effective policies for tasks involving continuous, high-dimensional control, contact-rich dynamics, and sparse feedback~@Kober2013Survey. Modern physics simulators with #ac("GPU")-accelerated parallel execution have become central enablers of this approach: by running thousands of environment replicas simultaneously, they provide the sample throughput required for stable policy learning while avoiding wear, risk, and slow data collection on physical hardware~@Makoviychuk2021IsaacGym.

NVIDIA Isaac Sim and the associated IsaacLab framework provide an integrated toolchain for this simulation-driven development. Isaac Sim offers high-fidelity physics simulation based on PhysX~5 with articulated rigid-body dynamics, contact modeling, and #ac("GPU")-accelerated pipelines within a #ac("USD")-based scene representation~@nvidia_isaac_sim_510_what_is. IsaacLab builds on top of Isaac Sim and provides a unified, modular interface for designing robotics tasks as #acp("MDP") and training policies at scale~@Mittal2025IsaacLab. Together, they enable a workflow in which robot models are constructed, validated, and used for policy training within a single, reproducible environment.

// COMMENT: The following paragraph frames the broader project context.
// It references the master thesis as a planned follow-up.
This thesis is the first part of a two-part project conducted at the Institute for Factory Automation and Production Systems (FAPS) at Friedrich-Alexander-Universität Erlangen-Nürnberg. The broader project goal is to develop a multi-agent robotic system for automated textile sorting from mixed waste streams, where a tendon-driven robot picks clothing items from a conveyor and a second robot arm stretches, inspects, and sorts them by condition. The present work establishes the simulation foundation and validates the tendon-driven robot model through basic manipulation tasks (reaching and placing rigid objects), providing the verified platform on which subsequent work will build.

== Problem Statement and Objectives

Deploying a custom tendon-driven manipulator for conveyor-based pick-and-place tasks requires a faithful simulation model that accurately represents the robot's kinematics, actuation characteristics, and workspace geometry. Without such a validated model, #ac("RL") policies trained in simulation may learn to exploit simulator-specific artifacts rather than developing behaviors that transfer to the physical system~@Salvato2021RealityGapSurvey @Peng2018DynamicsRandomization.

The specific robot considered in this thesis is a 5-#ac("DoF") manipulator consisting of a 2-#ac("DoF") prismatic positioning stage (providing linear motion in the $y$- and $z$-directions), a 3-#ac("DoF") tendon-driven arm (one proximal bending joint and a 2-#ac("DoF") cable-driven wrist), and a Robotiq 2F-140 parallel gripper as the end-effector. The design builds on the tendon-driven robot concept described by Klein~@Klein2023. Integrating this robot into a simulation-based #ac("RL") pipeline requires addressing several interconnected challenges: constructing a modular simulation scene, faithfully representing the tendon-driven actuation mechanism, validating the simulated robot against established benchmarks, and formulating #ac("RL") tasks that progressively build manipulation competence from basic skills to task-level behavior.

A further question addressed in subsequent work (master thesis) is whether the compliant tendon-driven wrist mechanism can be transferred to a standard industrial robot arm and whether such a transfer yields measurable benefits in manipulation performance.

The thesis pursues the following objectives:

+ *Validated tendon-driven robot model in simulation.*
  Construct and validate a modular simulation model of the 5-#ac("DoF") tendon-driven manipulator in Isaac~Sim that faithfully represents kinematics, actuation dynamics, and workspace geometry, such that it can serve as a reliable platform for #ac("RL")-based policy training.

+ *Progressive #ac("RL")-based manipulation skill acquisition.*
  Develop and evaluate #ac("RL") policies for manipulation tasks of increasing complexity comparing #ac("PD")-driven and tendon-driven actuation variants to quantify how actuation modeling influences learning performance.

+ *Foundation for deformable-object manipulation.*
  Establish a documented, reproducible simulation infrastructure that forms the basis for subsequent work on deformable cloth handling, multi-agent textile sorting, and sim-to-real transfer in the master thesis.

== Thesis Outline

This thesis is structured as follows.
@ch:background introduces the fundamentals required for this work, covering #ac("RL") for robotic manipulation with an emphasis on #ac("PPO")~@Schulman2017PPO, rigid-body physics simulation in PhysX~5, the NVIDIA Isaac~Sim and IsaacLab architecture~@Mittal2025IsaacLab, and tendon-driven robot kinematics and modeling.
@ch:research_gap reviews the state of the art in GPU-accelerated #ac("RL") for manipulation and tendon-driven robot simulation, and identifies the specific research gap addressed by this thesis.

@ch:methodology describes the methodological approach, including the simulation scene design, the modular robot model assembly, the tendon actuation implementation, the validation procedures (step-response analysis and workspace characterization), and the #ac("MDP") formulations for the reach and cube place tasks using `skrl` #ac("PPO")~@SerranoMunoz2023skrl @Schulman2017PPO.
@ch:results presents the quantitative and qualitative results: robot validation metrics and learned policy performance for both actuation variants across both tasks.

@ch:discussion discusses the implications and limitations of the approach, including simulation fidelity considerations and the effect of tendon-driven versus #ac("PD")-driven actuation on policy learning.
@ch:conclusion concludes the thesis and outlines the path toward the master thesis, where the validated simulation platform will be extended with deformable cloth simulation, multi-agent coordination, and sim-to-real transfer preparation.
