// Chapter 1: Introduction
#import "../../../shared/formatting/macros.typ": *
#import "../../../shared/formatting/acronyms.typ": *

= Introduction <ch:introduction>

== Motivation and Context

Post-consumer textile waste forms a rapidly growing fraction of municipal solid waste, driven by the high production volumes and short product lifecycles of fast-fashion garments~@EllenMacArthur2017NewTextilesEconomy @Robinson2026FibreSorting. Within the European Union, regulatory pressure is shifting waste management away from incineration and landfilling toward mandatory separate collection and material recovery of used textiles ~@Robinson2026FibreSorting. The primary bottleneck in any such recovery chain is the sorting stage~@Lopes2026TextileRecyclingReview @Robinson2026FibreSorting, where heterogeneous garments arrive on conveyors as crumpled, self-occluded and often soiled items that must be separated by material composition, color and condition before reuse or fiber-to-fiber recycling~@Lopes2026TextileRecyclingReview @Nellstrom2022Siptex. State-of-the-art facilities rely heavily on manual labor, which entails high physical and ergonomic strain, poor working conditions and limited throughput~@Lopes2026TextileRecyclingReview @Halvorsen2025AutonomousTextileSorting @Imamoglu2024ErgonomicTextile. These limitations motivate the development of autonomous robotic systems capable of selectively retrieving, presenting and classifying individual garments from moving streams~@Lopes2026TextileRecyclingReview @Halvorsen2025AutonomousTextileSorting.

Robotic manipulation in this setting differs fundamentally from classical industrial pick-and-place. Garments are deformable, self-occluding and exhibit high inter-instance variability, sensing is unreliable, and grasps frequently fail or slip. A manipulator that interacts with such objects benefits from intrinsic mechanical compliance, allowing it to absorb impacts when colliding with stacked items on the conveyor and to tolerate small kinematic errors during grasping without injecting large forces into the object or the surrounding hardware. Tendon-driven mechanisms address this requirement directly. By transmitting joint forces through tensile elements from remotely placed actuators, they reduce distal mass and inertia and introduce passive elasticity beneficial for contact-rich manipulation~@Rao2021TDCRModeling @Nemoto2022CableWrist @Bicchi2004FastSoftArm. The cable-driven architecture studied in this thesis~@Walter2023Tensegrity @Klein2023 has been shown experimentally to reduce peak impact forces by up to~83% relative to a comparable rigid arm~@Walter2023Tensegrity, qualifying it as a candidate manipulator for the textile-handling stage of the sorting pipeline.

Designing a controller for such a robot is non-trivial. Tendon routing geometry, cable elasticity, friction and hysteresis create a non-linear mapping between actuator commands and joint motion that is difficult to capture analytically~@Miyasaka2020HysteresisFriction @Kato2016Neuroendoscopy. #ac("RL") provides a viable alternative that learns control policies directly from interaction data, sidestepping the need for closed-form models~@SuttonBarto2018 @Kober2013Survey. The practical feasibility of #ac("RL") for high-#ac("DoF") manipulation in turn rests on #ac("GPU")-accelerated physics engines that run thousands of environment instances in parallel, allowing policy training to converge in hours rather than weeks of wall-clock time and without wear on physical hardware~@Makoviychuk2021IsaacGym. NVIDIA Isaac~Sim and the Isaac~Lab framework provide an integrated stack for this workflow, combining PhysX~5 articulated rigid-body dynamics, a #ac("USD")-based scene representation and a unified #ac("MDP") interface for large-scale policy training~@nvidia_isaac_sim_510_what_is @Mittal2025IsaacLab.

The work presented here is the first part of a two-part project carried out at the Institute for Factory Automation and Production Systems (FAPS) at Friedrich-Alexander-Universität Erlangen-Nürnberg. The long-term objective of the project is a multi-agent robotic cell in which a ceiling-mounted, tendon-driven manipulator selectively retrieves garments from a conveyor belt and hands them to a second collaborative arm that stretches each item, presents it to a camera for damage classification, and finally sorts it into a condition-specific bin. Achieving this end-to-end pipeline requires capabilities spanning rigid-body manipulation, deformable-object handling, multi-agent coordination, perception-based classification and sim-to-real transfer. The present project thesis restricts its scope to the foundational layer of that vision and is intended to be extended without modification of the tendon model itself by the subsequent master thesis.

== Problem Statement and Objectives

Deploying a custom tendon-driven manipulator in a simulation-based #ac("RL") pipeline requires more than loading a #ac("URDF"). #ac("RL") policies trained against an unfaithful model exploit simulator-specific artifacts and fail on transfer~@Salvato2021RealityGapSurvey @Peng2018DynamicsRandomization. The manipulator considered here is a 5-#ac("DoF") arm consisting of a 2-#ac("DoF") prismatic positioning stage (linear motion in the $y$- and $z$-directions), a 3-#ac("DoF") tendon-driven distal section (a proximal antiparallelogram bending joint and a 2-#ac("DoF") cable-driven wrist) and a Robotiq~2F-140 parallel gripper as end-effector. The mechanism builds on the design described by Klein~@Klein2023 and Walter~_et~al._~@Walter2023Tensegrity. Within the Isaac~Sim/Isaac~Lab ecosystem, no native #ac("RL")-compatible tendon primitive exists comparable to MuJoCo's tendon element (cf.~@sec:prior_tendon_sim). The cable-driven antiparallelogram joint must therefore be modeled through custom Jacobian and body-force mappings before any learning can take place. From this constellation, the thesis pursues four objectives:

+ *Modular and validated simulation model:*
  Construction of a reproducible Isaac~Sim scene and a modular #ac("USD") assembly of the 5-#ac("DoF") manipulator, comprising a #ac("PD")-driven reference variant, a constant-$J^top$ tendon variant and a physical tendon variant that share the same kinematic interface.

+ *Quantitative model verification:*
  Verification of the three actuation variants against the #ac("PID") step-response benchmark of Klein~@Klein2023 and against a Monte-Carlo workspace and manipulability characterization, demonstrating that the simulated robot covers the intended task workspace with realistic dynamic behavior.

+ *Reinforcement-learning baseline on rigid-object tasks:*
  Formulation of two #ac("RL") tasks of increasing difficulty and training of `skrl` #ac("PPO") policies~@SerranoMunoz2023skrl @Schulman2017PPO for each actuation variant, to quantify how the choice of actuation model affects sample efficiency, final return and success rate.

+ *Reusable foundation for the master thesis:*
  Documentation of the simulation, validation and training infrastructure to a level of reproducibility sufficient for the master thesis to extend it with deformable cloth simulation, a second collaborative arm, camera-based damage classification, multi-agent coordination and #ac("ROS")~2-based sim-to-real preparation, without revisiting the tendon model itself.

The methodological approach combines #ac("USD")-based modular scene composition, a custom tendon actuation layer implemented through analytic Jacobian mappings and body-force application, step-response and Monte-Carlo benchmarks for verification, and `skrl`-based #ac("PPO") training for two manipulation tasks of increasing difficulty. A secondary research question concerning the transferability of the compliant tendon-driven wrist mechanism to a conventional industrial robot arm is _explicitly deferred_ to the master thesis but already framed by the present work.

== Thesis Outline

The remainder of this thesis is structured as follows. @ch:background introduces the theoretical and technical background: #ac("RL") for robotic manipulation with an emphasis on #ac("PPO")~@Schulman2017PPO, tendon-driven and antiparallelogram-linkage mechanisms, workspace and dexterity metrics, rigid-body physics in PhysX~5, the Isaac~Sim/Isaac~Lab architecture~@Mittal2025IsaacLab, and the #ac("USD")/#ac("URDF") description formats underlying the modular scene. @ch:research_gap reviews the state of the art along three converging axes ( #ac("GPU")-accelerated #ac("RL") for manipulation, tendon- and cable-driven robot simulation, and tensegrity-inspired serial arms) and identifies the specific research gap addressed by the present thesis.

@ch:methodology details the methodological workflow. The physical robot description, the modular Isaac~Sim model construction, the custom tendon actuation layer with its three variants, the validation procedures (step-response and Monte-Carlo workspace analysis), the #ac("MDP") formulations of the reach and cube-place tasks, and the `skrl`-based training infrastructure. @ch:results presents the quantitative results. Step-response and workspace metrics for the three actuation variants together with learning curves and success rates for the trained #ac("PPO") policies on both tasks.

@ch:discussion interprets these results, contrasts them with related work and discusses the limitations of the chosen approach, in particular regarding simulation fidelity and the gap between the rigid-object tasks studied here and the deformable-object tasks targeted by the master thesis. @ch:conclusion summarizes the contributions of the project thesis and outlines the path toward the master thesis, where the validated platform will be extended toward the full multi-agent textile-sorting pipeline that motivates the project as a whole.