// Chapter 6: Discussion
#import "../../../shared/formatting/macros.typ": *
#import "../../../shared/formatting/acronyms.typ": *

= Discussion <ch:discussion>

This chapter interprets the results from @ch:results in relation to the objectives stated in @ch:introduction and the success criteria derived in @ch:research_gap. The interpretation distinguishes outcomes that satisfy the project-thesis goals, outcomes that connect the work to the related literature, outcomes that delimit the scope of the conclusions, and outcomes that translate into recommendations for the master thesis and other future work. The compact recap of the key findings and the outlook toward the master thesis are presented in @ch:conclusion to avoid duplication within the discussion.

== Evaluation of Outcomes <sec:discussion_outcomes>

The model validation satisfies the first project objective. The step-response comparison in @subsec:step_results shows that all three Isaac~Sim arm variants settle within $300 "ms"$, while the prismatic base joints settle below $200 "ms"$ with negligible steady-state error. The workspace analysis in @subsec:workspace_results shows that the disc-approximation model covers $99.72%$ of the desired task volume. Together these results satisfy the validation criterion defined in @ch:research_gap, because the simulated robot reaches the intended workspace and exhibits controlled dynamic behavior under the tested step commands.

The reach and cube-place experiments confirm the second and third project objectives for the #ac("PD") and constant-Jacobian tendon variants. On the reach task, both variants converge within $48"k"$ timesteps to total rewards above $+0.75$ and position tracking errors below $1 "cm"$ (@subsec:reach_performance). On the cube-place task, both variants achieve grasp rates above $94%$ and place success rates above $90%$ after $300"k"$ timesteps (@subsec:place_final). The near-equal performance of these two variants is the strongest positive result of the thesis. In the studied #ac("RL") setting, the constant $bold(J)^top$ cable-to-joint mapping introduces no measurable task-performance penalty relative to direct joint-position control.

The physical tendon variant produces a contrasting outcome. Its mean total reward plateaus at $-0.71$ over the last $10%$ of the $150"k"$-step horizon, with a policy standard deviation of $0.092$ against $0.021$ for the #ac("PD") baseline and $0.029$ for the constant-Jacobian tendon variant. On the cube-place task the variant reaches only $0.2%$ grasp rate and $0.0%$ place success. This outcome does not invalidate the physical antiparallelogram model. Instead, it localises the unresolved problem to the coupling between body-force tendon actuation, closed-chain linkage dynamics, and direct end-to-end policy learning, and thereby narrows the technical question for future work from general simulation feasibility to the design of an actuation interface for indirect force transmission.

The curriculum design supports the variants that already acquire the basic manipulation skill. The staged introduction of the distractor cube and the regularization terms produces only short transient reward dips in @subsec:curriculum_effect rather than permanent loss of performance, which indicates that the curriculum consolidates the pick-and-place sequence after grasping and transport are already established. The same curriculum is insufficient for the physical tendon variant, because the failure occurs upstream of the manipulation phases that the curriculum is designed to refine.

== Comparison with Related Work <sec:discussion_related_work>

The validation extends the predecessor work by Klein~@Klein2023, who established the base manipulator's workspace analysis, Gazebo simulation, #ac("PID") control procedure, and step-response comparison for the same cable-driven robot arm. The present thesis transfers this validation logic into Isaac~Sim and adds a systematic comparison between #ac("PD"), constant-Jacobian tendon, and physical antiparallelogram tendon model variants. The settling-time and workspace-coverage results therefore extend the earlier Gazebo-based model into a validated #ac("GPU")-accelerated representation rather than constituting a new isolated model.

The training results connect to tendon-driven #ac("RL") work outside the Isaac ecosystem. Or _et al._~@Or2023Robostrich apply curriculum #ac("RL") to a tendon-driven, high-#ac("DoF"), underactuated manipulator in MuJoCo, and Guist _et al._~@Guist2024PAMY2 motivate tendon drives through low moving mass and dynamic operation on the PAMY2 platform. The present thesis shares the use of tendon actuation and staged learning, but differs in the simulation stack and mechanism geometry. Cable tensions are implemented as explicit, observable Isaac~Lab action terms compatible with batched #ac("GPU") training, which complements rather than replaces the MuJoCo-based tendon-#ac("RL") workflows reported in those works.

The infrastructure results align with the direction established by Isaac~Gym and Isaac~Lab. Makoviychuk _et al._~@Makoviychuk2021IsaacGym demonstrate the value of fully #ac("GPU")-accelerated simulation and training with many parallel environments, and Mittal _et al._~@Mittal2025IsaacLab describe Isaac~Lab's manager-based architecture for modular robot-learning environments. The present work applies these capabilities to a non-standard tendon-driven manipulator instead of a conventional benchmark robot. The methodological contribution relative to the related #ac("RL") literature reviewed in @sec:prior_gpu_rl is the integration of a custom tendon-driven arm into the Isaac~Lab manager workflow with `skrl`-based #ac("PPO") training~@SerranoMunoz2023skrl @Schulman2017PPO.

The comparison remains bounded by the experimental scope. Prior contact-rich sim-to-real systems such as Factory and IndustReal address assembly tasks and transfer procedures for conventional robot hardware~@Narang2022Factory @Tang2023IndustReal. The present thesis performs neither sim-to-real transfer, nor physical validation and only limited domain randomization of the learned policies. Its result is therefore a validated simulation and training baseline rather than evidence of physical deployment readiness.

== Limitations of the Study <sec:discussion_limitations>

The first limitation concerns linkage model fidelity. The disc-approximation variant intentionally replaces the antiparallelogram elbow with a single revolute joint and a constant elbow lever arm. The simplification is justified for large-scale #ac("RL") because it reduces joint count and collision complexity, and @fig:elbow_comparison shows that it underestimates rather than overestimates reach. The strong performance of the constant-Jacobian tendon variant therefore does not transfer directly to the physical linkage, which introduces configuration-dependent force transmission and loop-closure constraints that the simplified models avoid.

The second limitation concerns tendon model fidelity. The tendon model applies cable tensions as direct joint torques or body forces and does not simulate tendon-specific physical behaviour. Elastic elongation under load, internal friction along the cable path, and the inertial and damping effects of the tendon mass are not represented in the simulation. These phenomena affect force transmission accuracy, introduce oscillatory compliance, and produce velocity-dependent losses that are absent from the present model. Their omission means that any policy trained on the current tendon action terms will encounter unmodeled stiffness and dissipation when deployed on hardware, which adds to the transfer risk already identified for the physical tendon variant. Characterising and modelling these effects is a task for future work. The Isaac~Lab implementation encapsulates the tendon actuation inside a custom action term that is decoupled from the task configuration and the reward pipeline. This design allows subsequent work to replace the idealised force-application layer with elastic, frictional, or inertia-compensating tendon models while reusing the existing validation procedure and scene definitions unchanged.

The third limitation concerns controller structure. All learned policies map observations directly to joint deltas or cable-tension commands. The poor performance of the physical tendon variant indicates that this flat action parameterization is insufficient for the body-force linkage model under the chosen reward formulation and training horizon. The experiments do not yet test hierarchical control, inner-loop tension regulation, impedance control, model-based compensation, or pretraining from the easier tendon variant.

The fourth limitation is the restriction to rigid-object tasks. The reach and cube-place tasks verify motion control and basic manipulation, but they do not reproduce the deformability, self-occlusion, grasp uncertainty, and perception requirements of textile sorting introduced in @ch:introduction. The cube-place task also relies on privileged simulation state instead of camera-based perception. The results therefore validate the robotic and #ac("RL") foundation, not the complete textile-sorting pipeline.

The fifth limitation concerns evaluation breadth. Each task is evaluated on the configured robot variants and training budgets reported in @ch:results, but the thesis does not present multi-seed statistical comparisons, ablation studies of individual reward terms, or systematic sweeps over #ac("PPO") hyperparameters.

The sixth limitation is the absence of physical policy deployment. The simulation dynamics are validated against Klein's benchmark and the workspace coverage is measured in simulation, but no learned policy is executed on hardware. Cable friction, backlash, sensor latency, motor-current limits, tendon wear, and unmodeled compliance therefore remain transfer risks rather than measured quantities, and any statement about real-world sorting performance lies outside the scope of this thesis.

== Practical Implications <sec:discussion_implications>

The constant-Jacobian tendon model is the practical working model for rigid-object #ac("RL") experiments. It preserves the cable-tension action interface while matching the #ac("PD") baseline on both tasks, which makes it suitable for developing task logic, reward terms, curricula, logging tools, and scene composition before training time is invested in the physical linkage variant.

The #ac("PD") variant remains valuable as a diagnostic baseline rather than as the final robot model. Its direct joint-position interface establishes the upper bound for task feasibility under the configured scene, reward, and #ac("PPO") setup. When the #ac("PD") variant succeeds and the tendon variant fails, the source of difficulty is the actuation model. When both fail, the source lies in task formulation, reward design, or scene configuration.

The physical tendon variant is best treated as a high-fidelity validation target rather than as the default training model. Its failure on cube place shows that direct end-to-end learning through body-force tendon commands is too difficult under the present setup. A staged workflow is therefore appropriate. Behaviors are developed and debugged on the #ac("PD") and constant-Jacobian variants and then transferred toward the physical linkage with additional low-level control support.

The validated workspace also supports mechanical and cell-layout decisions for the master thesis. The ceiling-mounted position and base travel cover the desired conveyor workspace in simulation, and the disc approximation provides a conservative lower bound on reach. The mounting concept therefore remains a fixed reference while subsequent work concentrates on deformable-object modeling, perception, and coordination.

== Recommendations and Lessons Learned <sec:discussion_recommendations>

The first lesson is that the three-variant structure is methodologically necessary. The #ac("PD") variant serves as the feasibility baseline, the constant-Jacobian tendon variant isolates the effect of cable-mediated actuation, and the physical tendon variant exposes the additional difficulty introduced by closed-chain body-force actuation. The separation makes the results interpretable, because task-design failures and actuation-model failures are not collapsed into a single training curve.

The second lesson is that actuation fidelity and learnability must be balanced explicitly. The reach and cube-place results show that the #ac("PPO") policy solves the manipulation task when the actuation interface is sufficiently transparent. The physical tendon variant therefore calls primarily for an intermediate actuation layer, such as low-level tension regulation or a hierarchical controller, that preserves the geometry-dependent dynamics while presenting a smoother learning problem to the policy.

The third lesson concerns curriculum design. The cube-place curriculum supports multi-stage manipulation once reaching and grasping are reliable, but it does not solve low-level actuation exploration. Future curricula must therefore separate two forms of progression. First from direct joint control to cable-tension control, and only then from simple rigid-object tasks toward more demanding manipulation scenarios.

The fourth lesson concerns evaluation breadth. Repeated training seeds, reward-term ablations, and sensitivity studies over tendon limits, solver iterations, and action scaling strengthen any future statement about the physical variant. Such studies clarify whether the observed failure stems from unstable learning, insufficient exploration, or an actuation interface unsuitable for direct policy control.

The fifth lesson is that reproducibility infrastructure functions as both a documentation outcome and a debugging tool. The automated plotting pipeline, TensorBoard diagnostics, monitoring tools, and shared Isaac~Lab configuration objects make results traceable across variants. Maintaining this structure simplifies future comparisons, because changes in performance are linked to explicit changes in the task, model, or controller.


