// Chapter 6: Discussion
#import "../../../shared/formatting/macros.typ": *
#import "../../../shared/formatting/acronyms.typ": *

= Discussion <ch:discussion>

This chapter interprets the results from @ch:results in relation to the objectives stated in @ch:introduction and the success criteria derived in @ch:research_gap. The interpretation distinguishes outcomes that satisfy the project-thesis goals, outcomes that connect the work to the related literature, outcomes that delimit the scope of the conclusions, and outcomes that translate into recommendations for the master thesis and other future work. The compact recap of the key findings and the outlook toward the master thesis are presented in @ch:conclusion to avoid duplication within the discussion.

== Evaluation of Outcomes <sec:discussion_outcomes>

The model validation satisfies the first project objective. The step-response comparison in @subsec:step_results shows that all three Isaac~Sim arm variants settle within $300 "ms"$, while the prismatic base joints settle below $200 "ms"$ with negligible steady-state error. The workspace analysis in @subsec:workspace_results shows that the disc-approximation model covers $99.72%$ of the desired task volume. Together these results satisfy the validation criterion defined in @ch:research_gap, because the simulated robot reaches the intended workspace and exhibits controlled dynamic behavior under the tested step commands.

The reach and cube-place experiments confirm the second and third project objectives for the #ac("PD") and constant-$J^top$ tendon variants. On the reach task, both variants converge within $48"k"$ timesteps to total rewards above $+0.75$ and position-tracking errors below $1 "cm"$ (@subsec:reach_performance), and both clear every reference agent by a wide margin. The trained policy reaches a $99.7 plus.minus 0.3 %$ (#ac("PD")) and $97.9 plus.minus 3.9 %$ (constant-$bold(J)^top$ tendon) success rate, against $79.3 %$ for the DLS-IK heuristic and $11.2$--$15.0 %$ for uniform-random exploration. On the cube-place task, both variants achieve grasp rates above $94 %$ and place success rates above $90 %$ after $300"k"$ timesteps (@subsec:place_final). This performance is moreover robust across the $N = 5$ training seeds: the #ac("PD") variant occupies a tight $[99.1 %, 100.0 %]$ success band and the tendon variant clusters at $98$--$100 %$ with only a single weaker seed at $91 %$, and the two head-to-head Welch comparisons against the strongest baseline remain significant at $p < 10^(-6)$ even after Bonferroni correction (@subsec:reach_significance).

The near-equal performance of these two variants is the central positive result of this thesis. In the studied #ac("RL") setting the constant $bold(J)^top$ cable-to-joint mapping introduces no measurable task-performance penalty relative to direct joint-position control. The strength of this claim is, however, deliberately bounded. It is an equivalence in _trained-policy task performance_ on the simulated robot, established for a single #ac("PPO") hyperparameter configuration and an $N = 5$ seed budget. It is neither a statement about hardware behaviour nor evidence that the physical antiparallelogram linkage is equally learnable (see @sec:discussion_limitations).

The physical tendon variant produces a contrasting outcome. The seed-aggregated reach evaluation in @tab:reach_results reports a success rate of $31.4 plus.minus 14.4 %$ across five independent training seeds, with the worst seed collapsing to $8.8 %$ and the best reaching only $46.2 %$. The mean final-step position error of $21.7 "cm"$ exceeds the $5 "cm"$ success threshold by more than a factor of four, and the per-seed distribution in @fig:reach_per_seed_scatter shows that no seed brings the median episode below the threshold. Measured against the baselines, the trained policy improves on uniform-random exploration by only $19.0$ percentage points ($31.4 %$ vs.~$12.3 %$) and stays on the same order of magnitude as unstructured exploration, in stark contrast to the more than eightfold margin obtained on the other two variants. On the cube-place task the variant reaches only $0.2 %$ grasp rate and $0.0 %$ place success. The two-sample Welch test against the uniform-random baseline yields $p = 0.041$ on the reach task and is therefore not significant after Bonferroni correction for the three pairwise tests reported in @subsec:reach_significance, consistent with Colas _et al._, who show that $N = 5$ comparisons are underpowered and subject to inflated small-sample error and should be treated as exploratory rather than confirmatory.
// Colas2018HowManySeeds — p.13 §4.2 + Fig.4 (β = 0.51 at N = 5) and p.19 §6 "Final recommendations". Uploaded PDF.
This outcome does not invalidate the physical tendon variant. Instead, it localises the unresolved problem to the coupling between body-force tendon actuation, closed-chain linkage dynamics, and direct end-to-end policy learning, and thereby narrows the technical question for future work from general simulation feasibility to the design of an actuation interface for indirect force transmission.

The curriculum design supports the variants that already acquire the basic manipulation skill. The staged introduction of the distractor cube and the regularization terms produces only short transient reward dips in @subsec:curriculum_effect rather than permanent loss of performance, which indicates that the curriculum consolidates the pick-and-place sequence after grasping and transport are already established. The same curriculum is insufficient for the physical tendon variant, because the failure occurs upstream of the manipulation phases that the curriculum is designed to refine.

== Comparison with Related Work <sec:discussion_related_work>

The validation extends the predecessor work by Klein~@Klein2023, who established the base manipulator's workspace analysis, Gazebo simulation, #ac("PID") control procedure, and step-response comparison for the same cable-driven robot arm. The present thesis transfers this validation logic into Isaac~Sim and adds a systematic comparison between #ac("PD"), constant-$J^top$ tendon, and physical tendon variants. The settling-time and workspace-coverage results therefore extend the earlier Gazebo-based model into a validated #ac("GPU")-accelerated representation rather than constituting a new isolated model.

The training results connect to tendon-driven #ac("RL") work outside the Isaac ecosystem. Or _et al._~@Or2023Robostrich apply curriculum #ac("RL") to a tendon-driven, high-#ac("DoF"), underactuated manipulator in MuJoCo, and Guist _et al._~@Guist2024PAMY2 motivate tendon drives through low moving mass and dynamic operation on the PAMY2 platform. The present thesis shares the use of tendon actuation and staged learning, but differs in the simulation stack and mechanism geometry. Cable tensions are implemented as explicit, observable Isaac~Lab action terms compatible with batched #ac("GPU") training, which complements rather than replaces the MuJoCo-based tendon-#ac("RL") workflows reported in those works.

The infrastructure results align with the direction established by Isaac~Gym and Isaac~Lab. Makoviychuk _et al._~@Makoviychuk2021IsaacGym demonstrate the value of fully #ac("GPU")-accelerated simulation and training with many parallel environments, and Mittal _et al._~@Mittal2025IsaacLab describe Isaac~Lab's manager-based architecture for modular robot-learning environments. The present work applies these capabilities to a non-standard tendon-driven manipulator instead of a conventional benchmark robot. The methodological contribution relative to the related #ac("RL") literature reviewed in @sec:prior_gpu_rl is the integration of a custom tendon-driven arm into the Isaac~Lab manager workflow with `skrl`-based #ac("PPO") training~@SerranoMunoz2023skrl @Schulman2017PPO.

The comparison remains bounded by the experimental scope. Prior contact-rich sim-to-real systems such as Factory and IndustReal address assembly tasks and transfer procedures for conventional robot hardware~@Narang2022Factory @Tang2023IndustReal. The present thesis performs neither sim-to-real transfer, nor physical validation and only limited domain randomization of the learned policies. Its result is therefore a validated simulation and training baseline rather than evidence of physical deployment readiness.

== Limitations of the Study <sec:discussion_limitations>

The first limitation concerns linkage model fidelity. The disc-approximation variant intentionally replaces the antiparallelogram elbow with a single revolute joint and a constant elbow lever arm. The simplification is justified for large-scale #ac("RL") because it reduces joint count and collision complexity, and @fig:elbow_comparison shows that it underestimates rather than overestimates reach. The strong performance of the constant-$J^top$ tendon variant therefore does not transfer directly to the physical linkage, which introduces configuration-dependent force transmission and loop-closure constraints that the simplified models avoid. In particular, the central equivalence result of @sec:discussion_outcomes is a property of the constant-$bold(J)^top$ approximation, in which the cable-to-joint mapping is held fixed, and must not be extrapolated to the configuration-dependent transmission of the real four-bar mechanism.

The second limitation concerns tendon model fidelity. The tendon model applies cable tensions as direct joint torques or body forces and does not simulate tendon-specific physical behaviour. Elastic elongation under load, internal friction along the cable path, and the inertial and damping effects of the tendon mass are not represented in the simulation. These phenomena affect force transmission accuracy, introduce oscillatory compliance, and produce velocity-dependent losses that are absent from the present model. Their omission means that any policy trained on the current tendon action terms will encounter unmodeled stiffness and dissipation when deployed on hardware, which adds to the transfer risk already identified for the physical tendon variant. Characterising and modelling these effects is a task for future work. The Isaac~Lab implementation encapsulates the tendon actuation inside a custom action term that is decoupled from the task configuration and the reward pipeline. This design allows subsequent work to replace the idealised force-application layer with elastic, frictional, or inertia-compensating tendon models while reusing the existing validation procedure and scene definitions unchanged.

The third limitation concerns controller structure. All learned policies map observations directly to joint deltas or cable-tension commands. The poor performance of the physical tendon variant indicates that this flat action parameterization is insufficient for the body-force linkage model under the chosen reward formulation and training horizon. The experiments do not yet test hierarchical control, inner-loop tension regulation, impedance control, model-based compensation, or pretraining from the easier tendon variant.

The fourth limitation is the restriction to rigid-object tasks. The reach and cube-place tasks verify motion control and basic manipulation, but they do not reproduce the deformability, self-occlusion, grasp uncertainty, and perception requirements of textile sorting introduced in @ch:introduction. The cube-place task also relies on privileged simulation state instead of camera-based perception. The results therefore validate the robotic and #ac("RL") foundation, not the complete textile-sorting pipeline.

The fifth limitation concerns evaluation breadth. The reach task is evaluated over $N = 5$ independent training seeds per variant and $500$ episodes per (variant, seed) cell, which matches the five trials per evaluation used by Henderson _et al._ in their own reproducibility study but lies well below the $N gt.eq 20$ samples that Colas _et al._ identify as required for confirmatory bootstrap-based inference~@Henderson2018DeepRLMatters~@Colas2018HowManySeeds.
// Henderson2018DeepRLMatters — p.2 §"Experimental Analysis" (five trials per evaluation). Uploaded arXiv PDF.
// Colas2018HowManySeeds — p.18--19 §6 "Final recommendations" ("A bootstrap test should not be used with less than 20 samples"). Uploaded PDF.
This sample size is adequate for ranking the three actuation variants by an order of magnitude, but it is too small to support strong claims about the physical tendon variant, whose per-seed success rate spans the entire range $[8.8 %, 46.2 %]$ (@fig:reach_per_seed_scatter). The cube-place task is currently evaluated on a single seed per variant, which was omitted from the multi-seed protocol for time and scope reasons (cf.~@sec:place_results). Its metrics are therefore point estimates without a cross-seed dispersion measure. Reward-term ablations and systematic sweeps over #ac("PPO") hyperparameters and tendon-action scaling are also out of scope and are listed among the master-thesis recommendations below.

The sixth limitation is the absence of physical policy deployment. The simulation dynamics are validated against Klein's benchmark and the workspace coverage is measured in simulation, but no learned policy is executed on hardware. Cable friction, backlash, sensor latency, motor-current limits, tendon wear, and unmodeled compliance therefore remain transfer risks rather than measured quantities, and any statement about real-world sorting performance lies outside the scope of this thesis.

== Practical Implications <sec:discussion_implications>

The constant-$J^top$ tendon variant is the practical working model for rigid-object #ac("RL") experiments. It preserves the cable-tension action interface while matching the #ac("PD") baseline on both tasks, which makes it suitable for developing task logic, reward terms, curricula, logging tools, and scene composition before training time is invested in the physical linkage variant.

The #ac("PD") variant remains valuable as a diagnostic baseline rather than as the final robot model. Its direct joint-position interface establishes the upper bound for task feasibility under the configured scene, reward, and #ac("PPO") setup. When the #ac("PD") variant succeeds and the tendon variant fails, the source of difficulty is the actuation model. When both fail, the source lies in task formulation, reward design, or scene configuration.

The physical tendon variant is best treated as a high-fidelity validation target rather than as the default training model. Its failure on cube place shows that direct end-to-end learning through body-force tendon commands is too difficult under the present setup. A staged workflow is therefore appropriate. Behaviors are developed and debugged on the #ac("PD") and constant-$J^top$ tendon variants and then transferred toward the physical linkage with additional low-level control support.

The validated workspace also supports mechanical and cell-layout decisions for the master thesis. The ceiling-mounted position and base travel cover the desired conveyor workspace in simulation, and the disc approximation provides a conservative lower bound on reach. The mounting concept therefore remains a fixed reference while subsequent work concentrates on deformable-object modeling, perception, and coordination.

== Recommendations and Lessons Learned <sec:discussion_recommendations>

The first lesson is that the three-variant structure is methodologically necessary. The #ac("PD") variant serves as the feasibility baseline, the constant-$J^top$ tendon variant isolates the effect of cable-mediated actuation, and the physical tendon variant exposes the additional difficulty introduced by closed-chain body-force actuation. The separation makes the results interpretable, because task-design failures and actuation-model failures are not collapsed into a single training curve.

The second lesson is that actuation fidelity and learnability must be balanced explicitly. The reach and cube-place results show that the #ac("PPO") policy solves the manipulation task when the actuation interface is sufficiently transparent. The physical tendon variant therefore calls primarily for an intermediate actuation layer, such as low-level tension regulation or a hierarchical controller, that preserves the geometry-dependent dynamics while presenting a smoother learning problem to the policy.

The third lesson concerns curriculum design. The cube-place curriculum supports multi-stage manipulation once reaching and grasping are reliable, but it does not solve low-level actuation exploration. Future curricula must therefore separate two forms of progression. First from direct joint control to cable-tension control, and only then from simple rigid-object tasks toward more demanding manipulation scenarios.

The fourth lesson concerns evaluation breadth. The $N = 5$ seed budget used here is sufficient to demonstrate the order-of-magnitude gap between the physical tendon variant and the other two, but the bimodal per-seed distribution in @fig:reach_per_seed_scatter and the non-significant Welch test in @subsec:reach_significance show that it is too small to characterise the physical tendon variant itself. Future work should therefore retrain the physical tendon variant with at least $N = 10$ seeds (and ideally $N gt.eq 20$ as recommended by Colas _et al._)~@Colas2018HowManySeeds, combined with reward-term ablations and sensitivity studies over tendon limits, solver iterations, and action scaling. Such studies will clarify whether the observed failure stems from unstable learning, insufficient exploration, or an actuation interface unsuitable for direct policy control.

The fifth lesson is that reproducibility infrastructure functions as both a documentation outcome and a debugging tool. The automated plotting pipeline, TensorBoard diagnostics, monitoring tools, and shared Isaac~Lab configuration objects make results traceable across variants. Maintaining this structure simplifies future comparisons, because changes in performance are linked to explicit changes in the task, model, or controller.


