"""Bake the "awake" variants of the physical (four-bar) tensegrity arm USDs.

A body-force-driven articulation that PhysX puts to sleep silently ignores
tensor-API external forces, freezing the cable-driven arm.  Zeroing the sleep
threshold at the *articulation* root proved insufficient (Isaac Lab 0.54,
PhysX GPU); this tool zeroes ``physxRigidBody:sleepThreshold`` and
``:stabilizationThreshold`` on every rigid body under the robot prim and writes
a ``*_awake.usd`` next to each source asset.  The physical reach configs
(``robots/tendon_robot_cfg.py``) reference the ``*_awake`` assets.

The loop-closure joint (``coupler_right_joint``) is kept ENABLED — the physical
four-bar is the model; do not disable it.

Usage (Isaac Sim's bundled Python or an env with the Isaac extscache on
ISAAC_PATH):

    conda run --no-capture-output -n env_isaaclab \
        python3 tools/make_physical_awake_usd.py

Regenerate after re-authoring the source physical USDs from
``build_tensegrity_arm_usd.py`` / Robot Assembler.
"""

from __future__ import annotations

import ctypes
import glob
import os
import shutil
import sys


def _bootstrap_pxr() -> None:
    """Make ``pxr`` importable and register the PhysX USD schema plugins.

    Mirrors ``build_tensegrity_arm_usd.py`` — locates the Isaac extscache USD
    libraries, preloads them with RTLD_GLOBAL, and registers the PhysxSchema
    plugins before the schema types are used.
    """
    isaac = os.environ.get("ISAAC_PATH") or os.path.expanduser("~/Isaac/IsaacSim")
    extscache = os.path.join(isaac, "extscache")
    if not os.path.isdir(extscache):
        raise SystemExit(f"Isaac extscache not found at {extscache}; set ISAAC_PATH.")

    def _latest(pattern: str) -> str | None:
        matches = sorted(glob.glob(os.path.join(extscache, pattern)))
        return matches[-1] if matches else None

    usd_libs = _latest("omni.usd.libs-*")
    physx = _latest("omni.usd.schema.physx-*")
    if not usd_libs or not physx:
        raise SystemExit("Could not locate omni.usd.libs / omni.usd.schema.physx in extscache.")

    for p in (physx, usd_libs):
        if p not in sys.path:
            sys.path.insert(0, p)
    # LD_LIBRARY_PATH is normally set by python.sh; when running under conda the
    # loose libusd .so files must be resolvable — preload them explicitly.
    os.environ["LD_LIBRARY_PATH"] = os.path.join(usd_libs, "bin") + ":" + os.environ.get("LD_LIBRARY_PATH", "")
    for so in sorted(glob.glob(os.path.join(usd_libs, "bin", "libusd_*.so"))):
        try:
            ctypes.CDLL(so, ctypes.RTLD_GLOBAL)
        except OSError:
            pass
    for so in sorted(glob.glob(os.path.join(physx, "bin", "*.so"))):
        try:
            ctypes.CDLL(so, ctypes.RTLD_GLOBAL)
        except OSError:
            pass

    from pxr import Plug  # noqa: PLC0415

    reg = Plug.Registry()
    for sub in ("PhysxSchema", "PhysxSchemaAddition", "OmniUsdPhysicsDeformableSchema"):
        resources = os.path.join(physx, "plugins", sub, "resources")
        if os.path.isdir(resources):
            reg.RegisterPlugins(resources)


_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
_SOURCES = [
    "res/Tensegrity/fivedof_manipulator/fivedof_linear_base_physical_robotiq2f140.usd",
    "res/Tensegrity/threedof_arm/tensegrity_threedof_arm_physical.usd",
]


def _bake_awake(src: str, dst: str) -> None:
    from pxr import PhysxSchema, Usd, UsdPhysics

    shutil.copyfile(src, dst)
    stage = Usd.Stage.Open(dst)
    n_bodies = 0
    for prim in stage.Traverse():
        if prim.HasAPI(UsdPhysics.RigidBodyAPI):
            api = PhysxSchema.PhysxRigidBodyAPI(prim) or PhysxSchema.PhysxRigidBodyAPI.Apply(prim)
            api.CreateSleepThresholdAttr(0.0)
            api.CreateStabilizationThresholdAttr(0.0)
            n_bodies += 1
    stage.GetRootLayer().documentation = (
        "Awake variant of the physical antiparallelogram arm: per-rigid-body "
        "sleep/stabilization thresholds zeroed so the body-force-driven arm is "
        "never put to sleep (a sleeping articulation ignores tensor-API forces). "
        "Loop-closure joint kept enabled. Generated by tools/make_physical_awake_usd.py."
    )
    stage.Save()
    print(f"  {os.path.relpath(dst, _REPO_ROOT)}: zeroed sleep on {n_bodies} bodies")


def main() -> None:
    _bootstrap_pxr()
    print("Baking awake physical-arm USDs:")
    for rel in _SOURCES:
        src = os.path.join(_REPO_ROOT, rel)
        if not os.path.isfile(src):
            print(f"  [skip] source not found: {rel}")
            continue
        dst = src.replace(".usd", "_awake.usd")
        _bake_awake(src, dst)


if __name__ == "__main__":
    main()
